// daily cron route (Vercel Cron Jobs) — generated by Nous, IMP-238/IMP-249.
import { NextResponse } from "next/server";

export const runtime = "nodejs";

export async function GET(request: Request) {
  // IMP-249 — verify the Vercel-injected CRON_SECRET. Vercel Cron sends
  // `Authorization: Bearer $CRON_SECRET`. Reject anything else (401).
  const expected = process.env.CRON_SECRET;
  const auth = request.headers.get("authorization");
  if (!expected || auth !== `Bearer ${expected}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // TODO: scheduled work (replaces a container-hosted scheduler).
  return NextResponse.json({ ran: true });
}
