// createTestDb — in-process Postgres (pglite) with the emitted schema applied
// (generated by Nous, IMP-305 / TE-2). The real-DB seam fixture: no Docker, no
// external database, deterministic and offline. It replays the SAME migration
// SQL the dev loop applies via `drizzle-kit push`, so a seam test drives the
// real tables + constraints, never a mock (see docs/dev-guide/TESTING.md §4).
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import * as schema from "../schema";

const migrationsDir = join(dirname(fileURLToPath(import.meta.url)), "..", "migrations");

/** A fresh in-memory Postgres with every generated migration applied, wrapped
 *  in Drizzle bound to the emitted schema. Call once per test (cheap). */
export async function createTestDb() {
  const client = new PGlite();
  const files = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  for (const f of files) {
    await client.exec(readFileSync(join(migrationsDir, f), "utf8"));
  }
  return drizzle({ client, schema });
}
