<!-- agent-sync: 9a0cb1eee459 | source: CLAUDE.md | DO NOT EDIT — this file is auto-generated from CLAUDE.md. Edit CLAUDE.md then run: python3 nous_agent_sync.py -->
# CLAUDE.md — Ledger

> Project intelligence file for AI-assisted development.
> This file is auto-generated by Nous Step 15 (Developer Package Generator).

## Dev Package — What This Is

This repository is the **dev package** — a ready-to-code monorepo generated by the
Nous product design pipeline. It contains everything you need to implement the product:

| What | Where | Read when |
|------|-------|-----------|
| **This file (CLAUDE.md)** | Root | Always — architecture rules, current sprint, coding standards |
| **Sprint plan** | `docs/stories/SPRINT_PLAN.md` | Before picking a story — shows all sprints, status, execution order |
| **Story files** | `docs/stories/sprint-N/*.md` | Before coding — full spec: ACs, API endpoints, entity changes, screen wiring |
| **HTML specs** | `docs/specs-html/*.html` | Visual reference — open in browser to see rendered story specs |
| **Screen specs (TOON)** | `docs/screens/*.json` | For UI implementation — `dataSource` tells you which API to call per section |
| **HTML mocks** | `docs/mocks/*.html` | Visual prototypes — open in browser to see the intended design |
| **Architecture** | `docs/architecture/ARCHITECTURE.md` | For bounded context structure, API conventions, event bus |
| **Decisions** | `docs/decisions/DECISIONS.md` | When unsure about a design choice — 140+ documented decisions |
| **API registry** | `docs/api-contract-registry.json` | Before implementing endpoints — source of truth for all API paths |
| **Navigation map** | `docs/specs/07c_navigation_map.json` | **Before adding a route, sidebar item, or user flow — authoritative registry** |
| **Nav map dev guide** | `docs/dev-guide/NAVIGATION.md` | Explains how to read + update the nav map; documents the invariant |
| **Feature backlog** | `docs/specs/07b_features_backlog.md` | Feature-level specs (FT-NNN) — context for which stories implement what |

### Dev-guide references (load on demand)

CLAUDE.md is intentionally compact. When you need the detailed reference:

| Topic | File | Load when |
|-------|------|-----------|
| Frontend rules (22 patterns) | `docs/dev-guide/FRONTEND.md` | Implementing any screen/page/component |
| Coding standards (factory methods, exception types, tenant extraction, M:N endpoints, phone/currency/email) | `docs/dev-guide/STANDARDS.md` | Writing any Spring controller or shared form/display |
| Security patterns (JWT, `@PreAuthorize`, tests, tenant access) | `docs/dev-guide/SECURITY.md` | Adding an auth'd controller or security test |
| Testing patterns + tool matrix + coverage targets | `docs/dev-guide/TESTING.md` | Writing any unit/integration/e2e test |
| Nous feedback events + AC verification protocol | `docs/dev-guide/FEEDBACK.md` | Before starting, reporting progress, or marking `done` |
| Build verification gate + rejection criteria | `docs/dev-guide/DEFINITION_OF_DONE.md` | Before marking any story `done` |
| Commit message conventions (US-NNN / CHG-NNN required) | `docs/dev-guide/COMMITS.md` | Installing git hooks; writing commit messages |

When someone says "re-read the dev package", read this file + the sprint plan + the
story file for whatever you're working on — then pull in the relevant dev-guide file
for the area you're working in.

## Navigation & routes — authoritative source

`docs/specs/07c_navigation_map.json` is the **single source of truth** for routes,
sidebar items, navigation edges, and user flows.

**The invariant**: every `apps/web/src/app/**/page.tsx` must have a matching entry
in `routes[].path` of the nav map. The build enforces this via `infra/scripts/validate-routes.sh`.
**No exemptions, no bypasses.** If you need a route the map doesn't have, update
the map in Nous first (via CHG-NNN), sync, then code.

**Sidebar**: `apps/web/src/components/shell/nav-items.gen.ts` is **auto-generated**
from the nav map. Never edit it. After any nav map change, run:

```
./infra/scripts/regenerate-sidebar.py
```

**Scaffolding a new page**:

```
./infra/scripts/scaffold-route.sh SCR-NN
```

Full guide: `docs/dev-guide/NAVIGATION.md`

## Project Overview

**Ledger** — built for Organization.

- **Organization:** Organization
- **Owner:** Owner
- **Architecture:** DDD bounded contexts in monorepo
- **Backend:** nextjs  / typescript 
- **Frontend:** nextjs  / react  / TypeScript
- **Database:** postgres  (Flyway migrations)
- **Auth:** keycloak  (OIDC / JWT)
- **AI:** RAG with pgvector + Claude API

## Quick Start

```bash
# 1. Start infrastructure
task infra

# 2. Build backend
task api

# 3. Start frontend
task web

# Or all at once:
task dev
```



## Repository Structure

```
apps/
  api/          # nextjs  typescript  — REST API
  web/          # nextjs  — SPA with SSR
packages/
  db/           # Flyway migrations and seed data
  design-system/# Tokens, tailwindcss preset
infra/
  docker-compose.yml
  app/     # Auth realm export
  scripts/      # Setup, run, seed, reset
docs/
  stories/      # User stories by sprint
  specs/        # ER model, screens, navigation map
  screens/      # TOON JSON screen specifications (source of truth for UI)
  mocks/        # HTML prototypes (visual reference)
  decisions/    # Product decisions
  dev-guide/    # Security, testing, and standards reference (full code examples)
```

## Backend Architecture Rules

1. **DDD layers per context:** `api/` → `application/` → `domain/` → `infrastructure/`
2. **Domain MUST NOT depend on infrastructure** — enforced by ArchUnit
3. **All entities extend `BaseEntity`** — UUID id, tenant_id, created_at, updated_at
4. **Tenant isolation via `tenant_id`** on every table (schema-per-tenant designed, row-level MVP)
5. **Events via Spring ApplicationEvents** (R1); outbox pattern planned for R2
6. **Flyway for all schema changes** — never use ddl-auto=update
7. **Cursor-based pagination** for all list endpoints
8. **JWT validation** via Spring Security OAuth2 Resource Server
9. **Soft delete** (`deleted_at` + `is_deleted`) on transactional entities
10. **NEVER use `jwt.getSubject()` directly (DEC-138)** — the DB stores `keycloak_id` as
    the Keycloak `preferred_username` (e.g. `"admin"`, `"seller"`), NOT the Keycloak UUID
    in the `sub` claim. Always use `JwtUtils.resolveKeycloakId(jwt)` to get the identity
    string, then look up the user via `UserRepository.findByKeycloakId()`. The call
    `UUID.fromString(jwt.getSubject())` is BANNED — it returns the Keycloak realm UUID
    which does not match any `app_users.id` value in the database.
11. **JSONB columns** — when a JPA entity maps a PostgreSQL JSONB column, use
    `@JdbcTypeCode(SqlTypes.JSON)` on the field (Hibernate 6+). The corresponding Flyway
    migration must use `jsonb` type. Test the round-trip (save → load → verify nested keys).
12. **CORS is configured in SecurityConfig** — frontend origins `localhost:3000` and `:3001`
    are allowed. If adding a new origin, update `corsConfigurationSource()` in SecurityConfig.
    Never disable CORS entirely; always list explicit origins.

## Architecture Wiring

The scaffold includes working security infrastructure. **Do not reinvent.** Reference existing
classes, don't create alternatives. Full patterns + code templates:
[`docs/dev-guide/SECURITY.md`](docs/dev-guide/SECURITY.md).

### JWT Identity Contract (DEC-138 — before any controller)

| JWT claim | Value | Use for |
|---|---|---|
| `sub` | Keycloak realm UUID | **NEVER** use for DB lookup |
| `preferred_username` | Username string | `app_users.keycloak_id` — primary DB lookup key |
| `org_id` | Tenant UUID | `app_users.tenant_id`, all multi-tenant queries |
| `email` | Email address | Display only |

Use `JwtUtils.resolveKeycloakId(jwt)` + `userRepository.findByKeycloakId(...)`. Never
`jwt.getSubject()` or `UUID.fromString(jwt.getSubject())` (returns Keycloak realm UUID,
not DB user UUID).

### Existing Security Files (do not recreate)

| File | Purpose | Package |
|------|---------|---------|
| `SecurityConfig.java` | Spring Security filter chain, JWT validation, RBAC | `shared.security` |
| `KeycloakJwtAuthenticationConverter.java` | Maps realm_access.roles → Spring ROLE_*; principal = preferred_username | `shared.security` |
| `JwtUtils.java` | `extractTenantId(jwt)` + `resolveKeycloakId(jwt)` | `shared.api` |
| `TenantFilter.java` | Extracts org_id → thread-local tenant context | `shared.security` |
| `TenantContext.java` | Domain interface for tenant access (inject this) | `shared.domain.tenant` |
| `BaseEntity.java` | UUID id, tenantId, timestamps | `shared` |
| `ArchitectureTest.java` | DDD layer enforcement + tenant isolation rules | test root |

Modify auth behavior in THESE files. Do not create parallel auth mechanisms.

Controller pattern, test helper (DEC-138 JWT setup), service-tenant access patterns →
[`SECURITY.md`](docs/dev-guide/SECURITY.md).




## Frontend Rules

Core rules (the ones that most often get violated):

1. **App Router only** — no pages/ directory. Server Components by default; `"use client"` only when needed.
2. **TOON JSON is authoritative for layout** — read `docs/screens/SCR-NN.json` before implementing. Wire each section's `dataSource` + `states` (loading/empty/error) exactly.
3. **HTML mocks are VISUAL REFERENCES ONLY** — `docs/mocks/*.html` are static prototypes for pixel comparison. Never copy mock HTML into the app; never use as "fallback UI".
4. **ALL API calls use the shared client** — `apiGet`/`apiPost` from `lib/api/client`. Raw `fetch()` on `/api/v1/*` is a bug.
5. **No dev mocks / fake auth** — any `if (devMode)` branch returning fake sessions is a rejection-level defect. Mocks only in `*.test.*` / `*.spec.*`.
6. **App state comes from the backend** — never hardcode `onboardingComplete`, feature flags, or fallback fixtures. API unavailable → loading/error state.
7. **Every page has loading, empty, and error states** — no blank screens. Silent failures are rejection-level.
8. **i18n via `useLocale()` hook** — never hardcode user-facing strings. Default `en-US`. Mixed-language view = broken i18n.
9. **Role gating via `hasMinRole()`** — `seller < manager < director < admin`. Imported from `lib/auth/roles.ts`.
10. **Redirects use named routes from `lib/routes.ts`** — never hardcode redirect paths as strings.
11. **`data-testid` matches TOON JSON `id`** — validated by `e2e/toon-fidelity.spec.ts`.
12. **Design tokens from `packages/design-system`** — never hardcode colors. Zustand for client state (no Redux/Context). zod for form validation.

Full reference (detailed patterns, API contract registry rules, screen-to-API wiring recipe):
[`docs/dev-guide/FRONTEND.md`](docs/dev-guide/FRONTEND.md)

## Version-Specific Constraints (IMPORTANT)

These rules are derived from the exact framework versions in this project.
Violating them causes compile/test failures. **Read before writing any code.**

### nextjs 



## Shared Contracts & Entity Conventions

When multiple stories touch the same entity, they MUST use consistent APIs.
**Before writing code, check if the entity already exists.** If it does, use its 
existing factory methods and field names — do NOT create alternative constructors.

### Entity Naming Conventions

| Convention | Rule | Example |
|-----------|------|---------|
| Java class | PascalCase | `com.example.app.sales.domain.Opportunity` |
| DB table (`@Table`) | snake_case | `opportunity` |
| Compound tables | snake_case | `funnel_definition`, `commercial_plan`, `funnel_stage` |
| FK columns | `<entity>_id` | `opportunity_id`, `tenant_id`, `plan_id` |
| Audit columns | Standard set | `id`, `tenant_id`, `created_at`, `updated_at`, `deleted_at`, `is_deleted` |

### Factory Method Convention

Full example: [`docs/dev-guide/STANDARDS.md`](docs/dev-guide/STANDARDS.md)

- Use `MyEntity.create(tenantId, ...)` — NEVER `new MyEntity()` + setters
- Named variants: `createDraft(...)`, `createFromImport(...)` — never remove existing `create()`
- `getter` names must match field name: `decisionNotes` → `getDecisionNotes()`, NOT `getNotes()`

### Cross-Story Interface Rule

Full example: [`docs/dev-guide/STANDARDS.md`](docs/dev-guide/STANDARDS.md)

- Define interfaces in **domain**, implement in **infrastructure**, inject domain interface in application services
- Enforced by ArchUnit: `application` layer MUST NOT import from `infrastructure`

### Database Migrations (IMP-086 — MANDATORY)

Migration format for this project: **drizzle (project's configured migration tool)**.

Before writing any migration reference in a story or implementation, the spec agent MUST have called:

```bash
python3 Nous/System/nous_trace.py migration next --count N --project <pid>
```

and used ONLY the version tokens it returned. The Nous graph tracks allocated versions across every merged story — hand-picking causes collisions. If you're implementing a story and the version in the spec looks suspect, re-check `nous_trace.py migration list --project <pid>` before writing the migration file.

**IMP-100 contract — your version must be a valid successor to all earlier sprints' versions.**
The widened allocator considers three sources: nous.db registered versions, on-disk migration files in the dev package, and `.nous-feedback.jsonl` events that mention a version. Per-tool semantics handled by a `MigrationAdapter` (Flyway: linear int; Alembic: DAG via `down_revision`; future tools plug in via adapter). The drift gate `nous_package.py drift --strict` includes a `[Migration Monotonicity]` section that fails if any later sprint reserves a version that's not a successor to an earlier sprint's. Run `./infra/scripts/sprint-status.sh` before authoring to verify the floor.

**Foreign-key references must point at tables in the canonical schema.** Ready-check `91_migration_references` validates every `REFERENCES <table>(<col>)` (or `op.create_foreign_key(referent_table=...)` for Alembic) against the set of tables actually declared in prior migrations. The check suggests the closest match on a typo: `REFERENCES tenants(id)` → `Closest match: tenant`. Don't deviate at implementation time — fix the spec.

**IMP-101 contract — seed data must agree with the auth provider's identity config.** When you change auth contracts (DEC-138 type — `keycloak_id` ↔ `preferred_username`, etc.), the seed file (`packages/db/seed/V*__*_seed.sql`) MUST be updated in the same change. The pipeline's `[Seed Integrity]` drift section + ready-check `92_seed_integrity` cross-check the seed against your auth provider's export (Keycloak realm JSON, Auth0 user export, etc.) — every dev user defined in the auth config must have a matching `app_user` row, every claim used as a foreign key (e.g. `org_id`) must resolve to its target entity (`tenant`), and historical UUID-shaped identifier values are banned by DEC-138. Run `nous_package.py drift --strict` before pushing auth-contract or seed changes.

### Enum Columns (IMP-087 — MANDATORY)

This project uses **drizzle**. When introducing a new enum column, document the on-disk representation rule in Implementation Notes so CHECK constraints match the ORM's storage format exactly.


## Bounded Context → Package Mapping

| Context | Backend Package | Frontend Path |
|---------|----------------|---------------|
| Company & Governance | `com.example.app.company` | `src/app/(authenticated)/company` |
| Commercial Planning | `com.example.app.planning` | `src/app/(authenticated)/planning` |
| Sales Execution | `com.example.app.sales` | `src/app/(authenticated)/sales` |
| Forecasting | `com.example.app.forecast` | `src/app/(authenticated)/forecast` |
| AI & Intelligence | `com.example.app.ai` | `src/app/(authenticated)/ai` |
| Learning & CMS | `com.example.app.learning` | `src/app/(authenticated)/learning` |
| Notifications | `com.example.app.notification` | `src/app/(authenticated)/notification` |
| Artifacts & Reporting | `com.example.app.artifact` | `src/app/(authenticated)/artifact` |
| Integration | `com.example.app.integration` | `src/app/(authenticated)/integration` |
| Identity & Access | `com.example.app.identity` | `src/app/(authenticated)/identity` |
| Billing & Subscriptions | `com.example.app.billing` | `src/app/(authenticated)/billing` |
| (Future) Marketing | `com.example.app.marketing` | `src/app/(authenticated)/marketing` |

## Key Decisions

| ID | Decision | Impact |
|----|----------|--------|

See `docs/decisions/` for full decision history.

## Design System

- **Primary:** #007AFF (Primary)
- **Accent:** #FF3B30 (Accent)
- **Font:** Inter (sans), JetBrains Mono (code)
- **Tokens:** `packages/design-system/tokens.json`
- **tailwindcss preset:** `packages/design-system/tailwind-preset.js`

## Testing Strategy

**Every story includes tests. Code without tests is not done.**

Minimum per story (effectiveness, not coverage — see `TESTING.md` §1/§3):
- Backend: given/when/then over events for aggregates + integration tests (real DB via Testcontainers, never a mock of our own code) for `@Repository`/`@WebMvcTest`/`@SpringBootTest`; property-based for money/derived-state math.
- Frontend: behavior/contract tests for components and hooks (assert real output, not "renders without throwing"); no mocking of our own route handlers.
- Security: at least one test per endpoint with an unauthorized role (expect 403); assert tenant isolation on every tenant-scoped path.
- ArchUnit runs on every build; no suppressions.
- E2E (Playwright) for full-stack stories in `apps/web/e2e/`.
- A new test must kill a previously-surviving mutant on a critical path; coverage is a diagnostic, never a target.

Full effectiveness rules, oracle guidance, tool matrix, and the gated critical-path set:
[`docs/dev-guide/TESTING.md`](docs/dev-guide/TESTING.md) + [`docs/TEST_EFFECTIVENESS_STANDARD.md`](docs/TEST_EFFECTIVENESS_STANDARD.md).

## Testing

**Before writing, modifying, or deleting any test, you MUST read `TESTING.md` in this
repo and follow it.** The org-wide rationale is in `docs/TEST_EFFECTIVENESS_STANDARD.md`.
These are hard constraints, not suggestions — a PR that violates them will be rejected.

Non-negotiable rules (summarized from `TESTING.md` §1):

- **Never use print/log as a test.** `console.log` / `System.out` / `print`, or a test that
  only checks "does not throw", is NOT an oracle. Every test asserts a property or contract.
- **Never mock code we own.** Mock ONLY true third-party network boundaries (payments,
  email/SMS/push, LLM providers). Use Testcontainers or in-memory real implementations for
  databases, our own services, the event store, and read models. Every third-party mock must
  be backed by a Pact contract test.
- **Test aggregates with given/when/then over events:** `GIVEN [past events] WHEN [command]
  THEN [emitted events | rejection]`. Do not mock the event store.
- **Use the strongest available oracle** (exact -> property-based -> metamorphic -> differential
  -> golden). Use property-based tests for all scoring/standings/money math. Do not default to
  exact-equality on large objects.
- **Do not write tests to raise coverage.** Coverage is a diagnostic, never a target. The only
  effectiveness target is the mutation score on critical paths. A new test must kill a mutant
  that was not previously killed; if it only adds coverage, it is redundant -- do not add it.
- **Keep tests deterministic:** inject the clock and RNG seed, no live network, no reliance on
  ordering or timing.
- **Assert tenant isolation** on every path touching tenant-scoped data.

Scope your test-writing to small, well-specified correctness bugs with clear reproduction and
expected behavior. Do not spray shallow or heavily-mocked tests to inflate volume -- test volume
is not a goal and is measured as a cost, not a quality.

When you change logic in a `TESTING.md` §3 critical path, update `TESTING.md` §3 in the same PR.

## Build Verification Gate

A story is NOT done until the full build passes — self-reported "tests pass" is not sufficient.

Before marking any story `done`:
- `./gradlew build` passes (unit + integration + ArchUnit). Tests meet the effectiveness bar in [`docs/dev-guide/TESTING.md`](docs/dev-guide/TESTING.md) §4 — coverage is a diagnostic, never a completion target (TE-1 / R1).
- `pnpm type-check && pnpm lint && pnpm test` passes.
- `./gradlew flywayMigrate` succeeds on a clean DB; no duplicate versions.
- Report evidence: `{"story":"US-XXX","event":"build_pass",...}` then `{"event":"done",...}`.

Full gate (commands, rejection criteria, troubleshooting):
[`docs/dev-guide/DEFINITION_OF_DONE.md`](docs/dev-guide/DEFINITION_OF_DONE.md).

## API Contract Reconciliation (MANDATORY)

The file `docs/api-contract-registry.json` lists **every API endpoint** the frontend
expects, extracted from TOON screen `dataSource` fields and story specs.

### Before implementing a backend controller:
1. **Check the registry** — search `docs/api-contract-registry.json` for your endpoint path
2. **Match the path exactly** — if the TOON says `GET /api/v1/accounts`, your
   `@GetMapping` must be on a controller with `@RequestMapping("/api/v1/accounts")`.
   Do NOT invent a different path.
3. **Match the HTTP method** — if the spec says GET, implement GET. Not POST.

### Before implementing a frontend screen:
1. **Read the TOON JSON** `dataSource` for each section
2. **Use the shared client** — `apiGet("/api/v1/accounts")` not `fetch(...)`
3. **Match the URL exactly** — copy-paste from the TOON JSON, don't improvise

### After completing a story with API endpoints:
Run: `python3 docs/scripts/api-reconcile-check.sh`

### If spec and implementation MUST diverge:
Log it explicitly — do NOT silently change paths:
```jsonl
{"story":"US-XXX","event":"deviation","notes":"Changed /api/v1/forecast/submissions to /api/v1/forecast/submission (singular) — backend naming convention"}
```

## Mandatory Implementation Standards (IMP-074..079)

Story AC checklists MUST confirm each of these. Full examples + rationale in
[`docs/dev-guide/STANDARDS.md`](docs/dev-guide/STANDARDS.md).

- **IMP-075/077 Tenant extraction** — Every controller calls `JwtUtils.extractTenantId(jwt)` directly. No private wrappers. No zero-UUID fallbacks (= security hole). Services accept `tenantId` as a param; never inject `Jwt` into services.
- **IMP-076 Exception handling** — Duplicate/constraint → `ConflictException(code, message)` (409). Business rule → `BusinessRuleException(code, message)` (422). `IllegalArgumentException` only in domain value-object guards (400). Never `@ResponseStatus` on service exceptions.
- **IMP-074 M:N endpoints** — For every Many-to-Many relationship implement all 4 sides: `GET /a/:id/b`, `POST /a/:id/b`, `DELETE /a/:id/b/:bid`, `GET /b/:id/a` (if navigable). All registered in `docs/api-contract-registry.json`; verified by `docs/scripts/api-reconcile-check.sh`.
- **IMP-078 Phone field** — `type="tel"` on every phone/mobile/contactPhone input. Read-only displays → `<a href="tel:{phone}">`.
- **IMP-079 Currency & formatting** — Money displays via `useCurrency().format(value)` only. Never raw numbers, never inline `Intl.NumberFormat`, never local `formatCurrency`. Money inputs: `type="number" step="0.01"`. Email inputs: `type="email"` (not text+regex).
- **Actor UUID (DEC-138)** — `JwtUtils.resolveKeycloakId(jwt)` → `UserRepository.findByKeycloakId()` → `user.getId()`. Never `jwt.getSubject()` or `extractSubjectAsUuid` (returns Keycloak realm UUID, not DB user UUID).

## Nous Feedback & Story Lifecycle

Append events to `.nous-feedback.jsonl` at the repo root as you work. This is how
Nous tracks progress across agents and sessions.

Core events you'll emit: `started`, `ac_pass`, `ac_verify`, `build_pass`, `done`,
`blocked`, `deviation`, `decision`, `feedback` (visual/UX issue with screenshot).

Example:
```jsonl
{"story":"US-064","event":"started","agent":"<your-agent>"}
{"story":"US-064","event":"ac_pass","ac":1,"notes":"..."}
{"story":"US-064","event":"done","coverage":"84%","agent":"<your-agent>"}
```

**Never mark `done` without adversarial AC verification** — try to BREAK each AC (grep for
competing paths, test with wrong role, check empty/null/error states, verify API contract matches).

### How status propagation actually works (round-trip — important)

Your `done` event lands in `.nous-feedback.jsonl` immediately, BUT the
following files do not auto-update:
- `docs/stories/SPRINT_PLAN.md` — regenerated by Nous from nous.db / Neon
- `docs/decisions/DECISIONS.md`, `CHANGES.md` — same: regenerated from nous.db

The propagation chain is:
```
.nous-feedback.jsonl (you write)
  → Nous-side `nous_package.py sync` runs
  → auto-pulls feedback into Neon (story_status: backlog → dev_done)
  → regenerates SPRINT_PLAN.md / CHANGES.md / etc.
  → pushes refreshed files back to this repo
```

The `sync` step is owned by the operator or CI — NOT by you. Until it runs,
`SPRINT_PLAN.md` will keep showing your completed story as backlog (⬜).

**This is normal. DO NOT re-implement a story just because SPRINT_PLAN.md
shows it as backlog.** First check `.nous-feedback.jsonl` for prior `done`
events. If found, the work is done; only the rendered file is stale.

**To verify status before picking a story:**
```bash
./infra/scripts/sprint-status.sh
```
This shows pending events (yours + other agents') that haven't yet propagated.
If you see your story listed under "Stale agent events", it's already done —
pick something else.

**To force a propagation refresh (when you have access):**
```bash
./infra/scripts/sync-from-nous.sh
```
Auto-pulls your events to Neon, then re-pushes refreshed `SPRINT_PLAN.md` etc.
Safe to run any time; pure read-mostly except for the nous.db status updates
your events imply.

Full event schema + AC verification protocol: [`docs/dev-guide/FEEDBACK.md`](docs/dev-guide/FEEDBACK.md).
Build verification gate + story rejection criteria: [`docs/dev-guide/DEFINITION_OF_DONE.md`](docs/dev-guide/DEFINITION_OF_DONE.md).

## Skills Required

- **Backend:** typescript , nextjs, JPA/Hibernate, Flyway, keycloak OIDC
- **Frontend:** TypeScript, react , nextjs  App Router, tailwindcss v4, Zustand
- **Infrastructure:** Docker, postgres , Redis, keycloak admin
- **AI/ML:** pgvector, RAG pattern, Claude API
- **Testing:** JUnit 5, Testcontainers, Playwright, ArchUnit
