-- HR-25 timestamp-slug migration (generated by Nous, IMP-250).
-- Drizzle migrations are NOT Flyway-numeric.

-- Enum types (parity with schema.ts pgEnum — IMP-254)
CREATE TYPE alert_rule_channel_enum AS ENUM ('email', 'slack', 'teams');
CREATE TYPE alert_rule_scope_kind_enum AS ENUM ('global', 'company', 'vendor_account');
CREATE TYPE alert_rule_type_enum AS ENUM ('approval_aging', 'provisioning_failure', 'blocked_no_seat', 'low_pool', 'invite_unaccepted', 'sync_stale', 'credential_failure', 'register_drift');
CREATE TYPE close_run_status_enum AS ENUM ('running', 'succeeded', 'failed');
CREATE TYPE company_role_assignment_role_enum AS ENUM ('approver', 'finance', 'viewer');
CREATE TYPE company_statement_language_enum AS ENUM ('es', 'en');
CREATE TYPE company_status_enum AS ENUM ('active', 'inactive');
CREATE TYPE company_type_enum AS ENUM ('internal', 'external');
CREATE TYPE integration_credential_health_enum AS ENUM ('ok', 'auth_failed', 'unverified');
CREATE TYPE integration_credential_kind_enum AS ENUM ('admin_scoped', 'analytics', 'graph_app', 'scim_bearer');
CREATE TYPE integration_credential_status_enum AS ENUM ('active', 'retired');
CREATE TYPE license_assignment_end_reason_enum AS ENUM ('left_company', 'inactive', 'reallocated');
CREATE TYPE license_assignment_source_kind_enum AS ENUM ('request', 'import', 'reconciliation');
CREATE TYPE license_request_state_enum AS ENUM ('submitted', 'pending_approval', 'approved', 'blocked_no_seat', 'provisioning', 'failed', 'invited', 'active', 'flagged_inactive', 'offboarding', 'deprovisioned', 'rejected');
CREATE TYPE license_type_status_enum AS ENUM ('active', 'inactive');
CREATE TYPE license_type_unit_enum AS ENUM ('seat', 'license');
CREATE TYPE person_status_enum AS ENUM ('active', 'departed');
CREATE TYPE provisioning_action_kind_enum AS ENUM ('invite', 'remove', 'assign_sku', 'withdraw_invite', 'checklist');
CREATE TYPE provisioning_action_mode_enum AS ENUM ('automated', 'orchestration');
CREATE TYPE provisioning_action_status_enum AS ENUM ('pending', 'sent', 'confirmed', 'failed', 'verification_failed', 'withdrawn');
CREATE TYPE reclamation_proposal_status_enum AS ENUM ('pending', 'approved', 'dismissed');
CREATE TYPE reconciliation_status_enum AS ENUM ('open', 'reconciled', 'overridden');
CREATE TYPE reconciliation_variance_line_cause_enum AS ENUM ('mid_cycle_proration', 'invite_consumed', 'timing', 'rate_mismatch', 'other');
CREATE TYPE statement_line_kind_enum AS ENUM ('license', 'usage', 'adjustment');
CREATE TYPE statement_status_enum AS ENUM ('draft', 'final', 'reconciled');
CREATE TYPE user_account_global_role_enum AS ENUM ('group_admin', 'central_finance');
CREATE TYPE user_account_status_enum AS ENUM ('active', 'disabled');
CREATE TYPE user_account_ui_language_enum AS ENUM ('es', 'en');
CREATE TYPE vendor_account_mode_enum AS ENUM ('automated', 'orchestration');
CREATE TYPE vendor_account_status_enum AS ENUM ('active', 'inactive');
CREATE TYPE vendor_connector_type_enum AS ENUM ('api', 'orchestration', 'manual');
CREATE TYPE vendor_identity_matching_enum AS ENUM ('email', 'upn', 'vendor_user_id');
CREATE TYPE vendor_provisioning_protocol_enum AS ENUM ('rest', 'scim', 'none');
CREATE TYPE vendor_status_enum AS ENUM ('active', 'inactive');
CREATE TABLE IF NOT EXISTS alert_rule (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  type                   alert_rule_type_enum NOT NULL,
  scope_kind             alert_rule_scope_kind_enum NOT NULL,
  company_id             UUID,
  vendor_account_id      UUID,
  threshold              JSONB,
  channel                alert_rule_channel_enum NOT NULL,
  enabled                BOOLEAN NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alert_rule_company_id ON alert_rule(company_id);
CREATE INDEX IF NOT EXISTS idx_alert_rule_vendor_account_id ON alert_rule(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_alert_rule_created_by ON alert_rule(created_by);

CREATE TABLE IF NOT EXISTS alert_event (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  alert_rule_id          UUID NOT NULL,
  fired_at               TIMESTAMPTZ NOT NULL,
  subject_ref            JSONB,
  notified               JSONB NOT NULL,
  acknowledged_by        UUID,
  acknowledged_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alert_event_alert_rule_id ON alert_event(alert_rule_id);
CREATE INDEX IF NOT EXISTS idx_alert_event_acknowledged_by ON alert_event(acknowledged_by);

CREATE TABLE IF NOT EXISTS system_setting (
  key                    TEXT PRIMARY KEY NOT NULL,
  value                  JSONB NOT NULL,
  updated_at             TIMESTAMPTZ NOT NULL,
  updated_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_system_setting_updated_by ON system_setting(updated_by);

CREATE TABLE IF NOT EXISTS audit_log (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  actor_user_id          UUID,
  action                 TEXT NOT NULL,
  entity_type            TEXT NOT NULL,
  entity_id              UUID NOT NULL,
  company_id             UUID,
  note                   TEXT,
  before                 JSONB,
  after                  JSONB,
  occurred_at            TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor_user_id ON audit_log(actor_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_company_id ON audit_log(company_id);

CREATE TABLE IF NOT EXISTS rate_card (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_account_id      UUID NOT NULL,
  license_type_id        UUID NOT NULL,
  monthly_rate_usd       NUMERIC(10, 2) NOT NULL,
  effective_from         DATE NOT NULL,
  effective_to           DATE,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  CONSTRAINT uq_rate_card_vendor_account_id_license_type_id_effective_from UNIQUE (vendor_account_id, license_type_id, effective_from)
);
CREATE INDEX IF NOT EXISTS idx_rate_card_vendor_account_id ON rate_card(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_rate_card_license_type_id ON rate_card(license_type_id);
CREATE INDEX IF NOT EXISTS idx_rate_card_created_by ON rate_card(created_by);

CREATE TABLE IF NOT EXISTS statement (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  company_id             UUID NOT NULL,
  period                 TEXT NOT NULL,
  status                 statement_status_enum NOT NULL,
  opening_seats          INTEGER NOT NULL,
  total_usd              NUMERIC(12, 2) NOT NULL,
  generated_at           TIMESTAMPTZ NOT NULL,
  close_run_id           UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_statement_company_id_period UNIQUE (company_id, period)
);
CREATE INDEX IF NOT EXISTS idx_statement_company_id ON statement(company_id);
CREATE INDEX IF NOT EXISTS idx_statement_close_run_id ON statement(close_run_id);

CREATE TABLE IF NOT EXISTS statement_line (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  statement_id           UUID NOT NULL,
  kind                   statement_line_kind_enum NOT NULL,
  person_id              UUID,
  vendor_account_id      UUID NOT NULL,
  license_type_id        UUID,
  assignment_id          UUID,
  license_days           INTEGER,
  rate_usd               NUMERIC(10, 2),
  amount_usd             NUMERIC(12, 2) NOT NULL,
  period_from            DATE,
  period_to              DATE,
  note                   TEXT
);
CREATE INDEX IF NOT EXISTS idx_statement_line_statement_id ON statement_line(statement_id);
CREATE INDEX IF NOT EXISTS idx_statement_line_person_id ON statement_line(person_id);
CREATE INDEX IF NOT EXISTS idx_statement_line_vendor_account_id ON statement_line(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_statement_line_license_type_id ON statement_line(license_type_id);
CREATE INDEX IF NOT EXISTS idx_statement_line_assignment_id ON statement_line(assignment_id);

CREATE TABLE IF NOT EXISTS close_run (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  period                 TEXT NOT NULL,
  status                 close_run_status_enum NOT NULL,
  started_at             TIMESTAMPTZ NOT NULL,
  finished_at            TIMESTAMPTZ,
  triggered_by           UUID,
  note                   TEXT,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_close_run_triggered_by ON close_run(triggered_by);

CREATE TABLE IF NOT EXISTS reconciliation (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  period                 TEXT NOT NULL,
  vendor_account_id      UUID NOT NULL,
  invoice_amount_usd     NUMERIC(12, 2),
  rollup_amount_usd      NUMERIC(12, 2) NOT NULL,
  variance_usd           NUMERIC(12, 2),
  status                 reconciliation_status_enum NOT NULL,
  override_note          TEXT,
  overridden_by          UUID,
  notes                  TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  updated_at             TIMESTAMPTZ,
  CONSTRAINT uq_reconciliation_vendor_account_id_period UNIQUE (vendor_account_id, period)
);
CREATE INDEX IF NOT EXISTS idx_reconciliation_vendor_account_id ON reconciliation(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_overridden_by ON reconciliation(overridden_by);

CREATE TABLE IF NOT EXISTS reconciliation_variance_line (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  reconciliation_id      UUID NOT NULL,
  cause                  reconciliation_variance_line_cause_enum NOT NULL,
  detail                 TEXT NOT NULL,
  register_amount_usd    NUMERIC(12, 2),
  invoice_amount_usd     NUMERIC(12, 2),
  difference_usd         NUMERIC(12, 2) NOT NULL,
  statement_line_id      UUID,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reconciliation_variance_line_reconciliation_id ON reconciliation_variance_line(reconciliation_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_variance_line_statement_line_id ON reconciliation_variance_line(statement_line_id);
CREATE INDEX IF NOT EXISTS idx_reconciliation_variance_line_created_by ON reconciliation_variance_line(created_by);

CREATE TABLE IF NOT EXISTS company (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  name                   TEXT NOT NULL,
  code                   TEXT NOT NULL,
  type                   company_type_enum NOT NULL,
  status                 company_status_enum NOT NULL,
  budget_monthly_usd     NUMERIC(10, 2),
  finance_contact_email  TEXT,
  statement_language     company_statement_language_enum,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  updated_at             TIMESTAMPTZ,
  updated_by             UUID,
  CONSTRAINT uq_company_code UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS idx_company_created_by ON company(created_by);
CREATE INDEX IF NOT EXISTS idx_company_updated_by ON company(updated_by);

CREATE TABLE IF NOT EXISTS person (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  email                  TEXT NOT NULL,
  full_name              TEXT NOT NULL,
  company_id             UUID NOT NULL,
  status                 person_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  updated_at             TIMESTAMPTZ,
  updated_by             UUID,
  CONSTRAINT uq_person_email UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS idx_person_company_id ON person(company_id);
CREATE INDEX IF NOT EXISTS idx_person_created_by ON person(created_by);
CREATE INDEX IF NOT EXISTS idx_person_updated_by ON person(updated_by);

CREATE TABLE IF NOT EXISTS user_account (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  email                  TEXT NOT NULL,
  idp_subject            TEXT,
  password_hash          TEXT,
  totp_secret_encrypted  TEXT,
  global_role            user_account_global_role_enum,
  person_id              UUID,
  ui_language            user_account_ui_language_enum,
  status                 user_account_status_enum NOT NULL,
  last_login_at          TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID,
  CONSTRAINT uq_user_account_email UNIQUE (email),
  CONSTRAINT uq_user_account_idp_subject UNIQUE (idp_subject),
  CONSTRAINT uq_user_account_person_id UNIQUE (person_id)
);
CREATE INDEX IF NOT EXISTS idx_user_account_person_id ON user_account(person_id);
CREATE INDEX IF NOT EXISTS idx_user_account_created_by ON user_account(created_by);

CREATE TABLE IF NOT EXISTS company_role_assignment (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  user_account_id        UUID NOT NULL,
  company_id             UUID NOT NULL,
  role                   company_role_assignment_role_enum NOT NULL,
  valid_from             DATE,
  valid_to               DATE,
  unique_grant           TEXT NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  CONSTRAINT uq_company_role_assignment_user_account_id_company_id_role UNIQUE (user_account_id, company_id, role)
);
CREATE INDEX IF NOT EXISTS idx_company_role_assignment_user_account_id ON company_role_assignment(user_account_id);
CREATE INDEX IF NOT EXISTS idx_company_role_assignment_company_id ON company_role_assignment(company_id);
CREATE INDEX IF NOT EXISTS idx_company_role_assignment_created_by ON company_role_assignment(created_by);

CREATE TABLE IF NOT EXISTS license_assignment (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  person_id              UUID NOT NULL,
  company_id             UUID NOT NULL,
  vendor_account_id      UUID NOT NULL,
  license_type_id        UUID NOT NULL,
  started_on             DATE NOT NULL,
  ended_on               DATE,
  end_reason             license_assignment_end_reason_enum,
  source_request_id      UUID,
  source_kind            license_assignment_source_kind_enum NOT NULL,
  note                   TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID,
  CONSTRAINT uq_license_assignment_source_request_id UNIQUE (source_request_id)
);
CREATE INDEX IF NOT EXISTS idx_license_assignment_person_id ON license_assignment(person_id);
CREATE INDEX IF NOT EXISTS idx_license_assignment_company_id ON license_assignment(company_id);
CREATE INDEX IF NOT EXISTS idx_license_assignment_vendor_account_id ON license_assignment(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_license_assignment_license_type_id ON license_assignment(license_type_id);
CREATE INDEX IF NOT EXISTS idx_license_assignment_source_request_id ON license_assignment(source_request_id);
CREATE INDEX IF NOT EXISTS idx_license_assignment_created_by ON license_assignment(created_by);

CREATE TABLE IF NOT EXISTS provisioning_action (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  request_id             UUID NOT NULL,
  vendor_account_id      UUID NOT NULL,
  kind                   provisioning_action_kind_enum NOT NULL,
  mode                   provisioning_action_mode_enum NOT NULL,
  vendor_ref             TEXT,
  status                 provisioning_action_status_enum NOT NULL,
  failure_reason         TEXT,
  raw_request            JSONB,
  raw_response           JSONB,
  sent_at                TIMESTAMPTZ,
  resolved_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_provisioning_action_request_id ON provisioning_action(request_id);
CREATE INDEX IF NOT EXISTS idx_provisioning_action_vendor_account_id ON provisioning_action(vendor_account_id);

CREATE TABLE IF NOT EXISTS reclamation_proposal (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  assignment_id          UUID NOT NULL,
  proposed_by            UUID,
  proposal_note          TEXT,
  status                 reclamation_proposal_status_enum NOT NULL,
  decided_by             UUID,
  decided_at             TIMESTAMPTZ,
  decision_note          TEXT,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reclamation_proposal_assignment_id ON reclamation_proposal(assignment_id);
CREATE INDEX IF NOT EXISTS idx_reclamation_proposal_proposed_by ON reclamation_proposal(proposed_by);
CREATE INDEX IF NOT EXISTS idx_reclamation_proposal_decided_by ON reclamation_proposal(decided_by);

CREATE TABLE IF NOT EXISTS license_request (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  request_no             TEXT NOT NULL,
  person_id              UUID NOT NULL,
  company_id             UUID NOT NULL,
  vendor_account_id      UUID NOT NULL,
  license_type_id        UUID NOT NULL,
  state                  license_request_state_enum NOT NULL,
  justification          TEXT NOT NULL,
  needed_by              DATE,
  requested_by           UUID,
  decided_by             UUID,
  decided_at             TIMESTAMPTZ,
  decision_comment       TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID,
  updated_at             TIMESTAMPTZ,
  license_assignment_id  UUID,
  CONSTRAINT uq_license_request_request_no UNIQUE (request_no)
);
CREATE INDEX IF NOT EXISTS idx_license_request_license_assignment_id ON license_request(license_assignment_id);
CREATE INDEX IF NOT EXISTS idx_license_request_person_id ON license_request(person_id);
CREATE INDEX IF NOT EXISTS idx_license_request_company_id ON license_request(company_id);
CREATE INDEX IF NOT EXISTS idx_license_request_vendor_account_id ON license_request(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_license_request_license_type_id ON license_request(license_type_id);
CREATE INDEX IF NOT EXISTS idx_license_request_requested_by ON license_request(requested_by);
CREATE INDEX IF NOT EXISTS idx_license_request_decided_by ON license_request(decided_by);
CREATE INDEX IF NOT EXISTS idx_license_request_created_by ON license_request(created_by);

CREATE TABLE IF NOT EXISTS request_transition (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  request_id             UUID NOT NULL,
  from_state             TEXT,
  to_state               TEXT NOT NULL,
  actor_user_id          UUID,
  note                   TEXT,
  occurred_at            TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_request_transition_request_id ON request_transition(request_id);
CREATE INDEX IF NOT EXISTS idx_request_transition_actor_user_id ON request_transition(actor_user_id);

CREATE TABLE IF NOT EXISTS activity_record (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_account_id      UUID NOT NULL,
  person_id              UUID NOT NULL,
  activity_date          DATE NOT NULL,
  counters               JSONB NOT NULL,
  raw_payload            JSONB,
  synced_at              TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_activity_record_vendor_account_id_person_id_activity_date UNIQUE (vendor_account_id, person_id, activity_date)
);
CREATE INDEX IF NOT EXISTS idx_activity_record_vendor_account_id ON activity_record(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_activity_record_person_id ON activity_record(person_id);

CREATE TABLE IF NOT EXISTS cost_record (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_account_id      UUID NOT NULL,
  person_id              UUID NOT NULL,
  cost_date              DATE NOT NULL,
  amount_usd             NUMERIC(12, 4) NOT NULL,
  raw_payload            JSONB,
  synced_at              TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_cost_record_vendor_account_id_person_id_cost_date UNIQUE (vendor_account_id, person_id, cost_date)
);
CREATE INDEX IF NOT EXISTS idx_cost_record_vendor_account_id ON cost_record(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_cost_record_person_id ON cost_record(person_id);

CREATE TABLE IF NOT EXISTS vendor (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  name                   TEXT NOT NULL,
  category               TEXT,
  connector_type         vendor_connector_type_enum NOT NULL,
  provisioning_protocol  vendor_provisioning_protocol_enum NOT NULL,
  can_provision          BOOLEAN NOT NULL,
  can_deprovision        BOOLEAN NOT NULL,
  has_usage_data         BOOLEAN NOT NULL,
  has_cost_data          BOOLEAN NOT NULL,
  identity_matching      vendor_identity_matching_enum NOT NULL,
  status                 vendor_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  CONSTRAINT uq_vendor_name UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS idx_vendor_created_by ON vendor(created_by);

CREATE TABLE IF NOT EXISTS vendor_account (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_id              UUID NOT NULL,
  name                   TEXT NOT NULL,
  mode                   vendor_account_mode_enum NOT NULL,
  vendor_org_ref         TEXT,
  contract_renewal_on    DATE,
  low_pool_floor         INTEGER NOT NULL,
  status                 vendor_account_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  updated_at             TIMESTAMPTZ,
  updated_by             UUID,
  CONSTRAINT uq_vendor_account_vendor_id_name UNIQUE (vendor_id, name)
);
CREATE INDEX IF NOT EXISTS idx_vendor_account_vendor_id ON vendor_account(vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_account_created_by ON vendor_account(created_by);
CREATE INDEX IF NOT EXISTS idx_vendor_account_updated_by ON vendor_account(updated_by);

CREATE TABLE IF NOT EXISTS vendor_account_capacity (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_account_id      UUID NOT NULL,
  license_type_id        UUID NOT NULL,
  purchased_qty          INTEGER NOT NULL,
  effective_from         DATE NOT NULL,
  note                   TEXT,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  CONSTRAINT uq_vendor_account_capacity_vendor_account_id_license_type_id_effective_from UNIQUE (vendor_account_id, license_type_id, effective_from)
);
CREATE INDEX IF NOT EXISTS idx_vendor_account_capacity_vendor_account_id ON vendor_account_capacity(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_vendor_account_capacity_license_type_id ON vendor_account_capacity(license_type_id);
CREATE INDEX IF NOT EXISTS idx_vendor_account_capacity_created_by ON vendor_account_capacity(created_by);

CREATE TABLE IF NOT EXISTS license_type (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_id              UUID NOT NULL,
  name                   TEXT NOT NULL,
  unit                   license_type_unit_enum NOT NULL,
  status                 license_type_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL,
  CONSTRAINT uq_license_type_vendor_id_name UNIQUE (vendor_id, name)
);
CREATE INDEX IF NOT EXISTS idx_license_type_vendor_id ON license_type(vendor_id);
CREATE INDEX IF NOT EXISTS idx_license_type_created_by ON license_type(created_by);

CREATE TABLE IF NOT EXISTS integration_credential (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  vendor_account_id      UUID NOT NULL,
  kind                   integration_credential_kind_enum NOT NULL,
  encrypted_secret       TEXT NOT NULL,
  scopes                 TEXT,
  last4                  TEXT,
  last_verified_at       TIMESTAMPTZ,
  health                 integration_credential_health_enum NOT NULL,
  status                 integration_credential_status_enum NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL,
  created_by             UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_integration_credential_vendor_account_id ON integration_credential(vendor_account_id);
CREATE INDEX IF NOT EXISTS idx_integration_credential_created_by ON integration_credential(created_by);

-- Foreign keys (deferred ALTER pass — added after all tables exist,
-- so forward-references, cycles, and self-refs all apply cleanly)
ALTER TABLE alert_rule ADD CONSTRAINT fk_alert_rule_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE alert_rule ADD CONSTRAINT fk_alert_rule_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE alert_rule ADD CONSTRAINT fk_alert_rule_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE alert_event ADD CONSTRAINT fk_alert_event_alert_rule_id FOREIGN KEY (alert_rule_id) REFERENCES alert_rule(id);
ALTER TABLE alert_event ADD CONSTRAINT fk_alert_event_acknowledged_by FOREIGN KEY (acknowledged_by) REFERENCES user_account(id);
ALTER TABLE system_setting ADD CONSTRAINT fk_system_setting_updated_by FOREIGN KEY (updated_by) REFERENCES user_account(id);
ALTER TABLE audit_log ADD CONSTRAINT fk_audit_log_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES user_account(id);
ALTER TABLE audit_log ADD CONSTRAINT fk_audit_log_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE rate_card ADD CONSTRAINT fk_rate_card_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE rate_card ADD CONSTRAINT fk_rate_card_license_type_id FOREIGN KEY (license_type_id) REFERENCES license_type(id);
ALTER TABLE rate_card ADD CONSTRAINT fk_rate_card_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE statement ADD CONSTRAINT fk_statement_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE statement ADD CONSTRAINT fk_statement_close_run_id FOREIGN KEY (close_run_id) REFERENCES close_run(id);
ALTER TABLE statement_line ADD CONSTRAINT fk_statement_line_statement_id FOREIGN KEY (statement_id) REFERENCES statement(id);
ALTER TABLE statement_line ADD CONSTRAINT fk_statement_line_person_id FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE statement_line ADD CONSTRAINT fk_statement_line_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE statement_line ADD CONSTRAINT fk_statement_line_license_type_id FOREIGN KEY (license_type_id) REFERENCES license_type(id);
ALTER TABLE statement_line ADD CONSTRAINT fk_statement_line_assignment_id FOREIGN KEY (assignment_id) REFERENCES license_assignment(id);
ALTER TABLE close_run ADD CONSTRAINT fk_close_run_triggered_by FOREIGN KEY (triggered_by) REFERENCES user_account(id);
ALTER TABLE reconciliation ADD CONSTRAINT fk_reconciliation_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE reconciliation ADD CONSTRAINT fk_reconciliation_overridden_by FOREIGN KEY (overridden_by) REFERENCES user_account(id);
ALTER TABLE reconciliation_variance_line ADD CONSTRAINT fk_reconciliation_variance_line_reconciliation_id FOREIGN KEY (reconciliation_id) REFERENCES reconciliation(id);
ALTER TABLE reconciliation_variance_line ADD CONSTRAINT fk_reconciliation_variance_line_statement_line_id FOREIGN KEY (statement_line_id) REFERENCES statement_line(id);
ALTER TABLE reconciliation_variance_line ADD CONSTRAINT fk_reconciliation_variance_line_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE company ADD CONSTRAINT fk_company_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE company ADD CONSTRAINT fk_company_updated_by FOREIGN KEY (updated_by) REFERENCES user_account(id);
ALTER TABLE person ADD CONSTRAINT fk_person_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE person ADD CONSTRAINT fk_person_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE person ADD CONSTRAINT fk_person_updated_by FOREIGN KEY (updated_by) REFERENCES user_account(id);
ALTER TABLE user_account ADD CONSTRAINT fk_user_account_person_id FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE user_account ADD CONSTRAINT fk_user_account_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE company_role_assignment ADD CONSTRAINT fk_company_role_assignment_user_account_id FOREIGN KEY (user_account_id) REFERENCES user_account(id);
ALTER TABLE company_role_assignment ADD CONSTRAINT fk_company_role_assignment_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE company_role_assignment ADD CONSTRAINT fk_company_role_assignment_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE license_assignment ADD CONSTRAINT fk_license_assignment_person_id FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE license_assignment ADD CONSTRAINT fk_license_assignment_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE license_assignment ADD CONSTRAINT fk_license_assignment_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE license_assignment ADD CONSTRAINT fk_license_assignment_license_type_id FOREIGN KEY (license_type_id) REFERENCES license_type(id);
ALTER TABLE license_assignment ADD CONSTRAINT fk_license_assignment_source_request_id FOREIGN KEY (source_request_id) REFERENCES license_request(id);
ALTER TABLE license_assignment ADD CONSTRAINT fk_license_assignment_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE provisioning_action ADD CONSTRAINT fk_provisioning_action_request_id FOREIGN KEY (request_id) REFERENCES license_request(id);
ALTER TABLE provisioning_action ADD CONSTRAINT fk_provisioning_action_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE reclamation_proposal ADD CONSTRAINT fk_reclamation_proposal_assignment_id FOREIGN KEY (assignment_id) REFERENCES license_assignment(id);
ALTER TABLE reclamation_proposal ADD CONSTRAINT fk_reclamation_proposal_proposed_by FOREIGN KEY (proposed_by) REFERENCES user_account(id);
ALTER TABLE reclamation_proposal ADD CONSTRAINT fk_reclamation_proposal_decided_by FOREIGN KEY (decided_by) REFERENCES user_account(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_license_assignment_id FOREIGN KEY (license_assignment_id) REFERENCES license_assignment(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_person_id FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_company_id FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_license_type_id FOREIGN KEY (license_type_id) REFERENCES license_type(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_requested_by FOREIGN KEY (requested_by) REFERENCES user_account(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_decided_by FOREIGN KEY (decided_by) REFERENCES user_account(id);
ALTER TABLE license_request ADD CONSTRAINT fk_license_request_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE request_transition ADD CONSTRAINT fk_request_transition_request_id FOREIGN KEY (request_id) REFERENCES license_request(id);
ALTER TABLE request_transition ADD CONSTRAINT fk_request_transition_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES user_account(id);
ALTER TABLE activity_record ADD CONSTRAINT fk_activity_record_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE activity_record ADD CONSTRAINT fk_activity_record_person_id FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE cost_record ADD CONSTRAINT fk_cost_record_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE cost_record ADD CONSTRAINT fk_cost_record_person_id FOREIGN KEY (person_id) REFERENCES person(id);
ALTER TABLE vendor ADD CONSTRAINT fk_vendor_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE vendor_account ADD CONSTRAINT fk_vendor_account_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendor(id);
ALTER TABLE vendor_account ADD CONSTRAINT fk_vendor_account_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE vendor_account ADD CONSTRAINT fk_vendor_account_updated_by FOREIGN KEY (updated_by) REFERENCES user_account(id);
ALTER TABLE vendor_account_capacity ADD CONSTRAINT fk_vendor_account_capacity_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE vendor_account_capacity ADD CONSTRAINT fk_vendor_account_capacity_license_type_id FOREIGN KEY (license_type_id) REFERENCES license_type(id);
ALTER TABLE vendor_account_capacity ADD CONSTRAINT fk_vendor_account_capacity_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE license_type ADD CONSTRAINT fk_license_type_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendor(id);
ALTER TABLE license_type ADD CONSTRAINT fk_license_type_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
ALTER TABLE integration_credential ADD CONSTRAINT fk_integration_credential_vendor_account_id FOREIGN KEY (vendor_account_id) REFERENCES vendor_account(id);
ALTER TABLE integration_credential ADD CONSTRAINT fk_integration_credential_created_by FOREIGN KEY (created_by) REFERENCES user_account(id);
-- Append-only triggers (append_only_entities)
CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on audit_log', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER audit_log_no_mutate
  BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();

CREATE OR REPLACE FUNCTION request_transition_append_only() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'append_only: % is forbidden on request_transition', TG_OP; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER request_transition_no_mutate
  BEFORE UPDATE OR DELETE ON request_transition
  FOR EACH ROW EXECUTE FUNCTION request_transition_append_only();
