// index.ts — Drizzle client (generated by Nous). Driver auto-selects by
// DATABASE_URL: node-postgres for a local/standard Postgres URL, neon-http
// for a Neon/Vercel endpoint. Override with DB_DRIVER=pg|neon.
import { drizzle as drizzlePg } from "drizzle-orm/node-postgres";
import { drizzle as drizzleNeon } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { Pool } from "pg";
import * as schema from "./schema";

export { SYSTEM_USER_EMAIL, SYSTEM_USER_ID } from "./system-ids";
export {
  deleteCompanyRoleAssignmentWithAudit,
  type DeleteCompanyRoleAssignmentInput,
  type DeletedCompanyRoleAssignment,
} from "./company-role-assignment-mutations";

const url = process.env.DATABASE_URL ?? "";
const driver = process.env.DB_DRIVER;
const useNeon =
  driver === "neon" || (driver !== "pg" && /neon|vercel/i.test(url));

export const db = useNeon
  ? drizzleNeon({ client: neon(url), schema })
  : drizzlePg({ client: url ? new Pool({ connectionString: url }) : new Pool(), schema });
