// schema.ts — Drizzle pgTable schema (generated by Nous, IMP-250).
// Tables + columns (types/enums/money/uniqueness) + FK/company_id derive
// from the project's 04_entity_catalog entity_attributes.
import { sql } from "drizzle-orm";
import { boolean, check, date, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";

export const alert_rule_channel_enum = pgEnum("alert_rule_channel_enum", ["email", "slack", "teams"]);
export const alert_rule_scope_kind_enum = pgEnum("alert_rule_scope_kind_enum", ["global", "company", "vendor_account"]);
export const alert_rule_type_enum = pgEnum("alert_rule_type_enum", ["approval_aging", "provisioning_failure", "blocked_no_seat", "low_pool", "invite_unaccepted", "sync_stale", "credential_failure", "register_drift", "deprovision_overdue", "close_missed"]);
export const alert_notification_delivery_phase_enum = pgEnum("alert_notification_delivery_phase_enum", ["pending", "claimed", "succeeded", "failed"]);
export const close_run_status_enum = pgEnum("close_run_status_enum", ["running", "succeeded", "failed"]);
export const company_role_assignment_role_enum = pgEnum("company_role_assignment_role_enum", ["approver", "finance", "viewer"]);
export const company_statement_language_enum = pgEnum("company_statement_language_enum", ["es", "en"]);
export const company_status_enum = pgEnum("company_status_enum", ["active", "inactive"]);
export const company_type_enum = pgEnum("company_type_enum", ["internal", "external"]);
export const integration_credential_health_enum = pgEnum("integration_credential_health_enum", ["ok", "auth_failed", "unverified"]);
export const integration_credential_kind_enum = pgEnum("integration_credential_kind_enum", ["admin_scoped", "analytics", "graph_app", "scim_bearer"]);
export const integration_credential_status_enum = pgEnum("integration_credential_status_enum", ["active", "retired"]);
export const license_assignment_end_reason_enum = pgEnum("license_assignment_end_reason_enum", ["left_company", "inactive", "reallocated"]);
export const license_assignment_source_kind_enum = pgEnum("license_assignment_source_kind_enum", ["request", "import", "reconciliation"]);
export const license_request_state_enum = pgEnum("license_request_state_enum", ["submitted", "pending_approval", "approved", "blocked_no_seat", "provisioning", "failed", "invited", "active", "flagged_inactive", "offboarding", "deprovisioned", "rejected"]);
export const lifecycle_notification_kind_enum = pgEnum("lifecycle_notification_kind_enum", ["submission", "new_request_to_approver", "decision", "provisioning_complete"]);
export const license_type_status_enum = pgEnum("license_type_status_enum", ["active", "inactive"]);
export const license_type_unit_enum = pgEnum("license_type_unit_enum", ["seat", "license"]);
export const person_status_enum = pgEnum("person_status_enum", ["active", "departed"]);
export const provisioning_action_kind_enum = pgEnum("provisioning_action_kind_enum", ["invite", "remove", "assign_sku", "withdraw_invite", "checklist"]);
export const provisioning_action_mode_enum = pgEnum("provisioning_action_mode_enum", ["automated", "orchestration"]);
export const provisioning_action_status_enum = pgEnum("provisioning_action_status_enum", ["pending", "sent", "confirmed", "failed", "verification_failed", "withdrawn"]);
export const reclamation_proposal_status_enum = pgEnum("reclamation_proposal_status_enum", ["pending", "approved", "dismissed"]);
export const reconciliation_status_enum = pgEnum("reconciliation_status_enum", ["open", "reconciled", "overridden"]);
export const reconciliation_variance_line_cause_enum = pgEnum("reconciliation_variance_line_cause_enum", ["mid_cycle_proration", "invite_consumed", "timing", "rate_mismatch", "other"]);
export const statement_line_kind_enum = pgEnum("statement_line_kind_enum", ["license", "usage", "adjustment"]);
export const statement_status_enum = pgEnum("statement_status_enum", ["draft", "final", "reconciled"]);
export const user_account_global_role_enum = pgEnum("user_account_global_role_enum", ["group_admin", "central_finance"]);
export const user_account_status_enum = pgEnum("user_account_status_enum", ["active", "disabled"]);
export const user_account_ui_language_enum = pgEnum("user_account_ui_language_enum", ["es", "en"]);
export const vendor_account_mode_enum = pgEnum("vendor_account_mode_enum", ["automated", "orchestration"]);
export const vendor_account_status_enum = pgEnum("vendor_account_status_enum", ["active", "inactive"]);
export const vendor_connector_type_enum = pgEnum("vendor_connector_type_enum", ["api", "orchestration", "manual"]);
export const vendor_identity_matching_enum = pgEnum("vendor_identity_matching_enum", ["email", "upn", "vendor_user_id"]);
export const vendor_provisioning_protocol_enum = pgEnum("vendor_provisioning_protocol_enum", ["rest", "scim", "none"]);
export const vendor_status_enum = pgEnum("vendor_status_enum", ["active", "inactive"]);

export const alertRule = pgTable("alert_rule", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  type: alert_rule_type_enum("type").notNull(),
  scopeKind: alert_rule_scope_kind_enum("scope_kind").notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id),
  threshold: jsonb("threshold"),
  channel: alert_rule_channel_enum("channel").notNull(),
  enabled: boolean("enabled").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
}, (table) => ({
  globalTypeUnique: uniqueIndex("uq_alert_rule_global_type")
    .on(table.type)
    .where(sql`${table.scopeKind} = 'global'`),
}));

export const alertEvent = pgTable("alert_event", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  alertRuleId: uuid("alert_rule_id").references((): AnyPgColumn => alertRule.id).notNull(),
  firedAt: timestamp("fired_at", { withTimezone: true }).notNull(),
  subjectRef: jsonb("subject_ref"),
  notified: jsonb("notified").notNull(),
  acknowledgedBy: uuid("acknowledged_by").references((): AnyPgColumn => userAccount.id),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  dedupeKey: text("dedupe_key"),
}, (table) => ({
  dedupeKeyUnique: uniqueIndex("uq_alert_event_dedupe_key")
    .on(table.dedupeKey)
    .where(sql`${table.dedupeKey} IS NOT NULL`),
}));

/**
 * Append-only notification outbox journal. AlertEvent is immutable except for
 * acknowledgement, so delivery progress is represented as new rows here.
 */
export const alertNotificationDelivery = pgTable("alert_notification_delivery", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  alertEventId: uuid("alert_event_id").references((): AnyPgColumn => alertEvent.id).notNull(),
  attempt: integer("attempt").notNull(),
  phase: alert_notification_delivery_phase_enum("phase").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
  workerId: text("worker_id"),
  providerMessageId: text("provider_message_id"),
  accepted: jsonb("accepted"),
  errorCode: text("error_code"),
  claimToken: uuid("claim_token"),
  recipientKey: text("recipient_key").default("default").notNull(),
  recipientUserAccountId: uuid("recipient_user_account_id").references((): AnyPgColumn => userAccount.id),
  recipientEmail: text("recipient_email"),
  recipientLocale: user_account_ui_language_enum("recipient_locale"),
}, (table) => ({
  alertEventIndex: index("idx_alert_notification_delivery_alert_event_id")
    .on(table.alertEventId),
  attemptPhaseUnique: uniqueIndex("uq_alert_notification_delivery_attempt_phase")
    .on(table.alertEventId, table.recipientKey, table.attempt, table.phase),
  succeededUnique: uniqueIndex("uq_alert_notification_delivery_succeeded")
    .on(table.alertEventId, table.recipientKey)
    .where(sql`${table.phase} = 'succeeded'`),
  claimFenceIndex: index("idx_alert_notification_delivery_claim_fence")
    .on(table.alertEventId, table.recipientKey, table.attempt, table.claimToken),
  claimFenceCheck: check(
    "ck_alert_notification_delivery_claim_fence",
    sql`(${table.phase} = 'pending' AND ${table.claimToken} IS NULL)
      OR (${table.phase} IN ('claimed', 'succeeded', 'failed')
          AND ${table.claimToken} IS NOT NULL)`,
  ),
  recipientCheck: check(
    "ck_alert_notification_delivery_recipient",
    sql`btrim(${table.recipientKey}) <> ''
      AND (${table.phase} <> 'pending'
        OR ${table.recipientEmail} IS NULL
        OR btrim(${table.recipientEmail}) <> '')`,
  ),
}));

export const lifecycleNotification = pgTable("lifecycle_notification", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  requestId: uuid("request_id").references((): AnyPgColumn => licenseRequest.id).notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id).notNull(),
  kind: lifecycle_notification_kind_enum("kind").notNull(),
  recipientUserAccountId: uuid("recipient_user_account_id").references((): AnyPgColumn => userAccount.id),
  recipientEmail: text("recipient_email").notNull(),
  recipientLocale: user_account_ui_language_enum("recipient_locale"),
  requestState: license_request_state_enum("request_state").notNull(),
  dedupeKey: text("dedupe_key").notNull().unique("lifecycle_notification_dedupe_key_key"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => ({
  requestIndex: index("idx_lifecycle_notification_request")
    .on(table.requestId, table.createdAt, table.id),
}));

export const lifecycleNotificationDelivery = pgTable("lifecycle_notification_delivery", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  notificationId: uuid("notification_id").references((): AnyPgColumn => lifecycleNotification.id).notNull(),
  attempt: integer("attempt").notNull(),
  phase: alert_notification_delivery_phase_enum("phase").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
  workerId: text("worker_id"),
  providerMessageId: text("provider_message_id"),
  accepted: jsonb("accepted"),
  errorCode: text("error_code"),
  claimToken: uuid("claim_token"),
}, (table) => ({
  attemptPhaseUnique: uniqueIndex("uq_lifecycle_notification_delivery_attempt_phase")
    .on(table.notificationId, table.attempt, table.phase),
  succeededUnique: uniqueIndex("uq_lifecycle_notification_delivery_succeeded")
    .on(table.notificationId)
    .where(sql`${table.phase} = 'succeeded'`),
  claimIndex: index("idx_lifecycle_notification_delivery_claim")
    .on(table.notificationId, table.attempt, table.claimToken),
}));

export const systemSetting = pgTable("system_setting", {
  key: text("key").primaryKey().notNull(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  updatedBy: uuid("updated_by").references((): AnyPgColumn => userAccount.id).notNull(),
});

export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().defaultRandom().notNull(),
    actorUserId: uuid("actor_user_id").references(
      (): AnyPgColumn => userAccount.id,
    ),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id").notNull(),
    companyId: uuid("company_id").references((): AnyPgColumn => company.id),
    note: text("note"),
    before: jsonb("before"),
    after: jsonb("after"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    crossOrgMoveClientRequestUnique: uniqueIndex(
      "uq_cross_org_move_client_request",
    )
      .on(table.entityId, sql`(${table.after}->>'clientRequestId')`)
      .where(
        sql`${table.entityType} = 'CrossOrgMove' AND ${table.after}->>'clientRequestId' IS NOT NULL`,
      ),
  }),
);

export const rateCard = pgTable("rate_card", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  licenseTypeId: uuid("license_type_id").references((): AnyPgColumn => licenseType.id).notNull(),
  monthlyRateUsd: numeric("monthly_rate_usd", { precision: 10, scale: 2 }).notNull(),
  effectiveFrom: date("effective_from").notNull(),
  effectiveTo: date("effective_to"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
});

export const statement = pgTable("statement", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id).notNull(),
  period: text("period").notNull(),
  status: statement_status_enum("status").notNull(),
  openingSeats: integer("opening_seats").notNull(),
  totalUsd: numeric("total_usd", { precision: 12, scale: 2 }).notNull(),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull(),
  closeRunId: uuid("close_run_id").references((): AnyPgColumn => closeRun.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const statementLine = pgTable("statement_line", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  statementId: uuid("statement_id").references((): AnyPgColumn => statement.id).notNull(),
  kind: statement_line_kind_enum("kind").notNull(),
  personId: uuid("person_id").references((): AnyPgColumn => person.id),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  licenseTypeId: uuid("license_type_id").references((): AnyPgColumn => licenseType.id),
  assignmentId: uuid("assignment_id").references((): AnyPgColumn => licenseAssignment.id),
  licenseDays: integer("license_days"),
  rateUsd: numeric("rate_usd", { precision: 10, scale: 2 }),
  amountUsd: numeric("amount_usd", { precision: 12, scale: 2 }).notNull(),
  periodFrom: date("period_from"),
  periodTo: date("period_to"),
  note: text("note"),
});

export const closeRun = pgTable("close_run", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  period: text("period").notNull(),
  status: close_run_status_enum("status").notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  triggeredBy: uuid("triggered_by").references((): AnyPgColumn => userAccount.id),
  note: text("note"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const reconciliation = pgTable("reconciliation", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  period: text("period").notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  invoiceAmountUsd: numeric("invoice_amount_usd", { precision: 12, scale: 2 }),
  rollupAmountUsd: numeric("rollup_amount_usd", { precision: 12, scale: 2 }).notNull(),
  varianceUsd: numeric("variance_usd", { precision: 12, scale: 2 }),
  status: reconciliation_status_enum("status").notNull(),
  overrideNote: text("override_note"),
  overriddenBy: uuid("overridden_by").references((): AnyPgColumn => userAccount.id),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
});

export const reconciliationVarianceLine = pgTable("reconciliation_variance_line", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  reconciliationId: uuid("reconciliation_id").references((): AnyPgColumn => reconciliation.id).notNull(),
  cause: reconciliation_variance_line_cause_enum("cause").notNull(),
  detail: text("detail").notNull(),
  registerAmountUsd: numeric("register_amount_usd", { precision: 12, scale: 2 }),
  invoiceAmountUsd: numeric("invoice_amount_usd", { precision: 12, scale: 2 }),
  differenceUsd: numeric("difference_usd", { precision: 12, scale: 2 }).notNull(),
  statementLineId: uuid("statement_line_id").references((): AnyPgColumn => statementLine.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
});

export const company = pgTable("company", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  name: text("name").notNull(),
  code: text("code").notNull(),
  type: company_type_enum("type").notNull(),
  status: company_status_enum("status").notNull(),
  budgetMonthlyUsd: numeric("budget_monthly_usd", { precision: 10, scale: 2 }),
  financeContactEmail: text("finance_contact_email"),
  statementLanguage: company_statement_language_enum("statement_language"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  updatedBy: uuid("updated_by").references((): AnyPgColumn => userAccount.id),
});

export const person = pgTable("person", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  email: text("email").notNull(),
  fullName: text("full_name").notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id).notNull(),
  status: person_status_enum("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  updatedBy: uuid("updated_by").references((): AnyPgColumn => userAccount.id),
}, (table) => ({
  lowerEmailUnique: uniqueIndex("uq_person_lower_email")
    .on(sql`lower(${table.email})`),
}));

export const userAccount = pgTable("user_account", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  email: text("email").notNull(),
  idpSubject: text("idp_subject"),
  passwordHash: text("password_hash"),
  totpSecretEncrypted: text("totp_secret_encrypted"),
  globalRole: user_account_global_role_enum("global_role"),
  personId: uuid("person_id").references((): AnyPgColumn => person.id),
  uiLanguage: user_account_ui_language_enum("ui_language"),
  status: user_account_status_enum("status").notNull(),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id),
});

export const companyRoleAssignment = pgTable("company_role_assignment", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  userAccountId: uuid("user_account_id").references((): AnyPgColumn => userAccount.id).notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id).notNull(),
  role: company_role_assignment_role_enum("role").notNull(),
  validFrom: date("valid_from"),
  validTo: date("valid_to"),
  uniqueGrant: text("unique_grant").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
});

export const licenseAssignment = pgTable("license_assignment", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  personId: uuid("person_id").references((): AnyPgColumn => person.id).notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id).notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  licenseTypeId: uuid("license_type_id").references((): AnyPgColumn => licenseType.id).notNull(),
  startedOn: date("started_on").notNull(),
  endedOn: date("ended_on"),
  endReason: license_assignment_end_reason_enum("end_reason"),
  sourceRequestId: uuid("source_request_id").references((): AnyPgColumn => licenseRequest.id),
  sourceKind: license_assignment_source_kind_enum("source_kind").notNull(),
  note: text("note"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id),
});

export const provisioningAction = pgTable("provisioning_action", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  requestId: uuid("request_id").references((): AnyPgColumn => licenseRequest.id).notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  kind: provisioning_action_kind_enum("kind").notNull(),
  mode: provisioning_action_mode_enum("mode").notNull(),
  vendorRef: text("vendor_ref"),
  status: provisioning_action_status_enum("status").notNull(),
  failureReason: text("failure_reason"),
  rawRequest: jsonb("raw_request"),
  rawResponse: jsonb("raw_response"),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => ({
  orchestrationChecklistOperationUnique: uniqueIndex(
    "uq_provisioning_action_orchestration_checklist_operation",
  )
    .on(table.requestId, sql`(${table.rawRequest} ->> 'operation')`)
    .where(
      sql`${table.kind} = 'checklist' AND ${table.mode} = 'orchestration'
          AND ${table.rawRequest} ->> 'operation' IN ('provision', 'deprovision')`,
    ),
  pendingRemoveRequestUnique: uniqueIndex(
    "uq_provisioning_action_pending_remove_request",
  )
    .on(table.requestId)
    .where(
      sql`${table.kind} = 'remove' AND ${table.status} = 'pending'`,
    ),
}));

export const reclamationProposal = pgTable("reclamation_proposal", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  assignmentId: uuid("assignment_id").references((): AnyPgColumn => licenseAssignment.id).notNull(),
  proposedBy: uuid("proposed_by").references((): AnyPgColumn => userAccount.id),
  proposalNote: text("proposal_note"),
  status: reclamation_proposal_status_enum("status").notNull(),
  decidedBy: uuid("decided_by").references((): AnyPgColumn => userAccount.id),
  decidedAt: timestamp("decided_at", { withTimezone: true }),
  decisionNote: text("decision_note"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const licenseRequest = pgTable("license_request", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  requestNo: text("request_no").notNull().unique("uq_license_request_request_no"),
  personId: uuid("person_id").references((): AnyPgColumn => person.id).notNull(),
  companyId: uuid("company_id").references((): AnyPgColumn => company.id).notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  licenseTypeId: uuid("license_type_id").references((): AnyPgColumn => licenseType.id).notNull(),
  state: license_request_state_enum("state").notNull(),
  justification: text("justification").notNull(),
  neededBy: date("needed_by"),
  requestedBy: uuid("requested_by").references((): AnyPgColumn => userAccount.id),
  decidedBy: uuid("decided_by").references((): AnyPgColumn => userAccount.id),
  decidedAt: timestamp("decided_at", { withTimezone: true }),
  decisionComment: text("decision_comment"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  licenseAssignmentId: uuid("license_assignment_id").references((): AnyPgColumn => licenseAssignment.id),
  clientRequestId: uuid("client_request_id").defaultRandom().notNull(),
}, (table) => ({
  requesterClientRequestUnique: unique(
    "uq_license_request_requester_client_request",
  ).on(table.requestedBy, table.clientRequestId),
}));

export const requestTransition = pgTable("request_transition", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  requestId: uuid("request_id").references((): AnyPgColumn => licenseRequest.id).notNull(),
  fromState: text("from_state"),
  toState: text("to_state").notNull(),
  actorUserId: uuid("actor_user_id").references((): AnyPgColumn => userAccount.id),
  note: text("note"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
});

export const activityRecord = pgTable("activity_record", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  personId: uuid("person_id").references((): AnyPgColumn => person.id).notNull(),
  activityDate: date("activity_date").notNull(),
  counters: jsonb("counters").notNull(),
  rawPayload: jsonb("raw_payload"),
  syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
});

export const costRecord = pgTable("cost_record", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  personId: uuid("person_id").references((): AnyPgColumn => person.id).notNull(),
  costDate: date("cost_date").notNull(),
  amountUsd: numeric("amount_usd", { precision: 12, scale: 4 }).notNull(),
  rawPayload: jsonb("raw_payload"),
  syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
});

export const vendor = pgTable("vendor", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  name: text("name").notNull(),
  category: text("category"),
  connectorType: vendor_connector_type_enum("connector_type").notNull(),
  provisioningProtocol: vendor_provisioning_protocol_enum("provisioning_protocol").notNull(),
  canProvision: boolean("can_provision").notNull(),
  canDeprovision: boolean("can_deprovision").notNull(),
  hasUsageData: boolean("has_usage_data").notNull(),
  hasCostData: boolean("has_cost_data").notNull(),
  identityMatching: vendor_identity_matching_enum("identity_matching").notNull(),
  status: vendor_status_enum("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
});

export const vendorAccount = pgTable("vendor_account", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorId: uuid("vendor_id").references((): AnyPgColumn => vendor.id).notNull(),
  name: text("name").notNull(),
  mode: vendor_account_mode_enum("mode").notNull(),
  vendorOrgRef: text("vendor_org_ref"),
  contractRenewalOn: date("contract_renewal_on"),
  lowPoolFloor: integer("low_pool_floor").notNull(),
  status: vendor_account_status_enum("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  updatedBy: uuid("updated_by").references((): AnyPgColumn => userAccount.id),
}, (table) => ({
  lowPoolFloorNonnegative: check(
    "vendor_account_low_pool_floor_nonnegative",
    sql`${table.lowPoolFloor} >= 0`,
  ),
  vendorOrgRefUnique: uniqueIndex("uq_vendor_account_vendor_id_vendor_org_ref")
    .on(table.vendorId, table.vendorOrgRef)
    .where(sql`${table.vendorOrgRef} IS NOT NULL`),
}));

export const vendorAccountCapacity = pgTable("vendor_account_capacity", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  licenseTypeId: uuid("license_type_id").references((): AnyPgColumn => licenseType.id).notNull(),
  purchasedQty: integer("purchased_qty").notNull(),
  effectiveFrom: date("effective_from").notNull(),
  note: text("note"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
}, (table) => ({
  purchasedQtyNonnegative: check(
    "vendor_account_capacity_purchased_qty_nonnegative",
    sql`${table.purchasedQty} >= 0`,
  ),
}));

export const licenseType = pgTable("license_type", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorId: uuid("vendor_id").references((): AnyPgColumn => vendor.id).notNull(),
  name: text("name").notNull(),
  unit: license_type_unit_enum("unit").notNull(),
  status: license_type_status_enum("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
});

export const integrationCredential = pgTable("integration_credential", {
  id: uuid("id").primaryKey().defaultRandom().notNull(),
  vendorAccountId: uuid("vendor_account_id").references((): AnyPgColumn => vendorAccount.id).notNull(),
  kind: integration_credential_kind_enum("kind").notNull(),
  encryptedSecret: text("encrypted_secret").notNull(),
  scopes: text("scopes"),
  last4: text("last4"),
  lastVerifiedAt: timestamp("last_verified_at", { withTimezone: true }),
  health: integration_credential_health_enum("health").notNull(),
  status: integration_credential_status_enum("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  createdBy: uuid("created_by").references((): AnyPgColumn => userAccount.id).notNull(),
}, (table) => ({
  oneActiveKind: uniqueIndex("uq_integration_credential_active_kind")
    .on(table.vendorAccountId, table.kind)
    .where(sql`${table.status} = 'active'`),
}));
