#!/usr/bin/env node
// mutation-scope — diff-scoped Stryker run (generated by Nous, IMP-344 / L1).
//
// ONE campaign over the files this branch actually changed, instead of a
// whole-tree run or a hand-chained per-story sequence. The common case — a diff
// with nothing mutatable — exits 0 in milliseconds without starting Stryker.
//
// Scope is the DIFF, filtered to mutatable source files. Deliberately NOT
// intersected with the critical set: nothing declares critical source *paths*,
// and guessing them could only drop a changed critical file from the run. The
// critical set decides which STORIES owe mutation evidence (see
// docs/dev-guide/TESTING.md §3), not which files get mutated.
//
// Env overrides:
//   MUTATION_BASE=<ref>   compare against this ref instead of the default branch
//   MUTATION_SCOPE_DRY=1  write + print the generated config, do NOT run Stryker
import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import ts from "../apps/web/node_modules/typescript/lib/typescript.js";

const BASE_CONFIG = "stryker.conf.json";
const GENERATED_SHARD_DIR = join(".tmp", "stryker-shards");
const GENERATED_MANIFEST = join(GENERATED_SHARD_DIR, "manifest.json");
const SCHEMA_STATIC_SOURCE = "packages/db/src/schema.ts";

// Mirrors stryker.conf.json's mutate globs: which files can carry mutants.
// This is a FILE-TYPE filter, not a critical-set narrowing — a changed `.md` or
// `.json` has no mutants, so excluding it removes nothing real.
const MUTATABLE_EXT = /\.(ts|tsx)$/;
const GENERATED_ARTIFACT = [
  /(^|\/)\.tmp\//,
  /(^|\/)\.next\//,
  /(^|\/)(coverage|dist|reports)\//,
];
const EXCLUDED = [
  /\.(test|spec)\.tsx?$/,
  /\.d\.ts$/,
  /(^|\/)migrations\//,
  /(^|\/)testing\//,
  /(^|\/)node_modules\//,
  ...GENERATED_ARTIFACT,
];

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

/** A git call whose FAILURE is an expected, handled outcome (probing for a ref
 *  that may not exist). git writes `fatal: ...` to stderr even when the caller
 *  copes, so stderr is discarded here — otherwise every run in a repo without
 *  `origin/HEAD` prints a scary line that is not an error. Real failures still
 *  surface: the caller decides, via the thrown exception. */
function gitProbe(args) {
  return execFileSync("git", args, {
    encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

/** Fail LOUD. A mutation run that cannot determine its scope must NOT report
 *  success having mutated nothing — a silent empty scope is a false green. */
function fail(message, hint) {
  console.error(`mutation-scope: ${message}`);
  if (hint) console.error(`  ${hint}`);
  process.exit(2);
}

/** The ref to diff against. Resolved, never hardcoded to `main`: a repo whose
 *  trunk is `master`, or a CI checkout with a different default, must not
 *  silently produce an empty diff. */
function resolveBase() {
  if (process.env.MUTATION_BASE) {
    const ref = process.env.MUTATION_BASE;
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch {
      fail(`MUTATION_BASE=${ref} does not resolve to a ref`,
           "check the ref name, or unset MUTATION_BASE to use the default branch");
    }
  }
  try {
    // origin/HEAD is the authoritative default branch when a remote exists.
    const sym = gitProbe(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"]);
    if (sym) return sym;
  } catch { /* no remote / no origin/HEAD — fall through to local trunks */ }
  for (const ref of ["main", "master"]) {
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch { /* try the next candidate */ }
  }
  fail("cannot resolve a default branch to diff against (tried origin/HEAD, main, master)",
       "set MUTATION_BASE=<ref> explicitly");
}

function changedFiles(base) {
  const mergeBase = mergeBaseFor(base);
  // Diff directly from the merge base so committed, staged, and unstaged
  // changes are all visible. Git diff does not report untracked files, so add
  // every non-ignored untracked path explicitly. Otherwise a newly created
  // production module can silently escape the pre-commit mutation gate.
  // ACMR excludes deletions: Stryker cannot mutate a file that is gone.
  const tracked = git(["diff", "--name-only", "--diff-filter=ACMR", mergeBase]);
  const untracked = git(["ls-files", "--others", "--exclude-standard"]);
  return [...new Set(
    [tracked, untracked]
      .flatMap((value) => value ? value.split("\n") : [])
      .filter(Boolean)
      .filter((path) => !GENERATED_ARTIFACT.some((pattern) => pattern.test(path))),
  )].sort();
}

function mergeBaseFor(base) {
  try {
    return gitProbe(["merge-base", "HEAD", base]);
  } catch {
    // A shallow clone or an unrelated history has no merge base. Exiting 0 here
    // would mutate nothing and report success — the false green this guard
    // exists to prevent.
    fail(`no merge base between HEAD and ${base}`,
         "unshallow the clone (git fetch --unshallow) or set MUTATION_BASE=<ref>");
  }
}

function mutatable(files) {
  return files
    .filter((f) => MUTATABLE_EXT.test(f))
    .filter((f) => !EXCLUDED.some((re) => re.test(f)))
    .sort();  // deterministic: the generated config must be byte-stable
}

function lineCount(contents) {
  if (contents.length === 0) return 0;
  const lines = contents.split(/\r?\n/);
  return lines.length - (lines.at(-1) === "" ? 1 : 0);
}

export function mutationTargetsFromPatch(patch, untracked = new Map()) {
  const targets = [];
  let source = null;
  for (const line of patch.split("\n")) {
    if (line.startsWith("+++ ")) {
      const path = line.slice(4);
      source = path === "/dev/null"
        ? null
        : path.startsWith("b/") ? path.slice(2) : path;
      continue;
    }
    if (!source || !line.startsWith("@@ ")) continue;
    const hunk = /\+(\d+)(?:,(\d+))?/.exec(line);
    if (!hunk) continue;
    const start = Number(hunk[1]);
    const count = hunk[2] === undefined ? 1 : Number(hunk[2]);
    if (count > 0) targets.push(`${source}:${start}-${start + count - 1}`);
  }
  for (const [path, count] of untracked) {
    if (count > 0) targets.push(`${path}:1-${count}`);
  }
  return [...new Set(targets)].sort();
}

export function mutationHunksFromPatch(patch, contentsForSource) {
  const hunks = [];
  let source = null;
  let current = null;
  const finish = () => {
    if (current) hunks.push({
      ...current,
      oldContents: contentsForSource(current.source).oldContents,
      newContents: contentsForSource(current.source).newContents,
    });
    current = null;
  };
  for (const line of patch.split("\n")) {
    if (line.startsWith("+++ ")) {
      source = line.slice(4).replace(/^b\//, "");
      continue;
    }
    if (line.startsWith("@@ ")) {
      finish();
      const header = /-(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))?/.exec(line);
      if (!header || !source) throw new Error(`cannot parse mutation hunk: ${line}`);
      current = {
        source,
        oldStart: Number(header[1]),
        oldLines: [],
        newStart: Number(header[3]),
        newLines: [],
      };
      continue;
    }
    if (!current) continue;
    if (line.startsWith("-") && !line.startsWith("---")) current.oldLines.push(line.slice(1));
    if (line.startsWith("+") && !line.startsWith("+++")) current.newLines.push(line.slice(1));
  }
  finish();
  return hunks;
}

export function mutationSourceFiles(targets) {
  return [...new Set(
    targets.map((target) => target.replace(/:\d+-\d+$/, "")),
  )].sort();
}

export function groupRoutedMutationTargets(targets, routeTestsForSource) {
  const groups = new Map();
  for (const source of mutationSourceFiles(targets)) {
    const testFiles = [...new Set(routeTestsForSource(source))].sort();
    if (testFiles.length === 0) {
      throw new Error(`mutatable source has no responsible Vitest test route: ${source}`);
    }
    const key = JSON.stringify(testFiles);
    const group = groups.get(key) ?? { mutate: [], sources: [], testFiles };
    group.sources.push(source);
    group.mutate.push(
      ...targets.filter((target) => target.replace(/:\d+-\d+$/, "") === source),
    );
    groups.set(key, group);
  }
  return [...groups.values()]
    .map((group) => ({
      mutate: [...new Set(group.mutate)].sort(),
      sources: [...new Set(group.sources)].sort(),
      testFiles: group.testFiles,
    }))
    .sort((left, right) =>
      JSON.stringify(left.sources).localeCompare(JSON.stringify(right.sources)) ||
      JSON.stringify(left.testFiles).localeCompare(JSON.stringify(right.testFiles)));
}

function parseModule(source, contents) {
  const parsed = ts.createSourceFile(
    source,
    contents,
    ts.ScriptTarget.Latest,
    true,
    source.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  if (parsed.parseDiagnostics.length > 0) {
    throw new Error(`verification-only candidate has parse errors: ${source}`);
  }
  return parsed;
}

function relativeModuleTarget(source, specifier, fileExists) {
  if (!specifier.startsWith("./") && !specifier.startsWith("../")) {
    throw new Error(`verification-only module specifier is not relative: ${specifier}`);
  }
  const unresolved = join(dirname(source), specifier.replace(/\.js$/, ""));
  const candidates = [
    `${unresolved}.ts`,
    `${unresolved}.tsx`,
    join(unresolved, "index.ts"),
    join(unresolved, "index.tsx"),
  ].filter(fileExists);
  if (candidates.length !== 1) {
    throw new Error(
      `verification-only module specifier resolves ${candidates.length} targets: ${specifier}`,
    );
  }
  return candidates[0];
}

function moduleDeclarations(parsed) {
  return parsed.statements.filter((node) =>
    (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
    node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier));
}

function declarationOnLine(parsed, lineNumber, predicate) {
  const matches = moduleDeclarations(parsed).filter((node) => {
    if (!predicate(node)) return false;
    const token = node.moduleSpecifier;
    const start = parsed.getLineAndCharacterOfPosition(token.getStart(parsed)).line + 1;
    const end = parsed.getLineAndCharacterOfPosition(token.getEnd()).line + 1;
    return start === lineNumber && end === lineNumber;
  });
  if (matches.length !== 1) {
    throw new Error(`verification-only hunk has ${matches.length} exact module declarations`);
  }
  return matches[0];
}

function fingerprint(lines) {
  return createHash("sha256").update(lines.join("\n")).digest("hex");
}

/** Classify only the two AST shapes that are inherently non-mutatable:
 * an existing relative import whose sole token edit appends `.js`, or a newly
 * added exact `export * from` declaration. Any mixed, unresolved, ambiguous,
 * or parse-invalid hunk throws instead of silently escaping mutation. */
export function classifyVerificationOnlyHunk(change, fileExists = existsSync) {
  const {
    source, oldContents, newContents,
    oldStart, oldLines, newStart, newLines,
  } = change;
  const oldParsed = parseModule(source, oldContents);
  const newParsed = parseModule(source, newContents);
  let reason;
  let specifier;

  if (oldLines.length === 1 && newLines.length === 1) {
    const oldNode = declarationOnLine(oldParsed, oldStart, ts.isImportDeclaration);
    const newNode = declarationOnLine(newParsed, newStart, ts.isImportDeclaration);
    const oldSpecifier = oldNode.moduleSpecifier.text;
    specifier = newNode.moduleSpecifier.text;
    const oldToken = oldNode.moduleSpecifier.getText(oldParsed);
    const newToken = newNode.moduleSpecifier.getText(newParsed);
    if (
      specifier !== `${oldSpecifier}.js` || oldSpecifier.endsWith(".js") ||
      oldLines[0].replace(oldToken, "<module>") !==
        newLines[0].replace(newToken, "<module>")
    ) {
      throw new Error("verification-only import must solely append .js to its module token");
    }
    reason = "relative-import-appends-js";
  } else if (oldLines.length === 0 && newLines.length === 1) {
    const node = declarationOnLine(
      newParsed,
      newStart,
      (candidate) => ts.isExportDeclaration(candidate) &&
        candidate.exportClause === undefined && !candidate.isTypeOnly,
    );
    const exactNodeText = node.getText(newParsed);
    if (newLines[0].trim() !== exactNodeText) {
      throw new Error("verification-only re-export hunk must contain one exact export declaration");
    }
    specifier = node.moduleSpecifier.text;
    reason = "new-relative-export-star";
  } else {
    throw new Error("verification-only hunk is mixed or spans unsupported lines");
  }

  const resolvedTarget = relativeModuleTarget(source, specifier, fileExists);
  return {
    newFingerprint: fingerprint(newLines),
    oldFingerprint: fingerprint(oldLines),
    range: `${source}:${newStart}-${newStart + newLines.length - 1}`,
    reason,
    resolvedTarget,
  };
}

export function requireNonzeroMutationReport(report, shardId) {
  const mutants = mutationReportMutants(report);
  if (mutants.length === 0) {
    throw new Error(`scored mutation shard ${shardId} instrumented zero mutants`);
  }
  const testable = mutants.filter((mutant) => mutant.status !== "Ignored");
  if (testable.length === 0) {
    throw new Error(`scored mutation shard ${shardId} has zero testable mutants`);
  }
  return testable.length;
}

function mutationReportMutants(report) {
  return report?.files && typeof report.files === "object"
    ? Object.values(report.files).flatMap((file) =>
        Array.isArray(file?.mutants) ? file.mutants : [])
    : [];
}

export function verificationAuditsForReport(
  report,
  shard,
  allHunks,
  classify = classifyVerificationOnlyHunk,
) {
  if (mutationReportMutants(report).length > 0) {
    throw new Error(`nonzero mutation shard ${shard.id} cannot downgrade to verification-only`);
  }
  return shard.mutate.map((range) => {
    const change = allHunks.find((candidate) =>
      `${candidate.source}:${candidate.newStart}-${candidate.newStart + candidate.newLines.length - 1}` === range);
    if (!change) throw new Error(`no exact diff hunk for zero-mutant range: ${range}`);
    return classify(change);
  });
}

export function readFreshMutationReport(
  reportPath,
  startedAt,
  fileStat = statSync,
  fileRead = (path) => readFileSync(path, "utf8"),
) {
  let metadata;
  try {
    metadata = fileStat(reportPath);
  } catch {
    throw new Error(`missing mutation report: ${reportPath}`);
  }
  if (metadata.mtimeMs < startedAt) {
    throw new Error(`stale mutation report: ${reportPath}`);
  }
  try {
    return JSON.parse(fileRead(reportPath));
  } catch {
    throw new Error(`malformed mutation report: ${reportPath}`);
  }
}

export function runVerificationCommands(commands, run = spawnSync) {
  if (commands.length === 0) throw new Error("verification-only result has no commands");
  for (const [command, args] of commands) {
    const result = run(command, args, { stdio: "inherit" });
    if (result.status !== 0) {
      throw new Error(`verification command failed: ${command} ${args.join(" ")}`);
    }
  }
  return commands.length;
}

export function verificationCommandsForSources(sources, testFiles) {
  const commands = [];
  if (sources.some((source) => source.startsWith("packages/connectors/"))) {
    commands.push(["node", ["--eval", 'require("node:fs").rmSync("packages/connectors/dist/module-wiring", { recursive: true, force: true })']]);
    commands.push(["pnpm", [
      "--filter", "@smp/connectors", "exec", "tsc",
      "--outDir", "dist/module-wiring", "--noEmit", "false",
      "--declaration", "false", "--composite", "false",
    ]]);
    commands.push(["node", ["--input-type=module", "--eval", [
      'const module = await import("./packages/connectors/dist/module-wiring/action-planner.js");',
      'if (typeof module.planProvisioningAction !== "function") throw new Error("missing planner export");',
      'try { await import("./packages/connectors/dist/module-wiring/contracts"); throw new Error("extensionless negative control resolved"); }',
      'catch (error) { if (error.code !== "ERR_MODULE_NOT_FOUND") throw error; }',
    ].join(" ")]]);
  }
  if (sources.some((source) => source.startsWith("packages/contracts/"))) {
    commands.push(["pnpm", ["--filter", "@smp/contracts", "build"]]);
  }
  commands.push([
    "./apps/web/node_modules/.bin/vitest",
    ["run", "--config", "vitest.mutation.config.mjs", ...testFiles],
  ]);
  return commands;
}

function mutationTargets(base, sourceFiles) {
  if (sourceFiles.length === 0) return [];
  const mergeBase = mergeBaseFor(base);
  const patch = git([
    "-c", "core.quotepath=false", "diff", "--no-ext-diff", "--no-renames",
    "--unified=0", "--diff-filter=ACMR", mergeBase, "--", ...sourceFiles,
  ]);
  const untrackedPaths = new Set(
    git(["ls-files", "--others", "--exclude-standard"])
      .split("\n")
      .filter(Boolean),
  );
  const untracked = new Map(
    sourceFiles
      .filter((path) => untrackedPaths.has(path))
      .map((path) => [path, lineCount(readFileSync(path, "utf8"))]),
  );
  return mutationTargetsFromPatch(patch, untracked);
}

function mutationHunks(base, sourceFiles) {
  if (sourceFiles.length === 0) return [];
  const mergeBase = mergeBaseFor(base);
  const patch = git([
    "-c", "core.quotepath=false", "diff", "--no-ext-diff", "--no-renames",
    "--unified=0", "--diff-filter=ACMR", mergeBase, "--", ...sourceFiles,
  ]);
  const cache = new Map();
  const contentsForSource = (source) => {
    if (!cache.has(source)) {
      let oldContents = "";
      try {
        oldContents = execFileSync("git", ["show", `${mergeBase}:${source}`], {
          encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
        });
      } catch { /* added file */ }
      cache.set(source, { oldContents, newContents: readFileSync(source, "utf8") });
    }
    return cache.get(source);
  };
  return mutationHunksFromPatch(patch, contentsForSource);
}

const TEST_FILE = /\.(test|spec)\.(ts|tsx)$/;
const ADJACENT_TEST_SUFFIXES = [
  ".test.ts",
  ".test.tsx",
  ".integration.test.ts",
  ".integration.test.tsx",
  ".pact.test.ts",
  ".spec.ts",
  ".spec.tsx",
];

// Thin composition roots and config/barrel files deliberately do not have an
// adjacent test. Their behavior is owned by these contract tests. Keeping the
// exceptional routes explicit prevents a changed source from silently riding
// along merely because some unrelated story test also changed.
export const DIRECT_TEST_ROUTES = {
  "apps/web/src/app/(authenticated)/usuarios/page.tsx": [
    "apps/web/src/components/users/users-roles-panel.test.tsx",
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/actions/manage-users.ts": [
    "apps/web/src/components/users/users-roles-panel.test.tsx",
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/server-authorization.ts": [
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/users-roles-page.tsx": [
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/request-workflow/approval/repository.ts": [
    "apps/web/src/modules/request-workflow/approval-repository.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/capacity-recovery-outbox.ts": [
    "apps/web/src/modules/vendor-catalog/capacity-service.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/no-seat-observation.ts": [
    "apps/web/src/modules/vendor-catalog/capacity-service.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-capacity-operations.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-capacity.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-capacity.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-capacity.test.ts",
  ],
  "apps/web/vitest.config.ts": [
    "apps/web/src/modules/identity-access/keycloak-admin.pact.test.ts",
  ],
  "packages/contracts/src/index.ts": [
    "packages/contracts/src/capacity.test.ts",
    "packages/contracts/src/identity-access.test.ts",
  ],
  "packages/connectors/src/index.ts": [
    "packages/connectors/src/action-planner.test.ts",
    "packages/connectors/src/dispatch.test.ts",
  ],
  "packages/db/src/provisioning-routing.ts": [
    "packages/db/src/provisioning-routing.test.ts",
  ],
  "packages/db/src/schema.ts": [
    "packages/db/src/schema.test.ts",
  ],
  "scripts/probes/anthropic/vitest.contract.config.ts": [
    "apps/web/src/modules/identity-access/keycloak-admin.pact.test.ts",
  ],
};

// Static source/schema enforcement tests inspect an uninstrumented application
// tree. Stryker necessarily rewrites that tree before its dry run, so these
// scanners reject the mutation sandbox itself before any mutant can run. They
// remain mandatory in the normal lint/check pipeline.
const MUTATION_INCOMPATIBLE_TESTS = new Set([
  "apps/web/src/modules/audit/audited-actions-enforcement.test.ts",
  "packages/db/src/migration-release.integration.test.ts",
  "packages/db/src/schema-parity.test.ts",
]);

export function mutationCompatibleTestFiles(testFiles) {
  return testFiles.filter((file) => !MUTATION_INCOMPATIBLE_TESTS.has(file));
}

function testsForSource(source, fileExists, directRoutes) {
  const responsible = new Set();
  const stem = source.replace(/\.(ts|tsx)$/, "");
  for (const suffix of ADJACENT_TEST_SUFFIXES) {
    const candidate = `${stem}${suffix}`;
    if (fileExists(candidate)) responsible.add(candidate);
  }
  for (const candidate of directRoutes[source] ?? []) {
    if (fileExists(candidate)) responsible.add(candidate);
  }
  return [...responsible].sort();
}

export function routedTestFiles(changed, mutate, fileExists = existsSync, directRoutes = DIRECT_TEST_ROUTES) {
  const routed = new Set(changed.filter((file) => TEST_FILE.test(file)));
  for (const source of mutate) {
    for (const candidate of testsForSource(source, fileExists, directRoutes)) routed.add(candidate);
  }
  return [...routed].sort();
}

export function requireRoutedTestFiles(changed, mutate, fileExists = existsSync, directRoutes = DIRECT_TEST_ROUTES) {
  for (const source of mutate) {
    if (testsForSource(source, fileExists, directRoutes).length === 0) {
      throw new Error(`mutatable source has no responsible Vitest test route: ${source}`);
    }
  }
  return routedTestFiles(changed, mutate, fileExists, directRoutes);
}

function main() {
  const base = resolveBase();
  const changed = changedFiles(base);
  const changedSources = mutatable(changed);
  const allMutate = mutationTargets(base, changedSources);
  const allHunks = mutationHunks(base, changedSources);
  const schemaStaticMutate = allMutate.filter((target) =>
    target.replace(/:\d+-\d+$/, "") === SCHEMA_STATIC_SOURCE);
  const routedMutate = allMutate.filter((target) => !schemaStaticMutate.includes(target));

  console.log(
    `mutation-scope: base=${base} changed=${changed.length} ` +
      `mutatable=${mutationSourceFiles(allMutate).length} ranges=${allMutate.length} ` +
      `schemaStaticRanges=${schemaStaticMutate.length}`,
  );

  if (allMutate.length === 0) {
    console.log("mutation-scope: no mutatable files in diff — nothing to mutate");
    process.exit(0);
  }

  let baseConf = {};
  try {
    baseConf = JSON.parse(readFileSync(BASE_CONFIG, "utf8"));
  } catch {
    fail(`cannot read ${BASE_CONFIG}`, "run from the repository root");
  }

  let routedGroups;
  try {
    routedGroups = groupRoutedMutationTargets(routedMutate, (source) =>
      mutationCompatibleTestFiles(testsForSource(source, existsSync, DIRECT_TEST_ROUTES)));
  } catch (error) {
    fail(error.message, "add a conventional adjacent test or an explicit accountable route");
  }

  const shardSpecs = routedGroups.map((group) => ({ kind: "vitest", ...group }));
  if (schemaStaticMutate.length > 0) {
    requireRoutedTestFiles(
      changed,
      mutationSourceFiles(schemaStaticMutate),
    );
    shardSpecs.push({
      kind: "schema-static",
      mutate: schemaStaticMutate,
      sources: [SCHEMA_STATIC_SOURCE],
      testFiles: ["packages/db/src/schema.test.ts"],
    });
  }

  const {
    commandRunner: _commandRunner,
    htmlReporter: _htmlReporter,
    mutate: _baseMutate,
    tempDirName: _tempDirName,
    testFiles: _baseTestFiles,
    vitest: _baseVitest,
    ...sharedBaseConf
  } = baseConf;
  const shards = shardSpecs.map((spec) => {
    const digest = createHash("sha256")
      .update([spec.kind, ...spec.sources, ...spec.testFiles, ...spec.mutate].join("\n"))
      .digest("hex")
      .slice(0, 12);
    const id = `${spec.kind}-${digest}`;
    const configPath = join(GENERATED_SHARD_DIR, `${id}.json`);
    const tempDirName = join(".tmp", `stryker-${id}`);
    const reportPath = join("reports", "mutation", `${id}.html`);
    const jsonReportPath = join("reports", "mutation", `${id}.json`);
    const common = {
      ...sharedBaseConf,
      mutate: spec.mutate,
      coverageAnalysis: "off",
      concurrency: 1,
      maxTestRunnerReuse: 1,
      timeoutFactor: 2,
      tempDirName,
      htmlReporter: { fileName: reportPath },
      jsonReporter: { fileName: jsonReportPath },
      reporters: [...new Set([...(sharedBaseConf.reporters ?? []), "json"])],
      thresholds: {
        ...baseConf.thresholds,
        high: 80,
        break: 80,
      },
    };
    const config = spec.kind === "schema-static"
      ? {
          ...common,
          testRunner: "command",
          commandRunner: {
            command: "./apps/web/node_modules/.bin/vitest run --root packages/db --config vitest.config.ts src/schema.test.ts",
          },
        }
      : {
          ...common,
          testRunner: "vitest",
          vitest: {
            ...baseConf.vitest,
            related: false,
            configFile: "vitest.mutation.config.mjs",
          },
          testFiles: spec.testFiles,
        };
    return {
      config,
      configPath,
      id,
      kind: spec.kind,
      jsonReportPath,
      mutate: spec.mutate,
      reportPath,
      sources: spec.sources,
      tempDirName,
      testFiles: spec.testFiles,
    };
  }).sort((left, right) => left.id.localeCompare(right.id));

  mkdirSync(GENERATED_SHARD_DIR, { recursive: true });
  for (const shard of shards) {
    writeFileSync(shard.configPath, `${JSON.stringify(shard.config, null, 2)}\n`, "utf8");
  }
  writeFileSync(
    GENERATED_MANIFEST,
    `${JSON.stringify({ base, shards: shards.map(({ config, ...shard }) => shard) }, null, 2)}\n`,
    "utf8",
  );
  console.log(`mutation-scope: wrote ${shards.length} shards + ${GENERATED_MANIFEST}`);

  if (process.env.MUTATION_SCOPE_DRY === "1") {
    console.log("mutation-scope: MUTATION_SCOPE_DRY=1 — not running Stryker");
    process.exit(0);
  }

  try {
    for (const shard of shards) {
      console.log(`mutation-scope: running ${shard.id} (${shard.mutate.length} ranges)`);
      rmSync(shard.jsonReportPath, { force: true });
      const startedAt = Date.now();
      const result = spawnSync(
        "pnpm", ["exec", "stryker", "run", shard.configPath], { stdio: "inherit" },
      );
      const report = readFreshMutationReport(shard.jsonReportPath, startedAt);
      const mutants = mutationReportMutants(report);
      if (mutants.length === 0) {
        if (result.status !== 0) {
          throw new Error(`zero-mutant shard ${shard.id} exited ${result.status}`);
        }
        if (shard.kind === "schema-static") {
          throw new Error(`scored mutation shard ${shard.id} instrumented zero mutants`);
        }
        const audits = verificationAuditsForReport(report, shard, allHunks);
        const commands = verificationCommandsForSources(shard.sources, shard.testFiles);
        runVerificationCommands(commands);
        shard.result = {
          audits,
          commands: commands.map(([command, args]) => [command, ...args]),
          classification: "verification-only",
          mutantCount: 0,
          tests: shard.testFiles,
          toolVersions: {
            node: process.version,
            stryker: execFileSync("pnpm", ["exec", "stryker", "--version"], { encoding: "utf8" }).trim(),
            typescript: ts.version,
          },
        };
        writeFileSync(
          GENERATED_MANIFEST,
          `${JSON.stringify({ base, shards: shards.map(({ config, ...entry }) => entry) }, null, 2)}\n`,
          "utf8",
        );
        console.log(`mutation-scope: verified non-mutatable module wiring ${shard.id}`);
        continue;
      }
      requireNonzeroMutationReport(report, shard.id);
      if (result.status !== 0) process.exit(result.status ?? 1);
    }
  } catch (err) {
    // A non-zero Stryker exit IS the gate failing — propagate the code, but not
    // execFileSync's exception: an uncaught throw prints a JS stack trace after
    // Stryker's own report, which reads as "the tool is broken" rather than
    // "your mutation score is short".
    if (err?.message) console.error(`mutation-scope: ${err.message}`);
    process.exit(typeof err?.status === "number" ? err.status : 1);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
