#!/usr/bin/env node
// mutation-scope — diff-scoped Stryker run (generated by Nous, IMP-344 / L1).
//
// ONE campaign over the files this branch actually changed, instead of a
// whole-tree run or a hand-chained per-story sequence. The common case — a diff
// with nothing mutatable — exits 0 in milliseconds without starting Stryker.
//
// Scope is the DIFF, filtered to mutatable source files. Deliberately NOT
// intersected with the critical set: nothing declares critical source *paths*,
// and guessing them could only drop a changed critical file from the run. The
// critical set decides which STORIES owe mutation evidence (see
// docs/dev-guide/TESTING.md §3), not which files get mutated.
//
// Env overrides:
//   MUTATION_BASE=<ref>   compare against this ref instead of the default branch
//   MUTATION_SCOPE_DRY=1  write + print the generated config, do NOT run Stryker
import { execFileSync, spawn, spawnSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync } from "node:fs";
import os from "node:os";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import ts from "../apps/web/node_modules/typescript/lib/typescript.js";
import {
  cacheRoot,
  projectMutationReportArtifact,
  readCacheEntry,
  writeSuccessfulCacheEntry,
} from "./mutation-evidence/cache.mjs";
import { canonicalJson, collectExecutionInputs, createEvidenceKey, sha256 } from "./mutation-evidence/fingerprint.mjs";
import {
  createPerformanceRun,
  finishPerformanceRun,
  finishShard,
  startShard,
  writePerformanceRecord,
} from "./mutation-evidence/performance.mjs";
import { validatePoolProjectionEvidence } from "./verify-pool-snapshot-projection.mjs";

const BASE_CONFIG = "stryker.conf.json";
const GENERATED_SHARD_DIR = join(".tmp", "stryker-shards");
const GENERATED_MANIFEST = join(GENERATED_SHARD_DIR, "manifest.json");
const SCHEMA_STATIC_SOURCE = "packages/db/src/schema.ts";
const VITEST_CONFIG_STATIC_SOURCE = "apps/web/vitest.config.ts";
const VITEST_CONFIG_STATIC_RANGE = `${VITEST_CONFIG_STATIC_SOURCE}:21-21`;
const SCORED_STATIC_KINDS = new Set(["schema-static", "vitest-config-static"]);
const EXACT_FRAMEWORK_ADAPTER_KIND = "exact-framework-adapter";
const MUTATION_RUNNER_STATIC_INPUTS = [
  "scripts/mutation-scope.mjs",
  "scripts/mutation-evidence/fingerprint.mjs",
  "scripts/mutation-evidence/cache.mjs",
  "scripts/mutation-evidence/performance.mjs",
];
const POOL_PROJECTION_STATIC_INPUTS = [
  "scripts/verify-pool-snapshot-projection.mjs",
];

// Mirrors stryker.conf.json's mutate globs: which files can carry mutants.
// This is a FILE-TYPE filter, not a critical-set narrowing — a changed `.md` or
// `.json` has no mutants, so excluding it removes nothing real.
const MUTATABLE_EXT = /\.(ts|tsx)$/;
const GENERATED_ARTIFACT = [
  /(^|\/)\.tmp\//,
  /(^|\/)\.next\//,
  /(^|\/)(coverage|dist|reports)\//,
];
const EXCLUDED = [
  /\.(test|spec)\.tsx?$/,
  /\.d\.ts$/,
  /(^|\/)e2e\//,
  /(^|\/)playwright\.config\.(ts|js|mts|mjs)$/,
  /(^|\/)migrations\//,
  /(^|\/)testing\//,
  /(^|\/)node_modules\//,
  ...GENERATED_ARTIFACT,
];

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

/** A git call whose FAILURE is an expected, handled outcome (probing for a ref
 *  that may not exist). git writes `fatal: ...` to stderr even when the caller
 *  copes, so stderr is discarded here — otherwise every run in a repo without
 *  `origin/HEAD` prints a scary line that is not an error. Real failures still
 *  surface: the caller decides, via the thrown exception. */
function gitProbe(args) {
  return execFileSync("git", args, {
    encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

/** Fail LOUD. A mutation run that cannot determine its scope must NOT report
 *  success having mutated nothing — a silent empty scope is a false green. */
function fail(message, hint) {
  console.error(`mutation-scope: ${message}`);
  if (hint) console.error(`  ${hint}`);
  process.exit(2);
}

/** The ref to diff against. Resolved, never hardcoded to `main`: a repo whose
 *  trunk is `master`, or a CI checkout with a different default, must not
 *  silently produce an empty diff. */
function resolveBase() {
  if (process.env.MUTATION_BASE) {
    const ref = process.env.MUTATION_BASE;
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch {
      fail(`MUTATION_BASE=${ref} does not resolve to a ref`,
           "check the ref name, or unset MUTATION_BASE to use the default branch");
    }
  }
  try {
    // origin/HEAD is the authoritative default branch when a remote exists.
    const sym = gitProbe(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"]);
    if (sym) return sym;
  } catch { /* no remote / no origin/HEAD — fall through to local trunks */ }
  for (const ref of ["main", "master"]) {
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch { /* try the next candidate */ }
  }
  fail("cannot resolve a default branch to diff against (tried origin/HEAD, main, master)",
       "set MUTATION_BASE=<ref> explicitly");
}

function changedFiles(base) {
  const mergeBase = mergeBaseFor(base);
  // Diff directly from the merge base so committed, staged, and unstaged
  // changes are all visible. Git diff does not report untracked files, so add
  // every non-ignored untracked path explicitly. Otherwise a newly created
  // production module can silently escape the pre-commit mutation gate.
  // ACMR excludes deletions: Stryker cannot mutate a file that is gone.
  const tracked = git(["diff", "--name-only", "--diff-filter=ACMR", mergeBase]);
  const untracked = git(["ls-files", "--others", "--exclude-standard"]);
  return [...new Set(
    [tracked, untracked]
      .flatMap((value) => value ? value.split("\n") : [])
      .filter(Boolean)
      .filter((path) => !GENERATED_ARTIFACT.some((pattern) => pattern.test(path))),
  )].sort();
}

function mergeBaseFor(base) {
  try {
    return gitProbe(["merge-base", "HEAD", base]);
  } catch {
    // A shallow clone or an unrelated history has no merge base. Exiting 0 here
    // would mutate nothing and report success — the false green this guard
    // exists to prevent.
    fail(`no merge base between HEAD and ${base}`,
         "unshallow the clone (git fetch --unshallow) or set MUTATION_BASE=<ref>");
  }
}

export function mutatable(files) {
  return files
    .filter((f) => MUTATABLE_EXT.test(f))
    .filter((f) => !EXCLUDED.some((re) => re.test(f)))
    .sort();  // deterministic: the generated config must be byte-stable
}

function lineCount(contents) {
  if (contents.length === 0) return 0;
  const lines = contents.split(/\r?\n/);
  return lines.length - (lines.at(-1) === "" ? 1 : 0);
}

export function mutationTargetsFromPatch(patch, untracked = new Map()) {
  const targets = [];
  let source = null;
  for (const line of patch.split("\n")) {
    if (line.startsWith("+++ ")) {
      const path = line.slice(4);
      source = path === "/dev/null"
        ? null
        : path.startsWith("b/") ? path.slice(2) : path;
      continue;
    }
    if (!source || !line.startsWith("@@ ")) continue;
    const hunk = /\+(\d+)(?:,(\d+))?/.exec(line);
    if (!hunk) continue;
    const start = Number(hunk[1]);
    const count = hunk[2] === undefined ? 1 : Number(hunk[2]);
    if (count > 0) targets.push(`${source}:${start}-${start + count - 1}`);
  }
  for (const [path, count] of untracked) {
    if (count > 0) targets.push(`${path}:1-${count}`);
  }
  return [...new Set(targets)].sort();
}

export function mutationHunksFromPatch(patch, contentsForSource) {
  const hunks = [];
  let source = null;
  let current = null;
  const finish = () => {
    if (current) hunks.push({
      ...current,
      oldContents: contentsForSource(current.source).oldContents,
      newContents: contentsForSource(current.source).newContents,
    });
    current = null;
  };
  for (const line of patch.split("\n")) {
    if (line.startsWith("+++ ")) {
      source = line.slice(4).replace(/^b\//, "");
      continue;
    }
    if (line.startsWith("@@ ")) {
      finish();
      const header = /-(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))?/.exec(line);
      if (!header || !source) throw new Error(`cannot parse mutation hunk: ${line}`);
      current = {
        source,
        oldStart: Number(header[1]),
        oldLines: [],
        newStart: Number(header[3]),
        newLines: [],
      };
      continue;
    }
    if (!current) continue;
    if (line.startsWith("-") && !line.startsWith("---")) current.oldLines.push(line.slice(1));
    if (line.startsWith("+") && !line.startsWith("+++")) current.newLines.push(line.slice(1));
  }
  finish();
  return hunks;
}

export function mutationSourceFiles(targets) {
  return [...new Set(
    targets.map((target) => target.replace(/:\d+-\d+$/, "")),
  )].sort();
}

/** Stryker interprets mutate paths with minimatch even when they carry an
 * exact line range. Escape bracketed Next.js route segments so a literal
 * `[vendorAccountId]` directory cannot be treated as a character class. */
export function strykerMutationTarget(target) {
  return target.replace(/[\[\]]/g, (bracket) => bracket === "[" ? "[[]" : "[]]");
}

export function groupRoutedMutationTargets(targets, routeTestsForSource) {
  const groups = new Map();
  for (const source of mutationSourceFiles(targets)) {
    const testFiles = [...new Set(routeTestsForSource(source))].sort();
    if (testFiles.length === 0) {
      throw new Error(`mutatable source has no responsible Vitest test route: ${source}`);
    }
    const key = JSON.stringify(testFiles);
    const group = groups.get(key) ?? { mutate: [], sources: [], testFiles };
    group.sources.push(source);
    group.mutate.push(
      ...targets.filter((target) => target.replace(/:\d+-\d+$/, "") === source),
    );
    groups.set(key, group);
  }
  return [...groups.values()]
    .map((group) => ({
      mutate: [...new Set(group.mutate)].sort(),
      sources: [...new Set(group.sources)].sort(),
      testFiles: group.testFiles,
    }))
    .sort((left, right) =>
      JSON.stringify(left.sources).localeCompare(JSON.stringify(right.sources)) ||
      JSON.stringify(left.testFiles).localeCompare(JSON.stringify(right.testFiles)));
}

function parseModule(source, contents) {
  const parsed = ts.createSourceFile(
    source,
    contents,
    ts.ScriptTarget.Latest,
    true,
    source.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  if (parsed.parseDiagnostics.length > 0) {
    throw new Error(`verification-only candidate has parse errors: ${source}`);
  }
  return parsed;
}

function sourcePackageRoot(source) {
  const segments = source.split("/");
  return segments[0] === "packages" || segments[0] === "apps"
    ? join(segments[0], segments[1])
    : segments[0];
}

function relativeModuleTarget(source, specifier, fileExists) {
  if (!specifier.startsWith("./") && !specifier.startsWith("../")) {
    throw new Error(`verification-only module specifier is not relative: ${specifier}`);
  }
  const unresolved = join(dirname(source), specifier.replace(/\.js$/, ""));
  const candidates = [
    `${unresolved}.ts`,
    `${unresolved}.tsx`,
    join(unresolved, "index.ts"),
    join(unresolved, "index.tsx"),
  ].filter(fileExists);
  if (candidates.length !== 1) {
    throw new Error(
      `verification-only module specifier resolves ${candidates.length} targets: ${specifier}`,
    );
  }
  const canonicalize = fileExists === existsSync ? realpathSync : resolve;
  const repositoryRoot = canonicalize(resolve("."));
  const packageRoot = canonicalize(resolve(sourcePackageRoot(source)));
  const resolvedCandidate = canonicalize(resolve(candidates[0]));
  if (
    relative(repositoryRoot, resolvedCandidate).startsWith(`..${sep}`) ||
    relative(packageRoot, resolvedCandidate).startsWith(`..${sep}`)
  ) {
    throw new Error(`verification-only module target escapes its package: ${specifier}`);
  }
  return candidates[0];
}

function moduleDeclarations(parsed) {
  return parsed.statements.filter((node) =>
    (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
    node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier));
}

function declarationOnLine(parsed, lineNumber, predicate) {
  const matches = moduleDeclarations(parsed).filter((node) => {
    if (!predicate(node)) return false;
    const token = node.moduleSpecifier;
    const start = parsed.getLineAndCharacterOfPosition(token.getStart(parsed)).line + 1;
    const end = parsed.getLineAndCharacterOfPosition(token.getEnd()).line + 1;
    return start === lineNumber && end === lineNumber;
  });
  if (matches.length !== 1) {
    throw new Error(`verification-only hunk has ${matches.length} exact module declarations`);
  }
  return matches[0];
}

function assertNoImportAttributes(node) {
  if (node.attributes || node.assertClause) {
    throw new Error("verification-only module declaration cannot use attributes or assertions");
  }
}

function assertRawJsAppend(oldNode, newNode, oldParsed, newParsed, oldLine, newLine) {
  assertNoImportAttributes(oldNode);
  assertNoImportAttributes(newNode);
  const oldToken = oldNode.moduleSpecifier.getText(oldParsed);
  const newToken = newNode.moduleSpecifier.getText(newParsed);
  if (
    oldToken.length < 3 ||
    newToken !== `${oldToken.slice(0, -1)}.js${oldToken.slice(-1)}` ||
    oldLine.replace(oldToken, "<module>") !== newLine.replace(newToken, "<module>")
  ) {
    throw new Error("verification-only module edit must solely insert .js before the unchanged closing quote");
  }
  return newNode.moduleSpecifier.text;
}

function fingerprint(lines) {
  return createHash("sha256").update(lines.join("\n")).digest("hex");
}

function contentHash(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

export function normalizeMutationConfigIdentity(config) {
  return {
    ...config,
    tempDirName: "<mutation-temp-dir>",
    htmlReporter: { ...config.htmlReporter, fileName: "<mutation-report-html>" },
    jsonReporter: { ...config.jsonReporter, fileName: "<mutation-report-json>" },
  };
}

function rangeParts(target) {
  const match = /^(.*):(\d+)-(\d+)$/.exec(target);
  if (!match) throw new Error(`invalid mutation range: ${target}`);
  return { source: match[1], start: Number(match[2]), end: Number(match[3]) };
}

export function validateMutationReportIdentity(
  report,
  shard,
  actualConfigText,
  sourceContents,
) {
  let actualConfig;
  try {
    actualConfig = JSON.parse(actualConfigText);
  } catch {
    throw new Error(`mutation config is malformed: ${shard.id}`);
  }
  const normalizedConfigHash = contentHash(
    `${JSON.stringify(normalizeMutationConfigIdentity(actualConfig), null, 2)}\n`,
  );
  if (contentHash(actualConfigText) !== shard.configHash && normalizedConfigHash !== shard.configHash) {
    throw new Error(`mutation config hash mismatch: ${shard.id}`);
  }
  for (const [source, expectedHash] of Object.entries(shard.contentHashes)) {
    if (contentHash(sourceContents(source)) !== expectedHash) {
      throw new Error(`mutation source content hash mismatch: ${source}`);
    }
  }
  if (
    JSON.stringify(report?.config?.mutate) !== JSON.stringify(shard.mutate) ||
    report?.config?.configFile !== shard.configPath ||
    report?.config?.jsonReporter?.fileName !== shard.jsonReportPath
  ) {
    throw new Error(`mutation report config identity mismatch: ${shard.id}`);
  }
  const ranges = shard.mutate.map(rangeParts);
  const reportedSources = Object.keys(report?.files ?? {}).sort();
  const reportMutants = mutationReportMutants(report);
  if (
    reportMutants.length > 0 &&
    JSON.stringify(reportedSources) !== JSON.stringify([...shard.sources].sort())
  ) {
    throw new Error(`mutation report source identity mismatch: ${shard.id}`);
  }
  for (const [source, file] of Object.entries(report?.files ?? {})) {
    if (!shard.sources.includes(source)) {
      throw new Error(`mutation report contains unexpected source: ${source}`);
    }
    if (typeof file?.source !== "string" || contentHash(file.source) !== shard.contentHashes[source]) {
      throw new Error(`mutation report embedded source hash mismatch: ${source}`);
    }
    for (const mutant of file?.mutants ?? []) {
      const start = mutant.location?.start?.line;
      const end = mutant.location?.end?.line;
      if (!ranges.some((range) =>
        range.source === source && Number.isInteger(start) && Number.isInteger(end) &&
        start >= range.start && end <= range.end)) {
        throw new Error(`mutation report mutant is outside requested ranges: ${source}`);
      }
    }
  }
  return true;
}

/** Classify only the two AST shapes that are inherently non-mutatable:
 * an existing relative import whose sole token edit appends `.js`, or a newly
 * added exact `export * from` declaration. Any mixed, unresolved, ambiguous,
 * or parse-invalid hunk throws instead of silently escaping mutation. */
export function classifyVerificationOnlyHunk(change, fileExists = existsSync) {
  const {
    source, oldContents, newContents,
    oldStart, oldLines, newStart, newLines,
  } = change;
  const oldParsed = parseModule(source, oldContents);
  const newParsed = parseModule(source, newContents);
  let reason;
  let specifier;

  if (oldLines.length === 1 && newLines.length === 1) {
    const oldNode = declarationOnLine(oldParsed, oldStart, ts.isImportDeclaration);
    const newNode = declarationOnLine(newParsed, newStart, ts.isImportDeclaration);
    specifier = assertRawJsAppend(
      oldNode, newNode, oldParsed, newParsed, oldLines[0], newLines[0],
    );
    reason = "relative-import-appends-js";
  } else if (oldLines.length >= 1 && oldLines.length === newLines.length) {
    const resolvedTargets = [];
    for (let index = 0; index < oldLines.length; index += 1) {
      const predicate = (candidate) => ts.isExportDeclaration(candidate) &&
        candidate.exportClause === undefined && !candidate.isTypeOnly;
      const oldNode = declarationOnLine(oldParsed, oldStart + index, predicate);
      const newNode = declarationOnLine(newParsed, newStart + index, predicate);
      const nextSpecifier = assertRawJsAppend(
        oldNode, newNode, oldParsed, newParsed, oldLines[index], newLines[index],
      );
      resolvedTargets.push(relativeModuleTarget(source, nextSpecifier, fileExists));
    }
    return {
      newFingerprint: fingerprint(newLines),
      oldFingerprint: fingerprint(oldLines),
      range: `${source}:${newStart}-${newStart + newLines.length - 1}`,
      reason: "relative-export-stars-append-js",
      resolvedTarget: resolvedTargets,
    };
  } else if (oldLines.length === 0 && newLines.length >= 1) {
    const resolvedTargets = [];
    for (let index = 0; index < newLines.length; index += 1) {
      const node = declarationOnLine(
        newParsed,
        newStart + index,
        (candidate) => ts.isExportDeclaration(candidate) &&
          candidate.exportClause === undefined && !candidate.isTypeOnly,
      );
      assertNoImportAttributes(node);
      const exactNodeText = node.getText(newParsed);
      if (newLines[index].trim() !== exactNodeText) {
        throw new Error("verification-only re-export hunk must contain only exact export declarations");
      }
      resolvedTargets.push(relativeModuleTarget(source, node.moduleSpecifier.text, fileExists));
    }
    return {
      newFingerprint: fingerprint(newLines),
      oldFingerprint: fingerprint(oldLines),
      range: `${source}:${newStart}-${newStart + newLines.length - 1}`,
      reason: "new-relative-export-stars",
      resolvedTarget: resolvedTargets,
    };
  } else {
    throw new Error("verification-only hunk is mixed or spans unsupported lines");
  }

  const resolvedTarget = relativeModuleTarget(source, specifier, fileExists);
  return {
    newFingerprint: fingerprint(newLines),
    oldFingerprint: fingerprint(oldLines),
    range: `${source}:${newStart}-${newStart + newLines.length - 1}`,
    reason,
    resolvedTarget,
  };
}

const POOL_PROJECTION_SOURCE = "packages/db/src/pool-snapshots.ts";
const POOL_PROJECTION_DELTAS = [
  { line: 6, oldLines: [], newLines: ["  readonly effectiveFrom: string;"] },
  { line: 22, oldLines: [], newLines: ["  effective_from: string;"] },
  {
    line: 51,
    oldLines: [],
    newLines: ["            capacity.effective_from::text AS effective_from,"],
  },
  {
    line: 57,
    oldLines: ["              vac.license_type_id, vac.purchased_qty"],
    newLines: [
      "              vac.license_type_id, vac.purchased_qty, vac.effective_from",
    ],
  },
  { line: 107, oldLines: [], newLines: ["    effectiveFrom: row.effective_from,"] },
];

function exactNamedInterfaceProperty(parsed, interfaceName, propertyName) {
  const interfaces = parsed.statements.filter((node) =>
    ts.isInterfaceDeclaration(node) && node.name.text === interfaceName);
  if (interfaces.length !== 1) {
    throw new Error(`database projection wrong scope: expected one ${interfaceName} interface`);
  }
  const properties = interfaces[0].members.filter((node) =>
    ts.isPropertySignature(node) && ts.isIdentifier(node.name) &&
    node.name.text === propertyName);
  if (properties.length !== 1) {
    throw new Error(`database projection missing or duplicate ${interfaceName}.${propertyName}`);
  }
  const [property] = properties;
  if (
    property.questionToken || property.initializer ||
    property.type?.kind !== ts.SyntaxKind.StringKeyword
  ) {
    throw new Error(`database projection ${interfaceName}.${propertyName} has a cast or default`);
  }
}

/** Verify the one inherently non-mutatable US-023 database projection bundle.
 * This is deliberately bound to a single source, function, field pair, and
 * complete five-delta patch; it is not a general SQL or data-wiring escape. */
export function classifyPoolSnapshotProjectionBundle(changes) {
  if (!Array.isArray(changes)) {
    throw new Error("database projection incomplete exact five-delta bundle");
  }
  if (new Set(changes.map((change) => change.newStart)).size !== changes.length) {
    throw new Error("database projection duplicate range");
  }
  if (changes.length !== POOL_PROJECTION_DELTAS.length) {
    throw new Error("database projection incomplete exact five-delta bundle");
  }
  if (changes.some((change) => change.source !== POOL_PROJECTION_SOURCE)) {
    throw new Error("database projection wrong scope");
  }
  const ordered = [...changes].sort((left, right) => left.newStart - right.newStart);
  for (let index = 0; index < POOL_PROJECTION_DELTAS.length; index += 1) {
    const change = ordered[index];
    const expected = POOL_PROJECTION_DELTAS[index];
    if (change.newStart !== expected.line) {
      throw new Error("database projection incomplete or extra range set");
    }
    if (
      JSON.stringify(change.oldLines) !== JSON.stringify(expected.oldLines) ||
      JSON.stringify(change.newLines) !== JSON.stringify(expected.newLines)
    ) {
      throw new Error("database projection mixed or renamed delta");
    }
  }
  const newContents = ordered[0].newContents;
  const oldContents = ordered[0].oldContents;
  if (ordered.some((change) =>
    change.newContents !== newContents || change.oldContents !== oldContents)) {
    throw new Error("database projection mixed source snapshots");
  }
  let reconstructedOld = newContents;
  for (const delta of [...POOL_PROJECTION_DELTAS].reverse()) {
    const next = `${delta.newLines.join("\n")}\n`;
    const previous = delta.oldLines.length === 0
      ? ""
      : `${delta.oldLines.join("\n")}\n`;
    const matches = reconstructedOld.split(next).length - 1;
    if (matches !== 1) {
      throw new Error("database projection missing, duplicate, or extra delta");
    }
    reconstructedOld = reconstructedOld.replace(next, previous);
  }
  if (reconstructedOld !== oldContents) {
    throw new Error("database projection mixed or extra edit");
  }

  const parsed = parseModule(POOL_PROJECTION_SOURCE, newContents);
  exactNamedInterfaceProperty(parsed, "SeatPoolCountsSnapshot", "effectiveFrom");
  exactNamedInterfaceProperty(parsed, "SeatPoolRow", "effective_from");
  const functions = parsed.statements.filter((node) =>
    ts.isFunctionDeclaration(node) && node.name?.text === "listCurrentSeatPoolCounts");
  if (functions.length !== 1 || !functions[0].body) {
    throw new Error("database projection wrong scope: listCurrentSeatPoolCounts");
  }
  let queryTemplate;
  let mappedPropertyCount = 0;
  const visit = (node) => {
    if (
      ts.isCallExpression(node) && ts.isPropertyAccessExpression(node.expression) &&
      node.expression.name.text === "query" && node.arguments.length >= 1
    ) {
      if (queryTemplate) throw new Error("database projection extra query in function scope");
      queryTemplate = node.arguments[0];
    }
    if (
      ts.isPropertyAssignment(node) && ts.isIdentifier(node.name) &&
      node.name.text === "effectiveFrom"
    ) {
      mappedPropertyCount += 1;
      if (
        !ts.isPropertyAccessExpression(node.initializer) ||
        !ts.isIdentifier(node.initializer.expression) ||
        node.initializer.expression.text !== "row" ||
        node.initializer.name.text !== "effective_from"
      ) {
        throw new Error("database projection row mapping wrong or has a default");
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(functions[0].body);
  if (mappedPropertyCount !== 1) {
    throw new Error("database projection row mapping missing or duplicate");
  }
  if (!queryTemplate || !ts.isNoSubstitutionTemplateLiteral(queryTemplate)) {
    throw new Error("database projection interpolation or non-static SQL");
  }
  const sqlText = queryTemplate.text;
  const requireOnce = (fragment, fault) => {
    if (sqlText.split(fragment).length - 1 !== 1) {
      throw new Error(`database projection ${fault}`);
    }
  };
  requireOnce(
    "capacity.effective_from::text AS effective_from",
    "outer projection removed, renamed, cast, or duplicated",
  );
  requireOnce(
    "vac.license_type_id, vac.purchased_qty, vac.effective_from",
    "lateral field removed, reordered, or duplicated",
  );
  requireOnce(
    "SELECT DISTINCT ON (vac.license_type_id)",
    "DISTINCT pairing removed or duplicated",
  );
  requireOnce(
    "ORDER BY vac.license_type_id, vac.effective_from DESC,\n                vac.created_at DESC, vac.id DESC",
    "ORDER pairing removed, changed, or duplicated",
  );

  return {
    faultIds: [
      "outer-projection-removed-or-renamed",
      "lateral-field-removed",
      "row-mapping-wrong",
      "operating-date-input-replaced",
      "operating-date-constant",
    ],
    ranges: ordered.map((change) =>
      `${change.source}:${change.newStart}-${change.newStart + change.newLines.length - 1}`),
    reason: "verification-only:database-projection-bundle",
    source: POOL_PROJECTION_SOURCE,
  };
}

const PAGE_WIRING_SPECS = {
  "apps/web/src/app/(authenticated)/cupos/page.tsx": {
    component: "PoolCards",
    deltas: [
      {
        line: 4,
        oldLines: ['import { PoolCards, type PoolCardsLabels } from "@/components/pools/pool-cards";'],
        newLines: ['import { PoolCards } from "@/components/pools/pool-cards";'],
      },
      {
        line: 9,
        oldLines: [],
        newLines: ['import { createPoolCardsLabels } from "./labels";', ""],
      },
      {
        line: 23,
        oldLines: [
          "  const labels: PoolCardsLabels = {",
          '    assigned: t("assigned"),',
          '    attention: t("attention"),',
          '    automated: t("automated"),',
          '    available: t("available"),',
          '    discrepancy: t("discrepancy"),',
          '    emptyDescription: t("emptyDescription"),',
          '    emptyTitle: t("emptyTitle"),',
          '    floor: t("floor"),',
          '    mode: t("mode"),',
          '    orchestration: t("orchestration"),',
          '    pending: t("pending"),',
          '    purchased: t("purchased"),',
          '    renewal: t("renewal"),',
          "  };",
        ],
        newLines: ["  const labels = createPoolCardsLabels(t);"],
      },
    ],
    faultIds: [
      "missing-or-wrong-label-import",
      "wrong-translator-argument",
      "wrong-assigned-label-identifier",
      "wrong-labels-prop",
    ],
    imports: ["createPoolCardsLabels"],
  },
  "apps/web/src/app/(authenticated)/excepciones/page.tsx": {
    component: "BlockedRequestsTable",
    deltas: [
      {
        line: 12,
        oldLines: [],
        newLines: [
          "import {",
          "  createBlockedRequestsLabels,",
          "  toBlockedRequestItem,",
          '} from "./labels";',
          "",
        ],
      },
      {
        line: 124,
        oldLines: [
          "            items={blocked.items.map((request) => ({",
          "              companyName: request.companyName,",
          "              daysBlocked: request.daysBlocked,",
          "              id: request.id,",
          "              licenseTypeName: request.licenseTypeName,",
          "              neededBy: request.neededBy,",
          "              personName: request.personName,",
          "              requestNo: request.requestNo,",
          "              vendorAccountName: request.vendorAccountName,",
          "            }))}",
          "            labels={{",
          '              company: t("blocked.company"),',
          '              daysBlocked: t("blocked.daysBlocked"),',
          '              empty: t("blocked.empty"),',
          '              neededBy: t("blocked.neededBy"),',
          '              noDate: t("blocked.noDate"),',
          '              organization: t("blocked.organization"),',
          '              request: t("blocked.request"),',
          '              status: t("blocked.status"),',
          '              statusBlocked: t("blocked.statusBlocked"),',
          '              viewPools: t("blocked.viewPools"),',
          "            }}",
        ],
        newLines: [
          "            items={blocked.items.map(toBlockedRequestItem)}",
          "            labels={createBlockedRequestsLabels(t)}",
        ],
      },
    ],
    faultIds: [
      "missing-or-wrong-composition-import",
      "wrong-request-adapter",
      "wrong-translator-argument",
      "wrong-items-or-labels-prop",
    ],
    imports: ["createBlockedRequestsLabels", "toBlockedRequestItem"],
  },
};

const PAGE_WIRING_SOURCES = new Set(Object.keys(PAGE_WIRING_SPECS));

function exactNamedImports(parsed, expectedNames) {
  const declarations = moduleDeclarations(parsed).filter((node) =>
    ts.isImportDeclaration(node) && node.moduleSpecifier.text === "./labels");
  if (declarations.length !== 1) {
    throw new Error("page wiring missing, wrong, or duplicate labels import");
  }
  const clause = declarations[0].importClause;
  if (
    !clause || clause.name || !clause.namedBindings ||
    !ts.isNamedImports(clause.namedBindings)
  ) {
    throw new Error("page wiring labels import must use exact named imports");
  }
  const names = clause.namedBindings.elements.map((element) => element.name.text).sort();
  if (JSON.stringify(names) !== JSON.stringify([...expectedNames].sort())) {
    throw new Error("page wiring labels import has missing, renamed, or extra bindings");
  }
}

function jsxAttribute(element, name) {
  const attributes = element.attributes.properties.filter((property) =>
    ts.isJsxAttribute(property) && property.name.getText() === name);
  if (attributes.length !== 1 || !attributes[0].initializer ||
      !ts.isJsxExpression(attributes[0].initializer) ||
      !attributes[0].initializer.expression) {
    throw new Error(`page wiring ${name} prop missing, duplicate, or non-expression`);
  }
  return attributes[0].initializer.expression;
}

export function classifyPageWiringBundle(changes) {
  if (!Array.isArray(changes) || changes.length === 0) {
    throw new Error("page wiring incomplete bundle");
  }
  const sources = new Set(changes.map((change) => change.source));
  if (sources.size !== 1) throw new Error("page wiring bundle must be file-specific");
  const source = [...sources][0];
  const spec = PAGE_WIRING_SPECS[source];
  if (!spec) throw new Error("page wiring wrong scope");
  if (changes.length !== spec.deltas.length) {
    throw new Error("page wiring incomplete or extra hunk set");
  }
  if (new Set(changes.map((change) => change.newStart)).size !== changes.length) {
    throw new Error("page wiring duplicate hunk");
  }
  const ordered = [...changes].sort((left, right) => left.newStart - right.newStart);
  for (let index = 0; index < spec.deltas.length; index += 1) {
    const change = ordered[index];
    const expected = spec.deltas[index];
    if (
      change.newStart !== expected.line ||
      JSON.stringify(change.oldLines) !== JSON.stringify(expected.oldLines) ||
      JSON.stringify(change.newLines) !== JSON.stringify(expected.newLines)
    ) {
      throw new Error("page wiring mixed, renamed, or unexpected hunk");
    }
  }
  const newContents = ordered[0].newContents;
  const oldContents = ordered[0].oldContents;
  if (ordered.some((change) =>
    change.newContents !== newContents || change.oldContents !== oldContents)) {
    throw new Error("page wiring mixed source snapshots");
  }
  if (/Stryker\s+(disable|restore)/.test(newContents)) {
    throw new Error("page wiring mutation suppression is forbidden");
  }
  let reconstructedOld = newContents;
  for (const delta of [...spec.deltas].reverse()) {
    const next = `${delta.newLines.join("\n")}\n`;
    const previous = delta.oldLines.length === 0
      ? ""
      : `${delta.oldLines.join("\n")}\n`;
    if (reconstructedOld.split(next).length - 1 !== 1) {
      throw new Error("page wiring missing, duplicate, or extra delta");
    }
    reconstructedOld = reconstructedOld.replace(next, previous);
  }
  if (reconstructedOld !== oldContents) {
    throw new Error("page wiring mixed or extra edit");
  }

  const parsed = parseModule(source, newContents);
  exactNamedImports(parsed, spec.imports);
  const defaults = parsed.statements.filter((node) =>
    ts.isFunctionDeclaration(node) && node.modifiers?.some((modifier) =>
      modifier.kind === ts.SyntaxKind.DefaultKeyword));
  if (defaults.length !== 1 || !defaults[0].body) {
    throw new Error("page wiring must contain one default page function");
  }
  const elements = [];
  const visit = (node) => {
    if (
      ts.isJsxSelfClosingElement(node) &&
      ts.isIdentifier(node.tagName) && node.tagName.text === spec.component
    ) elements.push(node);
    ts.forEachChild(node, visit);
  };
  visit(defaults[0].body);
  if (elements.length !== 1) {
    throw new Error(`page wiring must contain one ${spec.component}`);
  }
  const element = elements[0];
  if (source.includes("/cupos/")) {
    const declarations = [];
    const findLabels = (node) => {
      if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) &&
          node.name.text === "labels") declarations.push(node);
      ts.forEachChild(node, findLabels);
    };
    findLabels(defaults[0].body);
    const initializer = declarations[0]?.initializer;
    if (
      declarations.length !== 1 || !initializer || !ts.isCallExpression(initializer) ||
      !ts.isIdentifier(initializer.expression) ||
      initializer.expression.text !== "createPoolCardsLabels" ||
      initializer.arguments.length !== 1 || !ts.isIdentifier(initializer.arguments[0]) ||
      initializer.arguments[0].text !== "t"
    ) throw new Error("page wiring wrong translator call or assigned identifier");
    const labels = jsxAttribute(element, "labels");
    const items = jsxAttribute(element, "items");
    if (!ts.isIdentifier(labels) || labels.text !== "labels" ||
        !ts.isIdentifier(items) || items.text !== "items") {
      throw new Error("page wiring wrong PoolCards labels or items prop");
    }
  } else {
    const items = jsxAttribute(element, "items");
    const labels = jsxAttribute(element, "labels");
    const itemsText = items.getText(parsed);
    const labelsText = labels.getText(parsed);
    if (itemsText !== "blocked.items.map(toBlockedRequestItem)") {
      throw new Error("page wiring wrong request adapter or items prop");
    }
    if (labelsText !== "createBlockedRequestsLabels(t)") {
      throw new Error("page wiring wrong translator argument or labels prop");
    }
  }
  return {
    faultIds: spec.faultIds,
    ranges: ordered.map((change) =>
      `${change.source}:${change.newStart}-${change.newStart + change.newLines.length - 1}`),
    reason: "verification-only:page-wiring-bundle",
    source,
  };
}

const EXACT_FRAMEWORK_ADAPTERS = {
  "apps/web/src/app/(authenticated)/organizaciones/page.tsx": {
    sha256: "23f45735460082b1f28e52da675d060d2996fbfe566ac27db6db60d75e6f99fc",
  },
  "apps/web/src/app/(authenticated)/organizaciones/[vendorAccountId]/page.tsx": {
    sha256: "5394f1abbd72a39d45581fce4f41a4884d12cb1678b20512deddf025c11cfcc9",
  },
};

const EXACT_FRAMEWORK_ADAPTER_SOURCES = new Set(Object.keys(EXACT_FRAMEWORK_ADAPTERS));

/**
 * Audit the two Next.js composition roots whose remaining code solely invokes
 * framework/application seams. Business decisions live in scored loaders; the
 * detail root may only dispatch the already-scored `not-found` outcome.
 */
export function classifyExactFrameworkAdapter(source, contents, requestedRanges = []) {
  const spec = EXACT_FRAMEWORK_ADAPTERS[source];
  if (!spec) throw new Error("exact framework adapter wrong scope");
  if (/Stryker\s+(disable|restore)/.test(contents)) {
    throw new Error("exact framework adapter mutation suppression is forbidden");
  }
  if (sha256(contents) !== spec.sha256) throw new Error("exact framework adapter changed");
  for (const target of requestedRanges) {
    const range = rangeParts(target);
    if (range.source !== source || range.start < 1 || range.end > lineCount(contents)) {
      throw new Error("exact framework adapter range escapes source");
    }
  }
  return {
    ranges: requestedRanges.map((target) => ({ target, reason: "exact-source-hash" })),
    reason: "verification-only:exact-framework-adapter",
    source,
    verifiedMutationRanges: [...requestedRanges],
  };
}

export function partitionExactFrameworkAdapterTargets(targets, sourceContents) {
  const adapter = targets.filter((target) =>
    EXACT_FRAMEWORK_ADAPTER_SOURCES.has(rangeParts(target).source));
  for (const source of mutationSourceFiles(adapter)) {
    classifyExactFrameworkAdapter(
      source,
      sourceContents(source),
      adapter.filter((target) => rangeParts(target).source === source),
    );
  }
  return { adapter, routed: targets.filter((target) => !adapter.includes(target)) };
}

export function requireNonzeroMutationReport(report, shardId) {
  const mutants = mutationReportMutants(report);
  if (mutants.length === 0) {
    throw new Error(`scored mutation shard ${shardId} instrumented zero mutants`);
  }
  const testable = mutants.filter((mutant) => mutant.status !== "Ignored");
  if (testable.length === 0) {
    throw new Error(`scored mutation shard ${shardId} has zero testable mutants`);
  }
  return testable.length;
}

export function validateScoredMutationReport(report, breakThreshold, shardId) {
  const mutants = mutationReportMutants(report);
  requireNonzeroMutationReport(report, shardId);
  const terminal = new Set([
    "Killed", "Survived", "NoCoverage", "CompileError", "RuntimeError", "Timeout", "Ignored",
  ]);
  for (const mutant of mutants) {
    if (!terminal.has(mutant.status)) {
      throw new Error(`non-terminal or unknown mutant status in ${shardId}`);
    }
  }
  const valid = mutants.filter((mutant) =>
    ["Killed", "Timeout", "Survived", "NoCoverage"].includes(mutant.status));
  if (valid.length === 0) throw new Error(`scored mutation shard ${shardId} has zero valid mutants`);
  const detected = valid.filter((mutant) => ["Killed", "Timeout"].includes(mutant.status)).length;
  const score = (detected / valid.length) * 100;
  if (!Number.isFinite(breakThreshold) || breakThreshold < 0 || breakThreshold > 100) {
    throw new Error(`invalid mutation break threshold for ${shardId}`);
  }
  if (score < breakThreshold) {
    throw new Error(`mutation score ${score.toFixed(2)} is below break threshold ${breakThreshold}: ${shardId}`);
  }
  return score;
}

export function requireNonzeroStaticShard(kind, mutantCount, shardId) {
  if (SCORED_STATIC_KINDS.has(kind) && mutantCount === 0) {
    throw new Error(`scored mutation shard ${shardId} instrumented zero mutants`);
  }
}

function mutationReportMutants(report) {
  return report?.files && typeof report.files === "object"
    ? Object.values(report.files).flatMap((file) =>
        Array.isArray(file?.mutants) ? file.mutants : [])
    : [];
}

export function verificationAuditsForReport(
  report,
  shard,
  allHunks,
  classify = classifyVerificationOnlyHunk,
) {
  if (mutationReportMutants(report).length > 0) {
    throw new Error(`nonzero mutation shard ${shard.id} cannot downgrade to verification-only`);
  }
  if (shard.sources.includes(POOL_PROJECTION_SOURCE)) {
    if (shard.sources.length !== 1) {
      throw new Error("database projection bundle cannot share a verification-only shard");
    }
    const audit = classifyPoolSnapshotProjectionBundle(
      allHunks.filter((change) => change.source === POOL_PROJECTION_SOURCE),
    );
    if (
      JSON.stringify([...audit.ranges].sort()) !==
      JSON.stringify([...shard.mutate].sort())
    ) {
      throw new Error("database projection incomplete or extra mutation range set");
    }
    return [audit];
  }
  const vendorPageSources = shard.sources.filter((source) =>
    EXACT_FRAMEWORK_ADAPTER_SOURCES.has(source));
  if (vendorPageSources.length > 0) {
    if (vendorPageSources.length !== shard.sources.length) {
      throw new Error("exact framework adapter cannot share a verification-only shard");
    }
    return vendorPageSources.map((source) => classifyExactFrameworkAdapter(
      source,
      readFileSync(source, "utf8"),
      shard.mutate.filter((range) => rangeParts(range).source === source),
    ));
  }
  const pageSources = shard.sources.filter((source) => PAGE_WIRING_SOURCES.has(source));
  if (pageSources.length > 0) {
    if (shard.sources.length !== 1 || pageSources.length !== 1) {
      throw new Error("page wiring bundle cannot share a verification-only shard");
    }
    const audit = classifyPageWiringBundle(
      allHunks.filter((change) => change.source === pageSources[0]),
    );
    if (
      JSON.stringify([...audit.ranges].sort()) !==
      JSON.stringify([...shard.mutate].sort())
    ) throw new Error("page wiring incomplete or extra mutation range set");
    return [audit];
  }
  return shard.mutate.map((range) => {
    const change = allHunks.find((candidate) =>
      `${candidate.source}:${candidate.newStart}-${candidate.newStart + candidate.newLines.length - 1}` === range);
    if (!change) throw new Error(`no exact diff hunk for zero-mutant range: ${range}`);
    return classify(change);
  });
}

export function readFreshMutationReport(
  reportPath,
  startedAt,
  fileStat = statSync,
  fileRead = (path) => readFileSync(path, "utf8"),
) {
  let metadata;
  try {
    metadata = fileStat(reportPath);
  } catch {
    throw new Error(`missing mutation report: ${reportPath}`);
  }
  if (metadata.mtimeMs < startedAt) {
    throw new Error(`stale mutation report: ${reportPath}`);
  }
  try {
    return JSON.parse(fileRead(reportPath));
  } catch {
    throw new Error(`malformed mutation report: ${reportPath}`);
  }
}

export function controlledChildEnvironment(environment, runtimeProfile = {}) {
  const allowed = [
    "PATH", "HOME", "USER", "LOGNAME", "SHELL", "TMPDIR", "TMP", "TEMP",
    "LANG", "LC_ALL", "LC_MESSAGES", "TZ", "MIGRATIONS_DIR", "ECUADOR_HOLIDAYS",
  ];
  if (typeof environment.ECUADOR_HOLIDAYS === "string") {
    const holidays = environment.ECUADOR_HOLIDAYS.trim() === ""
      ? [] : environment.ECUADOR_HOLIDAYS.split(",").map((value) => value.trim());
    if (holidays.some((value) => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return true;
      const date = new Date(`${value}T00:00:00.000Z`);
      return Number.isNaN(date.valueOf()) || date.toISOString().slice(0, 10) !== value;
    })) throw new Error("ECUADOR_HOLIDAYS must be empty or a comma-separated ISO date list");
    environment = { ...environment, ECUADOR_HOLIDAYS: holidays.join(",") };
  }
  if (runtimeProfile.databaseDriver === "postgres") {
    const harnesses = String(runtimeProfile.databaseHarness ?? "default").split("-");
    for (const harness of harnesses) {
      if (harness === "default") allowed.push("DATABASE_URL", "DATABASE_ADMIN_URL");
      else {
        const prefix = harness.toUpperCase();
        allowed.push(
          `${prefix}_MUTATION_DATABASE_URL`,
          `${prefix}_MUTATION_DATABASE_ADMIN_URL`,
        );
      }
    }
    allowed.push("DB_DRIVER");
  }
  return Object.fromEntries(allowed
    .filter((key) => typeof environment[key] === "string")
    .map((key) => [key, environment[key]]));
}

export async function createDatabaseShardSandbox(
  environment,
  shardId,
  pgModule,
  { cleanupAttempts = 3 } = {},
) {
  const ownerUrl = environment.DATABASE_ADMIN_URL ?? environment.US017_MUTATION_DATABASE_ADMIN_URL;
  const appUrl = environment.DATABASE_URL ?? environment.US017_MUTATION_DATABASE_URL;
  if (!ownerUrl || !appUrl) throw new Error("database shard sandbox requires owner and app URLs");
  const template = new URL(ownerUrl).pathname.slice(1);
  if (!/^[a-z0-9_]+$/.test(template)) throw new Error("database shard template name is invalid");
  const slug = shardId.replace(/[^a-z0-9]/gi, "_").slice(0, 40).toLowerCase();
  const databaseName = `ledger_mutation_${slug}_${randomUUID().replaceAll("-", "")}`;
  const maintenanceUrl = new URL(ownerUrl);
  maintenanceUrl.pathname = "/postgres";
  const Client = pgModule.default?.Client ?? pgModule.Client;
  const maintenance = new Client({ connectionString: maintenanceUrl.toString() });
  await maintenance.connect();
  try {
    await maintenance.query(
      `CREATE DATABASE "${databaseName}" WITH TEMPLATE "${template}" OWNER ledger_owner`,
    );
  } finally {
    await maintenance.end();
  }
  const sandboxUrl = (source) => {
    const url = new URL(source);
    url.pathname = `/${databaseName}`;
    return url.toString();
  };
  const sandboxEnvironment = { ...environment };
  for (const key of Object.keys(sandboxEnvironment)) {
    if (key === "DATABASE_ADMIN_URL" || /^US\d+_MUTATION_DATABASE_ADMIN_URL$/.test(key)) {
      sandboxEnvironment[key] = sandboxUrl(ownerUrl);
    } else if (key === "DATABASE_URL" || /^US\d+_MUTATION_DATABASE_URL$/.test(key)) {
      sandboxEnvironment[key] = sandboxUrl(appUrl);
    }
  }
  if (!Number.isInteger(cleanupAttempts) || cleanupAttempts < 1) {
    throw new Error("database sandbox cleanupAttempts must be a positive integer");
  }
  let cleaned = false;
  let cleanupPromise = null;
  const cleanupOnce = async () => {
    const client = new Client({ connectionString: maintenanceUrl.toString() });
    await client.connect();
    try {
      await client.query(
        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()",
        [databaseName],
      );
      await client.query(`DROP DATABASE IF EXISTS "${databaseName}"`);
    } finally {
      await client.end();
    }
  };
  return {
    databaseName,
    environment: sandboxEnvironment,
    async cleanup() {
      if (cleaned) return;
      if (cleanupPromise) return cleanupPromise;
      cleanupPromise = (async () => {
        let lastError;
        for (let attempt = 1; attempt <= cleanupAttempts; attempt += 1) {
          try {
            await cleanupOnce();
            cleaned = true;
            return;
          } catch (error) {
            lastError = error;
          }
        }
        throw new Error(
          `database sandbox cleanup exhausted ${cleanupAttempts} attempt(s) for ${databaseName}`,
          { cause: lastError },
        );
      })();
      try {
        return await cleanupPromise;
      } finally {
        if (!cleaned) cleanupPromise = null;
      }
    },
  };
}

export async function exitAfterDatabaseCleanup({
  cleanup,
  exit,
  interruptedExitCode,
  reportFailure,
}) {
  try {
    await cleanup();
  } catch (error) {
    reportFailure(error.message);
    exit(1);
    return;
  }
  exit(interruptedExitCode);
}

export function runVerificationCommands(commands, run = spawnSync, environment = {}) {
  if (commands.length === 0) throw new Error("verification-only result has no commands");
  for (const [command, args] of commands) {
    const result = run(command, args, { stdio: "inherit", env: environment });
    if (result.status !== 0) {
      throw new Error(`verification command failed: ${command} ${args.join(" ")}`);
    }
  }
  return commands.length;
}

export function projectionEvidencePathForShard(shard) {
  return shard.sources.includes(POOL_PROJECTION_SOURCE)
    ? join(
        GENERATED_SHARD_DIR,
        shard.jsonReportPath
          ? `${basename(shard.jsonReportPath, ".json")}-projection.json`
          : `${shard.id}-${(shard.evidenceKey ?? shard.provenance?.runHash).slice(0, 12)}-projection.json`,
      )
    : undefined;
}

export function verificationCommandsForSources(sources, testFiles, context = {}) {
  const commands = [];
  if (sources.includes(POOL_PROJECTION_SOURCE)) {
    if (!context.evidencePath) {
      throw new Error("database projection verification requires an evidence path");
    }
    commands.push([
      "node",
      ["scripts/verify-pool-snapshot-projection.mjs", context.evidencePath],
    ]);
  }
  if (sources.some((source) => PAGE_WIRING_SOURCES.has(source))) {
    if (sources.length !== 1) {
      throw new Error("page wiring verification must be file-specific");
    }
    commands.push([
      "./apps/web/node_modules/.bin/vitest",
      ["run", "--config", "vitest.mutation.config.mjs", ...testFiles],
    ]);
    commands.push(["pnpm", ["--filter", "smp-web", "type-check"]]);
    commands.push(["pnpm", ["--filter", "smp-web", "build"]]);
  }
  if (sources.some((source) => EXACT_FRAMEWORK_ADAPTER_SOURCES.has(source))) {
    if (!sources.every((source) => EXACT_FRAMEWORK_ADAPTER_SOURCES.has(source))) {
      throw new Error("exact framework adapter verification must be isolated");
    }
    commands.push([
      "./apps/web/node_modules/.bin/vitest",
      ["run", "--config", "vitest.mutation.config.mjs", ...testFiles],
    ]);
    commands.push(["pnpm", ["--filter", "smp-web", "type-check"]]);
  }
  if (sources.some((source) => source.startsWith("packages/connectors/"))) {
    commands.push(["node", ["--eval", 'require("node:fs").rmSync("packages/connectors/dist/module-wiring", { recursive: true, force: true })']]);
    commands.push(["pnpm", [
      "--filter", "@smp/connectors", "exec", "tsc",
      "--outDir", "dist/module-wiring", "--noEmit", "false",
      "--declaration", "false", "--composite", "false",
    ]]);
    commands.push(["node", ["--input-type=module", "--eval", [
      'const root = "./packages/connectors/dist/module-wiring/";',
      'const publicApi = await import(`${root}index.js`);',
      'const modules = await Promise.all(["contracts.js", "dispatch.js", "action-planner.js"].map((file) => import(`${root}${file}`)));',
      'const expected = new Map(); for (const module of modules) for (const name of Object.keys(module)) {',
      '  if (expected.has(name) && expected.get(name) !== module[name]) throw new Error(`conflicting connector export: ${name}`);',
      '  expected.set(name, module[name]);',
      '}',
      'if (JSON.stringify(Object.keys(publicApi).sort()) !== JSON.stringify([...expected.keys()].sort()))',
      '  throw new Error("connector public exports differ from exact module union");',
      'for (const [name, value] of expected) if (publicApi[name] !== value) throw new Error(`connector export identity mismatch: ${name}`);',
      'try { await import("./packages/connectors/dist/module-wiring/contracts"); throw new Error("extensionless negative control resolved"); }',
      'catch (error) { if (error.code !== "ERR_MODULE_NOT_FOUND") throw error; }',
    ].join(" ")]]);
  }
  if (sources.some((source) => source.startsWith("packages/contracts/"))) {
    commands.push(["pnpm", ["--filter", "@smp/contracts", "build"]]);
    commands.push(["node", ["--input-type=module", "--eval", [
      'import { readFileSync } from "node:fs";',
      'import { verifyContractsBarrelSource } from "./scripts/mutation-scope.mjs";',
      'const source = readFileSync("packages/contracts/src/index.ts", "utf8");',
      'verifyContractsBarrelSource(source);',
      'for (const name of ["capacity", "identity-access"]) {',
      '  const declaration = `export * from "./${name}";`;',
      '  for (const wrong of [source.replace(`${declaration}\\n`, ""), source.replace(declaration, `export * from "./wrong-${name}";`)]) {',
      '    let rejected = false; try { verifyContractsBarrelSource(wrong); } catch { rejected = true; }',
      '    if (!rejected) throw new Error(`contracts barrel negative control did not fail: ${name}`);',
      '  }',
      '}',
    ].join(" ")]]);
  }
  if (
    !sources.includes(POOL_PROJECTION_SOURCE) &&
    !sources.some((source) => PAGE_WIRING_SOURCES.has(source))
  ) {
    commands.push([
      "./apps/web/node_modules/.bin/vitest",
      ["run", "--config", "vitest.mutation.config.mjs", ...testFiles],
    ]);
  }
  return commands;
}

export function verifyContractsBarrelSource(
  contents,
  fileExists = existsSync,
  source = "packages/contracts/src/index.ts",
) {
  const parsed = parseModule(source, contents);
  const expected = ["./capacity", "./identity-access"];
  const resolved = [];
  for (const specifier of expected) {
    const exports = moduleDeclarations(parsed).filter((node) =>
      ts.isExportDeclaration(node) && node.exportClause === undefined &&
      !node.isTypeOnly && node.moduleSpecifier.text === specifier);
    if (exports.length !== 1) {
      throw new Error(
        `contracts barrel must contain exactly one ${specifier} export; found ${exports.length}`,
      );
    }
    assertNoImportAttributes(exports[0]);
    resolved.push(relativeModuleTarget(source, specifier, fileExists));
  }
  return resolved;
}

function mutationTargets(base, sourceFiles) {
  if (sourceFiles.length === 0) return [];
  const mergeBase = mergeBaseFor(base);
  const patch = git([
    "-c", "core.quotepath=false", "diff", "--no-ext-diff", "--no-renames",
    "--unified=0", "--diff-filter=ACMR", mergeBase, "--", ...sourceFiles,
  ]);
  const untrackedPaths = new Set(
    git(["ls-files", "--others", "--exclude-standard"])
      .split("\n")
      .filter(Boolean),
  );
  const untracked = new Map(
    sourceFiles
      .filter((path) => untrackedPaths.has(path))
      .map((path) => [path, lineCount(readFileSync(path, "utf8"))]),
  );
  return mutationTargetsFromPatch(patch, untracked);
}

function mutationHunks(base, sourceFiles) {
  if (sourceFiles.length === 0) return [];
  const mergeBase = mergeBaseFor(base);
  const patch = git([
    "-c", "core.quotepath=false", "diff", "--no-ext-diff", "--no-renames",
    "--unified=0", "--diff-filter=ACMR", mergeBase, "--", ...sourceFiles,
  ]);
  const cache = new Map();
  const contentsForSource = (source) => {
    if (!cache.has(source)) {
      let oldContents = "";
      try {
        oldContents = execFileSync("git", ["show", `${mergeBase}:${source}`], {
          encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
        });
      } catch { /* added file */ }
      cache.set(source, { oldContents, newContents: readFileSync(source, "utf8") });
    }
    return cache.get(source);
  };
  return mutationHunksFromPatch(patch, contentsForSource);
}

const TEST_FILE = /\.(test|spec)\.(ts|tsx)$/;
const ADJACENT_TEST_SUFFIXES = [
  ".test.ts",
  ".test.tsx",
  ".integration.test.ts",
  ".integration.test.tsx",
  ".pact.test.ts",
  ".spec.ts",
  ".spec.tsx",
];

// Thin composition roots and config/barrel files deliberately do not have an
// adjacent test. Their behavior is owned by these contract tests. Keeping the
// exceptional routes explicit prevents a changed source from silently riding
// along merely because some unrelated story test also changed.
export const DIRECT_TEST_ROUTES = {
  "apps/web/src/app/(authenticated)/organizaciones/[vendorAccountId]/page.tsx": [
    "apps/web/src/app/(authenticated)/organizaciones/vendor-account-page-boundaries.test.ts",
    "apps/web/src/modules/vendor-catalog/vendor-account-page-loaders.test.ts",
  ],
  "apps/web/src/app/(authenticated)/organizaciones/error.tsx": [
    "apps/web/src/app/(authenticated)/organizaciones/vendor-account-page-boundaries.test.ts",
  ],
  "apps/web/src/app/(authenticated)/organizaciones/loading.tsx": [
    "apps/web/src/app/(authenticated)/organizaciones/vendor-account-page-boundaries.test.ts",
  ],
  "apps/web/src/app/(authenticated)/organizaciones/page.tsx": [
    "apps/web/src/app/(authenticated)/organizaciones/vendor-account-page-boundaries.test.ts",
    "apps/web/src/modules/vendor-catalog/vendor-account-page-loaders.test.ts",
  ],
  "apps/web/src/components/vendor-accounts/capability-card.tsx": [
    "apps/web/src/components/vendor-accounts/vendor-account-detail.test.tsx",
  ],
  "apps/web/src/components/vendor-accounts/vendor-account-dialog.tsx": [
    "apps/web/src/components/vendor-accounts/vendor-accounts.test.tsx",
    "apps/web/src/components/vendor-accounts/vendor-accounts.integration.test.tsx",
  ],
  "apps/web/src/components/vendor-accounts/vendor-account-form.tsx": [
    "apps/web/src/components/vendor-accounts/vendor-accounts.test.tsx",
    "apps/web/src/components/vendor-accounts/vendor-accounts.integration.test.tsx",
  ],
  "apps/web/src/components/vendor-accounts/vendor-account-tabs.tsx": [
    "apps/web/src/components/vendor-accounts/vendor-account-detail.test.tsx",
    "apps/web/src/components/vendor-accounts/vendor-accounts.integration.test.tsx",
  ],
  "apps/web/src/components/vendor-accounts/vendor-accounts-table.tsx": [
    "apps/web/src/components/vendor-accounts/vendor-accounts.test.tsx",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-vendor-accounts-operations.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-vendor-accounts.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-vendor-accounts-server-actions-factory.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-vendor-accounts.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/vendor-account-route-access.ts": [
    "apps/web/src/app/(authenticated)/organizaciones/vendor-account-page-boundaries.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/production-vendor-account-repository.ts": [
    "apps/web/src/modules/vendor-catalog/vendor-account-repository.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/vendor-account-service.ts": [
    "apps/web/src/modules/vendor-catalog/vendor-account-repository.integration.test.ts",
  ],
  "apps/web/src/app/(authenticated)/cupos/labels.ts": [
    "apps/web/src/app/(authenticated)/cupos/labels.test.ts",
  ],
  "apps/web/src/app/(authenticated)/excepciones/labels.ts": [
    "apps/web/src/app/(authenticated)/excepciones/labels.test.ts",
  ],
  "apps/web/src/app/(authenticated)/usuarios/page.tsx": [
    "apps/web/src/components/users/users-roles-panel.test.tsx",
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/actions/manage-users.ts": [
    "apps/web/src/components/users/users-roles-panel.test.tsx",
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/provider-operation-repository.ts": [
    "apps/web/src/modules/identity-access/repository.integration.test.ts",
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/server-authorization.ts": [
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/identity-access/users-roles-page.tsx": [
    "apps/web/src/modules/identity-access/user-admin-service.integration.test.ts",
  ],
  "apps/web/src/modules/request-workflow/approval/repository.ts": [
    "apps/web/src/modules/request-workflow/approval-repository.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/capacity-recovery-outbox.ts": [
    "apps/web/src/modules/vendor-catalog/capacity-service.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/no-seat-observation.ts": [
    "apps/web/src/modules/vendor-catalog/capacity-service.integration.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-capacity-operations.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-capacity.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-capacity.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-capacity.test.ts",
  ],
  "apps/web/src/modules/vendor-catalog/actions/manage-capacity-server-actions-factory.ts": [
    "apps/web/src/modules/vendor-catalog/actions/manage-capacity.test.ts",
  ],
  "apps/web/vitest.config.ts": [
    "apps/web/next.config.test.ts",
    "apps/web/src/modules/identity-access/keycloak-admin.pact.test.ts",
  ],
  "packages/contracts/src/index.ts": [
    "packages/contracts/src/capacity.test.ts",
    "packages/contracts/src/identity-access.test.ts",
  ],
  "packages/connectors/src/index.ts": [
    "packages/connectors/src/action-planner.test.ts",
    "packages/connectors/src/dispatch.test.ts",
  ],
  "packages/db/src/provisioning-routing.ts": [
    "packages/db/src/provisioning-routing.test.ts",
  ],
  "packages/db/src/schema.ts": [
    "packages/db/src/schema.test.ts",
  ],
  "scripts/probes/anthropic/vitest.contract.config.ts": [
    "apps/web/src/modules/identity-access/keycloak-admin.pact.test.ts",
  ],
};

// Static source/schema enforcement tests inspect an uninstrumented application
// tree. Stryker necessarily rewrites that tree before its dry run, so these
// scanners reject the mutation sandbox itself before any mutant can run. They
// remain mandatory in the normal lint/check pipeline.
const MUTATION_INCOMPATIBLE_TESTS = new Set([
  "apps/web/src/modules/audit/audited-actions-enforcement.test.ts",
  "packages/db/src/migration-release.integration.test.ts",
  "packages/db/src/schema-parity.test.ts",
]);

export function mutationCompatibleTestFiles(testFiles) {
  return testFiles.filter((file) => !MUTATION_INCOMPATIBLE_TESTS.has(file));
}

function testsForSource(source, fileExists, directRoutes) {
  const responsible = new Set();
  const stem = source.replace(/\.(ts|tsx)$/, "");
  for (const suffix of ADJACENT_TEST_SUFFIXES) {
    const candidate = `${stem}${suffix}`;
    if (fileExists(candidate)) responsible.add(candidate);
  }
  for (const candidate of directRoutes[source] ?? []) {
    if (fileExists(candidate)) responsible.add(candidate);
  }
  return [...responsible].sort();
}

export function routedTestFiles(changed, mutate, fileExists = existsSync, directRoutes = DIRECT_TEST_ROUTES) {
  const routed = new Set(changed.filter((file) => TEST_FILE.test(file)));
  for (const source of mutate) {
    for (const candidate of testsForSource(source, fileExists, directRoutes)) routed.add(candidate);
  }
  return [...routed].sort();
}

export function requireRoutedTestFiles(changed, mutate, fileExists = existsSync, directRoutes = DIRECT_TEST_ROUTES) {
  for (const source of mutate) {
    if (testsForSource(source, fileExists, directRoutes).length === 0) {
      throw new Error(`mutatable source has no responsible Vitest test route: ${source}`);
    }
  }
  return routedTestFiles(changed, mutate, fileExists, directRoutes);
}

function defaultToolVersions() {
  const packageVersion = (url) => JSON.parse(readFileSync(url, "utf8")).version;
  const rootPackage = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
  return {
    node: process.versions.node,
    pnpm: String(rootPackage.packageManager ?? "pnpm@0.0.0").replace(/^pnpm@/, ""),
    stryker: packageVersion(new URL("../node_modules/@stryker-mutator/core/package.json", import.meta.url)),
    typescript: ts.version,
    vitest: packageVersion(new URL("../apps/web/node_modules/vitest/package.json", import.meta.url)),
  };
}

function localRuntimeProfile() {
  return {
    arch: process.arch,
    locale: Intl.DateTimeFormat().resolvedOptions().locale,
    platform: process.platform,
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  };
}

export function databaseHarnessIdentity(shard, environment = process.env) {
  const adminKeys = Object.keys(environment)
    .filter((key) => /^US\d+_MUTATION_DATABASE_ADMIN_URL$/.test(key) && environment[key])
    .sort();
  const directlyReferenced = adminKeys.filter((key) => {
    const appKey = key.replace("_ADMIN_URL", "_URL");
    return shard?.testFiles.some((test) => existsSync(test)
      && [key, appKey].some((candidate) => readFileSync(test, "utf8").includes(candidate)));
  });
  const selected = directlyReferenced.length === 1
    ? directlyReferenced[0]
    : adminKeys.length === 1 ? adminKeys[0] : null;
  if (directlyReferenced.length > 1 || (!selected && adminKeys.length > 1)) {
    throw new Error("runtime-profile-unavailable");
  }
  return selected ?? "DATABASE_ADMIN_URL";
}

async function defaultRuntimeProfile({ shard, environment = process.env } = {}) {
  const local = localRuntimeProfile();
  if (!shard || !isDatabaseBacked(shard)) return local;
  const [{ verifyMigratedSchema }, { committedMigrations }, pgModule] = await Promise.all([
    import("../packages/db/scripts/verify-schema.mjs"),
    import("../packages/db/scripts/apply-migrations.mjs"),
    import("../packages/db/node_modules/pg/esm/index.mjs"),
  ]);
  const databaseHarness = databaseHarnessIdentity(shard, environment);
  const databaseAdminUrl = environment[databaseHarness];
  const databaseUrlKey = databaseHarness === "DATABASE_ADMIN_URL"
    ? "DATABASE_URL" : databaseHarness.replace("_ADMIN_URL", "_URL");
  const applicationUrl = environment[databaseUrlKey];
  if (!databaseAdminUrl || !applicationUrl) throw new Error("runtime-profile-unavailable");
  const verification = await verifyMigratedSchema({ databaseAdminUrl, applicationUrl });
  const migrations = await committedMigrations(environment.MIGRATIONS_DIR);
  const client = new pgModule.default.Client({
    connectionString: databaseAdminUrl,
    application_name: "ledger-mutation-runtime-profile",
  });
  await client.connect();
  let databaseServerVersion;
  try {
    const version = await client.query("SHOW server_version");
    databaseServerVersion = /\d+(?:\.\d+){0,3}/.exec(
      version.rows[0]?.server_version ?? "",
    )?.[0];
  } finally {
    await client.end();
  }
  const equivalentHarnesses = [
    ...(environment.DATABASE_ADMIN_URL === databaseAdminUrl
        && environment.DATABASE_URL === applicationUrl ? ["default"] : []),
    ...Object.keys(environment)
      .filter((key) => /^US\d+_MUTATION_DATABASE_ADMIN_URL$/.test(key)
        && environment[key] === databaseAdminUrl
        && environment[key.replace("_ADMIN_URL", "_URL")] === applicationUrl)
      .map((key) => key.replace(/_MUTATION_DATABASE_ADMIN_URL$/, "").toLowerCase()),
  ].sort();
  return {
    ...local,
    databaseDriver: "postgres",
    databaseHarness: [...new Set(equivalentHarnesses)].join("-"),
    databaseServerVersion,
    schemaFingerprint: sha256(JSON.stringify({ migrations, verification })),
  };
}

export function isDatabaseBacked(shard) {
  return shard.sources.some((source) => source.startsWith("packages/db/"))
    || shard.sources.some((source) => existsSync(source)
      && /process\.env\.(?:DATABASE_URL|DATABASE_ADMIN_URL)/.test(readFileSync(source, "utf8")))
    || shard.testFiles.some((test) =>
      test.startsWith("packages/db/")
      || (/\.integration\.test\.[cm]?[jt]sx?$/.test(test) && !/\.pact\.test\./.test(test)));
}

function sanitizedRuntimeProfile(profile, databaseBacked) {
  const allowed = databaseBacked
    ? ["platform", "arch", "locale", "timezone", "databaseDriver", "databaseHarness", "databaseServerVersion", "schemaFingerprint"]
    : ["platform", "arch", "locale", "timezone"];
  if (!profile || typeof profile !== "object" || Array.isArray(profile)) {
    throw new Error("runtime-profile-unavailable");
  }
  const result = Object.fromEntries(allowed.map((key) => [key, profile[key]]));
  if (Object.values(result).some((value) => typeof value !== "string" || value.length === 0)) {
    throw new Error("runtime-profile-unavailable");
  }
  if (databaseBacked && !/^[a-f0-9]{64}$/.test(result.schemaFingerprint)) {
    throw new Error("runtime-profile-unavailable");
  }
  return result;
}

export function createCampaignRuntimeProfileResolver(provider, environment = process.env) {
  const databaseProfiles = new Map();
  return async (shard) => {
    if (!isDatabaseBacked(shard)) return Object.freeze({ ...(await provider({ shard, environment })) });
    let identity;
    try {
      identity = databaseHarnessIdentity(shard, environment);
    } catch {
      identity = "ambiguous";
    }
    if (!databaseProfiles.has(identity)) {
      databaseProfiles.set(identity, Promise.resolve()
        .then(() => provider({ shard, environment }))
        .then((profile) => ({
          ...profile,
          databaseHarness: profile?.databaseHarness
            ?? (identity === "DATABASE_ADMIN_URL" ? "default" : identity
              .replace(/_MUTATION_DATABASE_ADMIN_URL$/, "").toLowerCase()),
        })));
    }
    const profile = await databaseProfiles.get(identity);
    return Object.freeze({ ...profile });
  };
}

function rehydrateCachedReport(cachedPath, destination, shard) {
  const report = JSON.parse(readFileSync(cachedPath, "utf8"));
  if (report.config?.mutationIdentity !== contentHash(JSON.stringify(shard.mutate))) {
    throw new Error(`cached mutation config identity mismatch: ${shard.id}`);
  }
  for (const [source, file] of Object.entries(report.files ?? {})) {
    const sourceBytes = readFileSync(source, "utf8");
    if (file.sourceHash !== contentHash(sourceBytes)) {
      throw new Error(`cached mutation source identity mismatch: ${source}`);
    }
    file.source = sourceBytes;
    delete file.sourceHash;
  }
  report.config = {
    mutate: shard.mutate,
    configFile: shard.configPath,
    jsonReporter: { ...report.config?.jsonReporter, fileName: shard.jsonReportPath },
  };
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, `${JSON.stringify(report)}\n`, "utf8");
}

export async function runMutationScope(options = {}) {
  const previousCwd = process.cwd();
  const previousEnvironment = {};
  const signalHandlers = [];
  const activeDatabaseSandboxes = new Set();
  const signalProcess = options.signalProcess ?? process;
  const cleanupFailureReporter = options.cleanupFailureReporter
    ?? ((message) => console.error(`mutation-scope: ${message}`));
  let signalShutdownPromise = null;
  let activeShardProcess = null;
  const cleanupDatabaseSandbox = async (record) => {
    if (record.cleanupPromise) return record.cleanupPromise;
    record.cleanupPromise = (async () => {
      const sandbox = await record.promise;
      let lastError;
      for (let attempt = 1; attempt <= 3; attempt += 1) {
        try {
          await sandbox.cleanup();
          activeDatabaseSandboxes.delete(record);
          return;
        } catch (error) {
          lastError = error;
        }
      }
      throw new Error(
        `database sandbox cleanup exhausted 3 campaign attempt(s) for ${sandbox.databaseName ?? "unknown"}`,
        { cause: lastError },
      );
    })();
    try {
      return await record.cleanupPromise;
    } finally {
      if (activeDatabaseSandboxes.has(record)) record.cleanupPromise = null;
    }
  };
  const cleanupAllDatabaseSandboxes = async () => {
    const results = await Promise.allSettled(
      [...activeDatabaseSandboxes].map(cleanupDatabaseSandbox),
    );
    const failures = results
      .filter((result) => result.status === "rejected")
      .map((result) => result.reason);
    if (failures.length > 0) {
      throw new AggregateError(failures, "database sandbox cleanup failed");
    }
  };
  const environment = options.env ?? process.env;
  if (options.cwd) process.chdir(options.cwd);
  for (const key of ["MUTATION_BASE", "MUTATION_CACHE", "MUTATION_SCOPE_DRY"]) {
    previousEnvironment[key] = process.env[key];
    if (environment[key] === undefined) delete process.env[key];
    else process.env[key] = environment[key];
  }
  try {
  const baseRef = resolveBase();
  const resolvedBase = mergeBaseFor(baseRef);
  const head = git(["rev-parse", "HEAD"]);
  const changed = changedFiles(baseRef);
  const changedSources = mutatable(changed);
  const allMutate = mutationTargets(baseRef, changedSources);
  const allHunks = mutationHunks(baseRef, changedSources);
  const worktreeHash = contentHash(changed.map((path) =>
    `${path}\0${existsSync(path) ? readFileSync(path, "utf8") : "<deleted>"}`).join("\0"));
  const toolVersions = options.toolVersions ?? defaultToolVersions();
  const schemaStaticMutate = allMutate.filter((target) =>
    target.replace(/:\d+-\d+$/, "") === SCHEMA_STATIC_SOURCE);
  const vitestConfigStaticMutate = allMutate.filter((target) =>
    target.replace(/:\d+-\d+$/, "") === VITEST_CONFIG_STATIC_SOURCE);
  if (vitestConfigStaticMutate.length > 0 && (
    vitestConfigStaticMutate.length !== 1 ||
    vitestConfigStaticMutate[0] !== VITEST_CONFIG_STATIC_RANGE
  )) {
    fail(
      `vitest config static shard must contain exactly ${VITEST_CONFIG_STATIC_RANGE}`,
      `found: ${vitestConfigStaticMutate.join(", ")}`,
    );
  }
  const staticMutate = new Set([...schemaStaticMutate, ...vitestConfigStaticMutate]);
  const adapterPartition = partitionExactFrameworkAdapterTargets(
    allMutate,
    (source) => readFileSync(source, "utf8"),
  );
  const vendorAccountPageAdapterMutate = adapterPartition.adapter;
  const vendorAccountPageAdapterSources = mutationSourceFiles(vendorAccountPageAdapterMutate);
  const routedMutate = adapterPartition.routed.filter((target) => !staticMutate.has(target));

  console.log(
    `mutation-scope: base=${resolvedBase} changed=${changed.length} ` +
      `mutatable=${mutationSourceFiles(allMutate).length} ranges=${allMutate.length} ` +
      `schemaStaticRanges=${schemaStaticMutate.length}`,
  );

  if (allMutate.length === 0) {
    console.log("mutation-scope: no mutatable files in diff — nothing to mutate");
    return { manifest: null, performance: null };
  }

  let baseConf = {};
  try {
    baseConf = JSON.parse(readFileSync(BASE_CONFIG, "utf8"));
  } catch {
    fail(`cannot read ${BASE_CONFIG}`, "run from the repository root");
  }

  let routedGroups;
  try {
    routedGroups = groupRoutedMutationTargets(routedMutate, (source) =>
      mutationCompatibleTestFiles(testsForSource(source, existsSync, DIRECT_TEST_ROUTES)));
  } catch (error) {
    fail(error.message, "add a conventional adjacent test or an explicit accountable route");
  }

  const shardSpecs = routedGroups.map((group) => ({ kind: "vitest", ...group }));
  if (vendorAccountPageAdapterMutate.length > 0) {
    const testFiles = [...new Set(vendorAccountPageAdapterSources.flatMap((source) =>
      mutationCompatibleTestFiles(testsForSource(source, existsSync, DIRECT_TEST_ROUTES))))].sort();
    if (testFiles.length === 0) {
      fail("exact framework adapter has no accountable focused tests");
    }
    shardSpecs.push({
      kind: EXACT_FRAMEWORK_ADAPTER_KIND,
      mutate: vendorAccountPageAdapterMutate,
      sources: vendorAccountPageAdapterSources,
      testFiles,
    });
  }
  if (schemaStaticMutate.length > 0) {
    requireRoutedTestFiles(
      changed,
      mutationSourceFiles(schemaStaticMutate),
    );
    shardSpecs.push({
      kind: "schema-static",
      mutate: schemaStaticMutate,
      sources: [SCHEMA_STATIC_SOURCE],
      testFiles: ["packages/db/src/schema.test.ts"],
    });
  }
  if (vitestConfigStaticMutate.length > 0) {
    requireRoutedTestFiles(
      changed,
      [VITEST_CONFIG_STATIC_SOURCE],
    );
    shardSpecs.push({
      kind: "vitest-config-static",
      mutate: vitestConfigStaticMutate,
      sources: [VITEST_CONFIG_STATIC_SOURCE],
      testFiles: ["apps/web/next.config.test.ts"],
    });
  }

  const {
    commandRunner: _commandRunner,
    htmlReporter: _htmlReporter,
    mutate: _baseMutate,
    tempDirName: _tempDirName,
    testFiles: _baseTestFiles,
    vitest: _baseVitest,
    ...sharedBaseConf
  } = baseConf;
  const runSuffix = process.env.MUTATION_SCOPE_DRY === "1"
    ? "dry"
    : (options.runId ?? `${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`);
  const shards = shardSpecs.map((spec) => {
    const digest = createHash("sha256")
      .update([spec.kind, ...spec.sources, ...spec.testFiles, ...spec.mutate].join("\n"))
      .digest("hex")
      .slice(0, 12);
    const id = `${spec.kind}-${digest}`;
    const configPath = join(GENERATED_SHARD_DIR, `${id}-${runSuffix}.json`);
    const tempDirName = join(".tmp", `stryker-${id}-${runSuffix}`);
    const contentHashes = Object.fromEntries(
      spec.sources.map((source) => [source, contentHash(readFileSync(source, "utf8"))]),
    );
    const reportPath = join("reports", "mutation", `${id}-${runSuffix}.html`);
    const jsonReportPath = join("reports", "mutation", `${id}-${runSuffix}.json`);
    const common = {
      ...sharedBaseConf,
      mutate: spec.mutate.map(strykerMutationTarget),
      coverageAnalysis: "off",
      concurrency: 1,
      maxTestRunnerReuse: 1,
      timeoutFactor: 2,
      tempDirName,
      htmlReporter: { fileName: reportPath },
      jsonReporter: { fileName: jsonReportPath },
      reporters: [...new Set([...(sharedBaseConf.reporters ?? []), "json"])],
      thresholds: {
        ...baseConf.thresholds,
        high: 80,
        break: 80,
      },
    };
    const config = SCORED_STATIC_KINDS.has(spec.kind)
      ? {
          ...common,
          testRunner: "command",
          commandRunner: {
            command: spec.kind === "schema-static"
              ? "./apps/web/node_modules/.bin/vitest run --root packages/db --config vitest.config.ts src/schema.test.ts"
              : "./apps/web/node_modules/.bin/vitest run --root apps/web --config vitest.static-contract.config.mjs next.config.test.ts",
          },
        }
      : {
          ...common,
          testRunner: "vitest",
          vitest: {
            ...baseConf.vitest,
            related: false,
            configFile: "vitest.mutation.config.mjs",
          },
          testFiles: spec.testFiles,
        };
    const configText = `${JSON.stringify(config, null, 2)}\n`;
    const configIdentity = normalizeMutationConfigIdentity(config);
    const configIdentityText = `${JSON.stringify(configIdentity, null, 2)}\n`;
    return {
      cacheDecision: "pending",
      classification: "pending",
      config,
      configHash: contentHash(configIdentityText),
      configPath,
      configText,
      contentHashes,
      dependencyHashes: {},
      durationMs: null,
      evidenceKey: null,
      id,
      kind: spec.kind,
      jsonReportPath,
      mutantCount: null,
      mutate: spec.mutate,
      priorDurationMs: null,
      reportHash: null,
      reportPath,
      result: "pending",
      sources: spec.sources,
      tempDirName,
      testFiles: spec.testFiles,
    };
  }).sort((left, right) => left.id.localeCompare(right.id));

  mkdirSync(GENERATED_SHARD_DIR, { recursive: true });
  for (const shard of shards) {
    writeFileSync(shard.configPath, shard.configText, "utf8");
  }
  const manifestFor = () => ({
    provenance: { base: resolvedBase, baseRef, head, worktreeHash },
    shards: shards.map(({ config, configText, ...shard }) => shard),
    toolVersions,
  });
  writeFileSync(
    GENERATED_MANIFEST,
    `${JSON.stringify(manifestFor(), null, 2)}\n`,
    "utf8",
  );
  console.log(`mutation-scope: wrote ${shards.length} shards + ${GENERATED_MANIFEST}`);

  if (process.env.MUTATION_SCOPE_DRY === "1") {
    console.log("mutation-scope: MUTATION_SCOPE_DRY=1 — not running Stryker");
    return { manifest: manifestFor(), performance: null };
  }

  const cacheMode = process.env.MUTATION_CACHE === "off" ? "bypass" : "enabled";
  const performanceRun = createPerformanceRun({
    provenance: {
      campaignKey: sha256(shards.map((shard) => `${shard.id}:${shard.configHash}`).join("\n")),
      head,
      base: resolvedBase,
      baseRef,
    },
    cacheMode,
    machine: options.machine ?? {
      os: `${os.type()} ${os.release()}`,
      arch: os.arch(), logicalCpuCount: os.cpus().length, memoryBytes: os.totalmem(), toolVersions,
    },
    ...(options.performanceOptions ?? {}),
  });
  const persist = () => {
    writeFileSync(GENERATED_MANIFEST, `${JSON.stringify(manifestFor(), null, 2)}\n`, "utf8");
    writePerformanceRecord(process.cwd(), performanceRun);
  };
  if (options.installSignalHandlers !== false) {
    for (const signal of ["SIGINT", "SIGTERM"]) {
      const handler = () => {
        signalShutdownPromise ??= (async () => {
          finishPerformanceRun(performanceRun, "interrupted");
          persist();
          if (activeShardProcess?.pid) {
            try {
              process.kill(-activeShardProcess.pid, signal);
            } catch (error) {
              if (error?.code !== "ESRCH") throw error;
            }
          }
          await exitAfterDatabaseCleanup({
            cleanup: cleanupAllDatabaseSandboxes,
            exit: (code) => signalProcess.exit(code),
            interruptedExitCode: signal === "SIGINT" ? 130 : 143,
            reportFailure: cleanupFailureReporter,
          });
        })();
        return signalShutdownPromise;
      };
      signalProcess.once(signal, handler);
      signalHandlers.push([signal, handler]);
    }
  }
  persist();
  try {
  options.beforeEvidence?.();
  if (signalShutdownPromise) {
    await signalShutdownPromise;
    return { manifest: manifestFor(), performance: performanceRun };
  }
  const gitAtRoot = (args, execOptions = {}) => execFileSync("git", args, {
    ...execOptions, encoding: "utf8",
  }).trim();
  const repositoryCacheRoot = cacheRoot(process.cwd(), gitAtRoot);
  const runtimeProfileProvider = options.runtimeProfileProvider ?? defaultRuntimeProfile;
  const resolveRuntimeProfile = createCampaignRuntimeProfileResolver(runtimeProfileProvider, environment);
  const executionContexts = new Map();
  for (const shard of shards) {
    let runtimeProfile;
    try {
      runtimeProfile = sanitizedRuntimeProfile(
        await resolveRuntimeProfile(shard),
        isDatabaseBacked(shard),
      );
    } catch {
      runtimeProfile = sanitizedRuntimeProfile(localRuntimeProfile(), false);
      shard.cacheDecision = "rejected";
      shard.reason = "runtime-profile-unavailable";
    }
    const commandList = verificationCommandsForSources(
      shard.sources,
      shard.testFiles,
      { evidencePath: "<projection-evidence>" },
    ).map(([command, args]) => [command, ...args]);
    const commandFiles = commandList.flatMap((command) => command)
      .filter((candidate) => typeof candidate === "string"
        && /\.(?:[cm]?[jt]sx?|json)$/.test(candidate)
        && candidate !== "scripts/verify-pool-snapshot-projection.mjs"
        && existsSync(candidate));
    const configurationFiles = [
      BASE_CONFIG,
      "vitest.mutation.config.mjs",
      "apps/web/vitest.static-contract.config.mjs",
      "packages/db/vitest.config.ts",
      ...(shard.sources.some((source) => PAGE_WIRING_SOURCES.has(source))
        ? ["apps/web/next.config.ts"] : []),
    ]
      .filter((file) => existsSync(file));
    const entryFiles = [...shard.sources, ...shard.testFiles, ...commandFiles]
      .filter((file) => existsSync(file));
    const executionInputs = collectExecutionInputs({
      root: process.cwd(),
      entryFiles,
      configurationFiles,
      staticFiles: [
        ...MUTATION_RUNNER_STATIC_INPUTS,
        ...(shard.sources.includes(POOL_PROJECTION_SOURCE)
          ? POOL_PROJECTION_STATIC_INPUTS : []),
      ].filter((file) => existsSync(file)),
      migrationRoots: isDatabaseBacked(shard) && existsSync("packages/db/src/migrations")
        ? ["packages/db/src/migrations"] : [],
      toolVersions,
      runtimeProfile,
      environment: controlledChildEnvironment({ ...process.env, ...environment }, runtimeProfile),
    });
    shard.dependencyHashes = executionInputs.hashes;
    if (!executionInputs.reusable && shard.cacheDecision !== "rejected") {
      shard.cacheDecision = "rejected";
      shard.reason = executionInputs.reasons[0]?.code ?? "dependency-profile-unavailable";
    }
    shard.evidenceKey = createEvidenceKey({
      shardKind: shard.kind,
      mutate: shard.mutate,
      sources: shard.sources,
      testFiles: shard.testFiles,
      config: normalizeMutationConfigIdentity(shard.config),
      dependencyHashes: shard.dependencyHashes,
      toolVersions,
      runtimeProfile,
      commandList,
    });
    executionContexts.set(shard.id, { commandList, executionInputs, runtimeProfile });
  }
  performanceRun.provenance.campaignKey = sha256(
    shards.map((shard) => shard.evidenceKey).sort().join("\n"),
  );
  persist();
  const executeShard = options.executeShard ?? (({ shard, environment: childEnvironment }) =>
    new Promise((resolveExecution, rejectExecution) => {
      const child = spawn("pnpm", ["exec", "stryker", "run", shard.configPath], {
        detached: true,
        stdio: "inherit",
        env: childEnvironment,
      });
      activeShardProcess = child;
      child.once("error", rejectExecution);
      child.once("close", (status, childSignal) => {
        if (activeShardProcess === child) activeShardProcess = null;
        const signalStatus = childSignal === "SIGINT" ? 130 : childSignal === "SIGTERM" ? 143 : 1;
        resolveExecution({ status: status ?? signalStatus });
      });
    }));
    for (const shard of shards) {
      const { commandList, executionInputs, runtimeProfile } = executionContexts.get(shard.id);
      console.log(`mutation-scope: running ${shard.id} (${shard.mutate.length} ranges)`);
      const performanceToken = startShard(performanceRun, {
        id: shard.id, evidenceKey: shard.evidenceKey, classification: "pending",
      });
      const startedAt = Date.now();
      let cached = null;
      if (cacheMode === "enabled" && shard.cacheDecision !== "rejected") {
        cached = readCacheEntry({
          root: repositoryCacheRoot,
          evidenceKey: shard.evidenceKey,
          validateArtifacts: (artifacts, entry) => {
            if (
              entry.evidenceKey !== shard.evidenceKey
              || entry.shardKind !== shard.kind
              || entry.result !== "passed"
              || !["scored", "verification-only"].includes(entry.classification)
              || canonicalJson(entry.toolVersions) !== canonicalJson(toolVersions)
              || canonicalJson(entry.runtimeProfile) !== canonicalJson(runtimeProfile)
              || canonicalJson(entry.dependencyHashes) !== canonicalJson(shard.dependencyHashes)
              || entry.commandIdentity !== sha256(canonicalJson(commandList))
            ) return false;
            const reportArtifact = artifacts["mutation-report.json"];
            if (!reportArtifact) return false;
            rehydrateCachedReport(reportArtifact, shard.jsonReportPath, shard);
            const projectionPath = projectionEvidencePathForShard(shard);
            if (projectionPath) {
              const projectionArtifact = artifacts["projection-evidence.json"];
              if (!projectionArtifact) return false;
              mkdirSync(dirname(projectionPath), { recursive: true });
              copyFileSync(projectionArtifact, projectionPath);
              validatePoolProjectionEvidence(
                JSON.parse(readFileSync(projectionPath, "utf8")),
                readFileSync(POOL_PROJECTION_SOURCE, "utf8"),
              );
            }
            const report = JSON.parse(readFileSync(shard.jsonReportPath, "utf8"));
            validateMutationReportIdentity(
              report, shard, readFileSync(shard.configPath, "utf8"),
              (source) => readFileSync(source, "utf8"),
            );
            const mutants = mutationReportMutants(report);
            if (mutants.length > 0) {
              if (entry.classification !== "scored") return false;
              validateScoredMutationReport(report, shard.config.thresholds.break, shard.id);
            } else {
              if (entry.classification !== "verification-only") return false;
              requireNonzeroStaticShard(shard.kind, mutants.length, shard.id);
              verificationAuditsForReport(report, shard, allHunks);
            }
            return true;
          },
        });
      }
      if (cached?.hit) {
        shard.classification = cached.entry.classification;
        const cachedReport = JSON.parse(readFileSync(shard.jsonReportPath, "utf8"));
        shard.mutantCount = mutationReportMutants(cachedReport).length;
        shard.reportHash = contentHash(readFileSync(shard.jsonReportPath));
        if (shard.classification === "verification-only") {
          const projectionPath = projectionEvidencePathForShard(shard);
          shard.result = {
            audits: verificationAuditsForReport(cachedReport, shard, allHunks),
            commands: commandList,
            ...(projectionPath
              ? { projectionEvidence: validatePoolProjectionEvidence(
                  JSON.parse(readFileSync(projectionPath, "utf8")),
                  readFileSync(POOL_PROJECTION_SOURCE, "utf8"),
                ) }
              : {}),
            tests: shard.testFiles,
          };
        } else {
          shard.result = "passed";
        }
        shard.cacheDecision = "reused";
        shard.priorDurationMs = cached.entry.durationMs ?? 0;
        const timing = finishShard(performanceRun, performanceToken, "reused", {
          classification: cached.entry.classification,
          result: "passed", priorDurationMs: shard.priorDurationMs,
        });
        shard.durationMs = timing.durationMs;
        persist();
        continue;
      }
      if (cached && !cached.hit && cached.reason !== "not-found") {
        shard.cacheDecision = "rejected";
        shard.reason = cached.reason;
        shard.priorDurationMs = cached.entry?.durationMs ?? null;
      }
      rmSync(shard.jsonReportPath, { force: true });
      rmSync(shard.reportPath, { force: true });
      let shardEnvironment = environment;
      let databaseSandbox = null;
      let databaseSandboxRecord = null;
      if (isDatabaseBacked(shard) && (!options.executeShard || options.databaseSandboxFactory)) {
        const factory = options.databaseSandboxFactory ?? (async (env, id) =>
          createDatabaseShardSandbox(env, id, await import("../packages/db/node_modules/pg/esm/index.mjs")));
        databaseSandboxRecord = {};
        activeDatabaseSandboxes.add(databaseSandboxRecord);
        databaseSandboxRecord.promise = Promise.resolve()
          .then(() => factory(environment, shard.id));
        try {
          databaseSandbox = await databaseSandboxRecord.promise;
        } catch (error) {
          activeDatabaseSandboxes.delete(databaseSandboxRecord);
          throw error;
        }
        shardEnvironment = databaseSandbox.environment;
      }
      if (signalShutdownPromise) {
        await signalShutdownPromise;
        return { manifest: manifestFor(), performance: performanceRun };
      }
      const childEnvironment = controlledChildEnvironment(shardEnvironment, runtimeProfile);
      let result;
      if (shard.kind === EXACT_FRAMEWORK_ADAPTER_KIND) {
        writeFileSync(shard.jsonReportPath, `${JSON.stringify({
          config: {
            configFile: shard.configPath,
            jsonReporter: { fileName: shard.jsonReportPath },
            mutate: shard.mutate,
          },
          files: {},
        })}\n`, "utf8");
        result = { status: 0 };
      } else {
        result = await executeShard({ shard, environment: childEnvironment });
      }
      if (signalShutdownPromise) {
        await signalShutdownPromise;
        return { manifest: manifestFor(), performance: performanceRun };
      }
      const report = readFreshMutationReport(shard.jsonReportPath, startedAt);
      validateMutationReportIdentity(
        report,
        shard,
        readFileSync(shard.configPath, "utf8"),
        (source) => readFileSync(source, "utf8"),
      );
      const mutants = mutationReportMutants(report);
      shard.mutantCount = mutants.length;
      shard.reportHash = contentHash(readFileSync(shard.jsonReportPath));
      if (mutants.length === 0) {
        if (result.status !== 0) {
          throw new Error(`zero-mutant shard ${shard.id} exited ${result.status}`);
        }
        requireNonzeroStaticShard(shard.kind, mutants.length, shard.id);
        const audits = verificationAuditsForReport(report, shard, allHunks);
        const projectionEvidencePath = projectionEvidencePathForShard(shard);
        const commands = verificationCommandsForSources(
          shard.sources,
          shard.testFiles,
          { evidencePath: projectionEvidencePath },
        );
        runVerificationCommands(
          commands,
          options.verificationRunner ?? spawnSync,
          childEnvironment,
        );
        shard.classification = "verification-only";
        shard.result = {
          audits,
          commands: commandList,
          ...(projectionEvidencePath
            ? {
                projectionEvidence: validatePoolProjectionEvidence(
                  JSON.parse(readFileSync(projectionEvidencePath, "utf8")),
                  readFileSync(POOL_PROJECTION_SOURCE, "utf8"),
                ),
              }
            : {}),
          tests: shard.testFiles,
        };
        console.log(`mutation-scope: verified non-mutatable source bundle ${shard.id}`);
      } else {
        validateScoredMutationReport(report, shard.config.thresholds.break, shard.id);
        shard.classification = "scored";
        shard.result = result.status === 0 ? "passed" : "failed";
      }
      if (result.status !== 0) throw Object.assign(new Error(`mutation shard ${shard.id} failed`), { status: result.status ?? 1 });
      const timingDecision = shard.cacheDecision === "rejected" ? "rejected" : "executed";
      const timing = finishShard(performanceRun, performanceToken, timingDecision, {
        classification: shard.classification,
        result: "passed",
        ...(timingDecision === "rejected" ? {
          rejectionReason: shard.reason,
          ...(shard.priorDurationMs === null ? {} : { priorDurationMs: shard.priorDurationMs }),
        } : {}),
      });
      shard.durationMs = timing.durationMs;
      if (shard.cacheDecision === "pending") shard.cacheDecision = "executed";
      if (cacheMode === "enabled" && shard.reason !== "runtime-profile-unavailable"
          && executionInputs.reusable) {
        const artifacts = { "mutation-report.json": shard.jsonReportPath };
        const artifactProjectors = {
          "mutation-report.json": projectMutationReportArtifact,
        };
        const projectionPath = projectionEvidencePathForShard(shard);
        if (projectionPath && existsSync(projectionPath)) {
          artifacts["projection-evidence.json"] = projectionPath;
          const sourceContents = readFileSync(POOL_PROJECTION_SOURCE, "utf8");
          artifactProjectors["projection-evidence.json"] = (evidence) =>
            validatePoolProjectionEvidence(evidence, sourceContents);
        }
        writeSuccessfulCacheEntry({
          root: repositoryCacheRoot,
          evidenceKey: shard.evidenceKey,
          entry: {
            result: "passed", shardKind: shard.kind, classification: shard.classification,
            durationMs: shard.durationMs, toolVersions, runtimeProfile,
            dependencyHashes: shard.dependencyHashes, commandList,
          },
          artifacts,
          artifactProjectors,
        });
      }
      persist();
      if (databaseSandboxRecord) {
        await cleanupDatabaseSandbox(databaseSandboxRecord);
      }
    }
    finishPerformanceRun(performanceRun, "passed");
    persist();
    return { manifest: manifestFor(), performance: performanceRun };
  } catch (err) {
    // A non-zero Stryker exit IS the gate failing — propagate the code, but not
    // execFileSync's exception: an uncaught throw prints a JS stack trace after
    // Stryker's own report, which reads as "the tool is broken" rather than
    // "your mutation score is short".
    if (err?.message) console.error(`mutation-scope: ${err.message}`);
    try {
      finishPerformanceRun(performanceRun, "failed");
      persist();
    } catch { /* retain the original mutation failure */ }
    throw err;
  }
  } finally {
    await cleanupAllDatabaseSandboxes();
    for (const [signal, handler] of signalHandlers) signalProcess.removeListener(signal, handler);
    for (const [key, value] of Object.entries(previousEnvironment)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
    if (options.cwd) process.chdir(previousCwd);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    await runMutationScope();
  } catch (error) {
    if (error?.message) console.error(`mutation-scope: ${error.message}`);
    process.exit(typeof error?.status === "number" ? error.status : 1);
  }
}
