#!/usr/bin/env node
// mutation-scope — diff-scoped Stryker run (generated by Nous, IMP-344 / L1).
//
// ONE campaign over the files this branch actually changed, instead of a
// whole-tree run or a hand-chained per-story sequence. The common case — a diff
// with nothing mutatable — exits 0 in milliseconds without starting Stryker.
//
// Scope is the DIFF, filtered to mutatable source files. Deliberately NOT
// intersected with the critical set: nothing declares critical source *paths*,
// and guessing them could only drop a changed critical file from the run. The
// critical set decides which STORIES owe mutation evidence (see
// docs/dev-guide/TESTING.md §3), not which files get mutated.
//
// Env overrides:
//   MUTATION_BASE=<ref>   compare against this ref instead of the default branch
//   MUTATION_SCOPE_DRY=1  write + print the generated config, do NOT run Stryker
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const BASE_CONFIG = "stryker.conf.json";
const GENERATED_CONFIG = join(".tmp", "stryker.generated.conf.json");

// Mirrors stryker.conf.json's mutate globs: which files can carry mutants.
// This is a FILE-TYPE filter, not a critical-set narrowing — a changed `.md` or
// `.json` has no mutants, so excluding it removes nothing real.
const MUTATABLE_EXT = /\.(ts|tsx)$/;
const EXCLUDED = [
  /\.(test|spec)\.tsx?$/,
  /\.d\.ts$/,
  /(^|\/)migrations\//,
  /(^|\/)testing\//,
  /(^|\/)node_modules\//,
];

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

/** A git call whose FAILURE is an expected, handled outcome (probing for a ref
 *  that may not exist). git writes `fatal: ...` to stderr even when the caller
 *  copes, so stderr is discarded here — otherwise every run in a repo without
 *  `origin/HEAD` prints a scary line that is not an error. Real failures still
 *  surface: the caller decides, via the thrown exception. */
function gitProbe(args) {
  return execFileSync("git", args, {
    encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

/** Fail LOUD. A mutation run that cannot determine its scope must NOT report
 *  success having mutated nothing — a silent empty scope is a false green. */
function fail(message, hint) {
  console.error(`mutation-scope: ${message}`);
  if (hint) console.error(`  ${hint}`);
  process.exit(2);
}

/** The ref to diff against. Resolved, never hardcoded to `main`: a repo whose
 *  trunk is `master`, or a CI checkout with a different default, must not
 *  silently produce an empty diff. */
function resolveBase() {
  if (process.env.MUTATION_BASE) {
    const ref = process.env.MUTATION_BASE;
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch {
      fail(`MUTATION_BASE=${ref} does not resolve to a ref`,
           "check the ref name, or unset MUTATION_BASE to use the default branch");
    }
  }
  try {
    // origin/HEAD is the authoritative default branch when a remote exists.
    const sym = gitProbe(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"]);
    if (sym) return sym;
  } catch { /* no remote / no origin/HEAD — fall through to local trunks */ }
  for (const ref of ["main", "master"]) {
    try {
      gitProbe(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch { /* try the next candidate */ }
  }
  fail("cannot resolve a default branch to diff against (tried origin/HEAD, main, master)",
       "set MUTATION_BASE=<ref> explicitly");
}

function changedFiles(base) {
  let mergeBase;
  try {
    mergeBase = gitProbe(["merge-base", "HEAD", base]);
  } catch {
    // A shallow clone or an unrelated history has no merge base. Exiting 0 here
    // would mutate nothing and report success — the false green this guard
    // exists to prevent.
    fail(`no merge base between HEAD and ${base}`,
         "unshallow the clone (git fetch --unshallow) or set MUTATION_BASE=<ref>");
  }
  // ACMR excludes deletions: Stryker cannot mutate a file that is gone.
  const out = git(["diff", "--name-only", "--diff-filter=ACMR", `${mergeBase}..HEAD`]);
  return out ? out.split("\n").filter(Boolean) : [];
}

function mutatable(files) {
  return files
    .filter((f) => MUTATABLE_EXT.test(f))
    .filter((f) => !EXCLUDED.some((re) => re.test(f)))
    .sort();  // deterministic: the generated config must be byte-stable
}

function main() {
  const base = resolveBase();
  const changed = changedFiles(base);
  const mutate = mutatable(changed);

  console.log(`mutation-scope: base=${base} changed=${changed.length} mutatable=${mutate.length}`);

  if (mutate.length === 0) {
    console.log("mutation-scope: no mutatable files in diff — nothing to mutate");
    process.exit(0);
  }

  let baseConf = {};
  try {
    baseConf = JSON.parse(readFileSync(BASE_CONFIG, "utf8"));
  } catch {
    fail(`cannot read ${BASE_CONFIG}`, "run from the repository root");
  }

  // tempDirName is derived from the SCOPE, not the clock: two runs on the same
  // diff must produce a byte-identical config, and two runs on different scopes
  // must not collide.
  const digest = createHash("sha256").update(mutate.join("\n")).digest("hex").slice(0, 12);

  const conf = {
    ...baseConf,
    mutate,
    // Settings the hand-rolled per-story configs converged on empirically, now
    // generated defaults: a real DB fixture makes perTest coverage analysis
    // unsound, and parallel runners race on shared database state.
    coverageAnalysis: "off",
    concurrency: 1,
    maxTestRunnerReuse: 1,
    timeoutFactor: 2,
    tempDirName: join(".tmp", `stryker-${digest}`),
  };

  mkdirSync(dirname(GENERATED_CONFIG), { recursive: true });
  writeFileSync(GENERATED_CONFIG, `${JSON.stringify(conf, null, 2)}\n`, "utf8");
  console.log(`mutation-scope: wrote ${GENERATED_CONFIG}`);

  if (process.env.MUTATION_SCOPE_DRY === "1") {
    console.log("mutation-scope: MUTATION_SCOPE_DRY=1 — not running Stryker");
    process.exit(0);
  }

  try {
    execFileSync("pnpm", ["exec", "stryker", "run", GENERATED_CONFIG], { stdio: "inherit" });
  } catch (err) {
    // A non-zero Stryker exit IS the gate failing — propagate the code, but not
    // execFileSync's exception: an uncaught throw prints a JS stack trace after
    // Stryker's own report, which reads as "the tool is broken" rather than
    // "your mutation score is short".
    process.exit(typeof err?.status === "number" ? err.status : 1);
  }
}

main();
