// Vitest config (generated by Nous, IMP-305 / TE-2). A package can have the
// runner wired before it has any tests; `passWithNoTests` keeps that GREEN.
// The dev team adds tests per docs/dev-guide/TESTING.md §4 — an empty suite
// is not a failure, a broken one is.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    // Most DB tests provision a real pinned PostgreSQL container. Serialize
    // files so Docker startup is deterministic rather than port-race bound.
    fileParallelism: false,
    passWithNoTests: true,
    include: ["src/**/*.{test,spec}.ts"],
  },
});
